package org.novasos.healthysv2.maternalandchildhealth;
import jakarta.persistence.*;import java.math.*;import java.time.*;import java.util.*;

@Entity @Table(name="child_health_record",schema="maternal_child") class ChildHealthRecord{
 @Id private UUID id;@Column(name="child_patient_id",nullable=false,unique=true)private UUID childPatientId;@Column(name="mother_patient_id")private UUID motherPatientId;@Column(name="created_at",nullable=false,updatable=false)private Instant createdAt;@Column(nullable=false,length=30)private String status;@OneToMany(mappedBy="record",cascade=CascadeType.ALL,orphanRemoval=true)private List<Vaccination> vaccinations=new ArrayList<>();@OneToMany(mappedBy="record",cascade=CascadeType.ALL,orphanRemoval=true)private List<GrowthMeasurement> measurements=new ArrayList<>();
 protected ChildHealthRecord(){}static ChildHealthRecord open(UUID child,UUID mother){var x=new ChildHealthRecord();x.id=UUID.randomUUID();x.childPatientId=Objects.requireNonNull(child);x.motherPatientId=mother;x.createdAt=Instant.now();x.status="ACTIVE";return x;}Vaccination addVaccination(UUID vaccine,Integer dose,Instant administeredAt,UUID administeredBy,UUID organization,String batch,LocalDate nextDue,String status){ensureActive();var v=Vaccination.create(this,vaccine,dose,administeredAt,administeredBy,organization,batch,nextDue,status);vaccinations.add(v);return v;}GrowthMeasurement addMeasurement(Instant at,BigDecimal weight,BigDecimal height,BigDecimal head,UUID by){ensureActive();if(weight==null&&height==null&&head==null)throw new IllegalArgumentException("Measurement required");var m=GrowthMeasurement.create(this,at,weight,height,head,by);measurements.add(m);return m;}private void ensureActive(){if(!"ACTIVE".equals(status))throw new IllegalStateException("Record is inactive");}
 UUID getId(){return id;}UUID getChildPatientId(){return childPatientId;}UUID getMotherPatientId(){return motherPatientId;}Instant getCreatedAt(){return createdAt;}String getStatus(){return status;}List<Vaccination> getVaccinations(){return vaccinations;}List<GrowthMeasurement> getMeasurements(){return measurements;}
}
@Entity @Table(name="vaccination",schema="maternal_child") class Vaccination{@Id private UUID id;@ManyToOne(fetch=FetchType.LAZY)@JoinColumn(name="child_patient_id",referencedColumnName="child_patient_id",nullable=false)private ChildHealthRecord record;@Column(name="vaccine_catalog_id",nullable=false)private UUID vaccineCatalogId;@Column(name="dose_number")private Integer doseNumber;@Column(name="administered_at")private Instant administeredAt;@Column(name="administered_by")private UUID administeredBy;@Column(name="organization_id")private UUID organizationId;@Column(name="batch_number",length=100)private String batchNumber;@Column(name="next_due_date")private LocalDate nextDueDate;@Column(nullable=false,length=30)private String status;protected Vaccination(){}static Vaccination create(ChildHealthRecord r,UUID vaccine,Integer dose,Instant at,UUID by,UUID org,String batch,LocalDate next,String status){var x=new Vaccination();x.id=UUID.randomUUID();x.record=r;x.vaccineCatalogId=Objects.requireNonNull(vaccine);x.doseNumber=dose;x.administeredAt=at;x.administeredBy=by;x.organizationId=org;x.batchNumber=Values.optional(batch);x.nextDueDate=next;x.status=Values.normalize(status,at==null?"PLANNED":"ADMINISTERED");return x;}UUID getId(){return id;}UUID getVaccineCatalogId(){return vaccineCatalogId;}Integer getDoseNumber(){return doseNumber;}Instant getAdministeredAt(){return administeredAt;}UUID getAdministeredBy(){return administeredBy;}UUID getOrganizationId(){return organizationId;}String getBatchNumber(){return batchNumber;}LocalDate getNextDueDate(){return nextDueDate;}String getStatus(){return status;}}
@Entity @Table(name="growth_measurement",schema="maternal_child") class GrowthMeasurement{@Id private UUID id;@ManyToOne(fetch=FetchType.LAZY)@JoinColumn(name="child_patient_id",referencedColumnName="child_patient_id",nullable=false)private ChildHealthRecord record;@Column(name="measured_at",nullable=false)private Instant measuredAt;private BigDecimal weight,height;@Column(name="head_circumference")private BigDecimal headCircumference;private BigDecimal bmi;@Column(name="measured_by")private UUID measuredBy;protected GrowthMeasurement(){}static GrowthMeasurement create(ChildHealthRecord r,Instant at,BigDecimal weight,BigDecimal height,BigDecimal head,UUID by){var x=new GrowthMeasurement();x.id=UUID.randomUUID();x.record=r;x.measuredAt=at==null?Instant.now():at;x.weight=weight;x.height=height;x.headCircumference=head;x.bmi=weight!=null&&height!=null&&height.signum()>0?weight.divide(height.movePointLeft(2).pow(2),2,RoundingMode.HALF_UP):null;x.measuredBy=by;return x;}UUID getId(){return id;}Instant getMeasuredAt(){return measuredAt;}BigDecimal getWeight(){return weight;}BigDecimal getHeight(){return height;}BigDecimal getHeadCircumference(){return headCircumference;}BigDecimal getBmi(){return bmi;}UUID getMeasuredBy(){return measuredBy;}}
