package org.novasos.healthysv2.maternalandchildhealth;
import static org.novasos.healthysv2.maternalandchildhealth.api.MaternalChildDtos.*;import java.net.*;import java.util.*;import jakarta.validation.Valid;import io.swagger.v3.oas.annotations.tags.Tag;import org.novasos.healthysv2.shared.api.ApiPaths;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping(ApiPaths.V1) @Tag(name="Maternal and child health",description="Pregnancy, prenatal care, birth, vaccination and growth records") @PreAuthorize("hasAnyRole('PLATFORM_ADMIN','HOSPITAL_ADMIN','DOCTOR','NURSE','PATIENT')") class MaternalChildController{
 private static final String CLINICAL="hasAnyRole('PLATFORM_ADMIN','HOSPITAL_ADMIN','DOCTOR','NURSE')";private final MaternalChildService service;MaternalChildController(MaternalChildService service){this.service=service;}
 @PostMapping("/pregnancies")@PreAuthorize(CLINICAL)ResponseEntity<PregnancyResponse>start(@Valid@RequestBody StartPregnancyRequest r){var out=service.start(r);return ResponseEntity.created(URI.create(ApiPaths.V1+"/pregnancies/"+out.id())).body(out);}
 @GetMapping("/pregnancies")List<PregnancySummary>search(@RequestParam UUID motherPatientId){return service.search(motherPatientId);}@GetMapping("/pregnancies/{id}")PregnancyResponse find(@PathVariable UUID id){return service.find(id);}
 @PostMapping("/pregnancies/{id}/prenatal-visits")@PreAuthorize(CLINICAL)ResponseEntity<PrenatalVisitResponse>visit(@PathVariable UUID id,@Valid@RequestBody PrenatalVisitRequest r){return ResponseEntity.status(201).body(service.addVisit(id,r));}
 @PostMapping("/pregnancies/{id}/risks")@PreAuthorize(CLINICAL)ResponseEntity<PregnancyRiskResponse>risk(@PathVariable UUID id,@Valid@RequestBody PregnancyRiskRequest r){return ResponseEntity.status(201).body(service.addRisk(id,r));}@PostMapping("/pregnancies/{id}/risks/{risk}/resolve")@PreAuthorize(CLINICAL)PregnancyRiskResponse resolve(@PathVariable UUID id,@PathVariable UUID risk){return service.resolveRisk(id,risk);}
 @PostMapping("/pregnancies/{id}/delivery")@PreAuthorize(CLINICAL)ResponseEntity<DeliveryResponse>delivery(@PathVariable UUID id,@Valid@RequestBody DeliveryRequest r){return ResponseEntity.status(201).body(service.deliver(id,r));}@PostMapping("/pregnancies/{id}/postpartum-visits")@PreAuthorize(CLINICAL)ResponseEntity<PostpartumVisitResponse>postpartum(@PathVariable UUID id,@Valid@RequestBody PostpartumVisitRequest r){return ResponseEntity.status(201).body(service.addPostpartum(id,r));}
 @GetMapping("/child-health-records/{childPatientId}")ChildHealthRecordResponse child(@PathVariable UUID childPatientId){return service.childRecord(childPatientId);}@PostMapping("/child-health-records/{childPatientId}/vaccinations")@PreAuthorize(CLINICAL)ResponseEntity<VaccinationResponse>vaccinate(@PathVariable UUID childPatientId,@Valid@RequestBody VaccinationRequest r){return ResponseEntity.status(201).body(service.vaccinate(childPatientId,r));}@PostMapping("/child-health-records/{childPatientId}/growth-measurements")@PreAuthorize(CLINICAL)ResponseEntity<GrowthMeasurementResponse>measure(@PathVariable UUID childPatientId,@Valid@RequestBody GrowthMeasurementRequest r){return ResponseEntity.status(201).body(service.measure(childPatientId,r));}
}
