package org.novasos.healthysv2.maternalandchildhealth;
import static org.novasos.healthysv2.maternalandchildhealth.api.PatientMaternalChildDtos.*;
import java.sql.*;
import java.time.*;
import java.util.*;
import org.novasos.healthysv2.audit.AuditTrail;
import org.novasos.healthysv2.maternalandchildhealth.api.MaternalChildDtos.PregnancySummary;
import org.novasos.healthysv2.patient.PatientSelfAccess;
import org.novasos.healthysv2.shared.api.dto.PageResponse;
import org.novasos.healthysv2.shared.api.error.*;
import org.springframework.data.domain.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
@Service @Transactional(readOnly=true)
class PatientMaternalChildService {
 private static final String CHILD="select r.id,r.child_patient_id,r.mother_patient_id,r.status,r.created_at,p.first_name,p.last_name,p.birth_date,p.gender from maternal_child.child_health_record r join patient.patient c on c.id=r.child_patient_id join identity.person p on p.id=c.person_id ";
 private final PatientSelfAccess selves; private final JdbcTemplate jdbc; private final AuditTrail audit;
 PatientMaternalChildService(PatientSelfAccess selves,JdbcTemplate jdbc,AuditTrail audit){this.selves=selves;this.jdbc=jdbc;this.audit=audit;}
 PageResponse<PregnancySummary> pregnancies(UUID subject,int page,int size){var self=selves.resolve(subject);checkPage(page,size);long total=count("select count(*) from maternal_child.pregnancy where mother_patient_id=?",self.patient());var content=jdbc.query("select * from maternal_child.pregnancy where mother_patient_id=? order by created_at desc,id desc limit ? offset ?",this::summary,self.patient(),size,(long)page*size);accessed(self,self.patient(),"MATERNAL_HEALTH","LIST");return PageResponse.from(new PageImpl<>(content,PageRequest.of(page,size),total));}
 PregnancyDetail pregnancy(UUID subject,UUID id){var self=selves.resolve(subject);var rows=jdbc.query("select * from maternal_child.pregnancy where id=?",this::summary,id);if(rows.isEmpty())throw new ResourceNotFoundException("Pregnancy",id);var pregnancy=rows.getFirst();if(!self.patient().equals(pregnancy.motherPatientId())){accessed(self,pregnancy.motherPatientId(),id,"MATERNAL_HEALTH","DENIED");throw new AccessDeniedException("Pregnancy belongs to another patient");}
 var dates=jdbc.query("select estimated_conception_date,last_menstrual_period from maternal_child.pregnancy where id=?",(rs,row)->new LocalDate[]{date(rs,"estimated_conception_date"),date(rs,"last_menstrual_period")},id).getFirst();
 var visits=jdbc.query("select id,visit_date,gestational_age_weeks,weight,systolic_pressure,diastolic_pressure,fetal_heart_rate from maternal_child.prenatal_visit where pregnancy_id=? order by visit_date desc,id desc",(rs,row)->new Prenatal(uuid(rs,"id"),instant(rs,"visit_date"),integer(rs,"gestational_age_weeks"),rs.getBigDecimal("weight"),integer(rs,"systolic_pressure"),integer(rs,"diastolic_pressure"),integer(rs,"fetal_heart_rate")),id);
 var deliveries=jdbc.query("select id,delivery_date,delivery_type from maternal_child.delivery where pregnancy_id=?",(rs,row)->new org.novasos.healthysv2.maternalandchildhealth.api.PatientMaternalChildDtos.Delivery(uuid(rs,"id"),instant(rs,"delivery_date"),rs.getString("delivery_type"),newborns(uuid(rs,"id"))),id);
 accessed(self,self.patient(),id,"MATERNAL_HEALTH","READ");return new PregnancyDetail(pregnancy,dates[0],dates[1],visits,deliveries.isEmpty()?null:deliveries.getFirst());}
 PageResponse<ChildSummary> children(UUID subject,int page,int size){var self=selves.resolve(subject);checkPage(page,size);long total=count("select count(*) from maternal_child.child_health_record where child_patient_id=? or mother_patient_id=?",self.patient(),self.patient());var content=jdbc.query(CHILD+"where r.child_patient_id=? or r.mother_patient_id=? order by r.created_at desc,r.id desc limit ? offset ?",this::childSummary,self.patient(),self.patient(),size,(long)page*size);accessed(self,self.patient(),"PEDIATRIC_RECORD","LIST");return PageResponse.from(new PageImpl<>(content,PageRequest.of(page,size),total));}
 ChildDetail child(UUID subject,UUID child){var self=selves.resolve(subject);requireChild(self,child);var summary=jdbc.query(CHILD+"where r.child_patient_id=?",this::childSummary,child).getFirst();
 var births=jdbc.query("select d.delivery_date,d.delivery_type,n.birth_order,n.birth_weight,n.birth_height,n.head_circumference,n.apgar_1,n.apgar_5,n.status from maternal_child.newborn n join maternal_child.delivery d on d.id=n.delivery_id where n.child_patient_id=?",(rs,row)->new Birth(instant(rs,"delivery_date"),rs.getString("delivery_type"),integer(rs,"birth_order"),rs.getBigDecimal("birth_weight"),rs.getBigDecimal("birth_height"),rs.getBigDecimal("head_circumference"),rs.getObject("apgar_1",Short.class),rs.getObject("apgar_5",Short.class),rs.getString("status")),child);
 var vaccines=jdbc.query("select v.id,v.vaccine_catalog_id,c.code,c.name,v.dose_number,v.administered_at,v.next_due_date,v.status from maternal_child.vaccination v join catalog.vaccine_catalog c on c.id=v.vaccine_catalog_id where v.child_patient_id=? order by coalesce(v.administered_at, v.next_due_date::timestamptz) desc nulls last,v.id desc",(rs,row)->new org.novasos.healthysv2.maternalandchildhealth.api.PatientMaternalChildDtos.Vaccination(uuid(rs,"id"),uuid(rs,"vaccine_catalog_id"),rs.getString("code"),rs.getString("name"),integer(rs,"dose_number"),instant(rs,"administered_at"),date(rs,"next_due_date"),rs.getString("status")),child);
 var growth=jdbc.query("select id,measured_at,weight,height,head_circumference,bmi from maternal_child.growth_measurement where child_patient_id=? order by measured_at desc,id desc",(rs,row)->new Growth(uuid(rs,"id"),instant(rs,"measured_at"),rs.getBigDecimal("weight"),rs.getBigDecimal("height"),rs.getBigDecimal("head_circumference"),rs.getBigDecimal("bmi")),child);
 accessed(self,child,"PEDIATRIC_RECORD","READ");return new ChildDetail(summary,births.isEmpty()?null:births.getFirst(),vaccines,growth);}
 void requireChild(PatientSelfAccess.Identity self,UUID child){var mothers=jdbc.query("select mother_patient_id from maternal_child.child_health_record where child_patient_id=?",(rs,row)->uuid(rs,"mother_patient_id"),child);if(mothers.isEmpty())throw new ResourceNotFoundException("ChildHealthRecord",child);if(!self.patient().equals(child)&&!self.patient().equals(mothers.getFirst())){accessed(self,child,"PEDIATRIC_RECORD","DENIED");throw new AccessDeniedException("Child is not linked to this patient");}}
 void requireLegacyChild(UUID child){var authentication=org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication();if(!(authentication instanceof org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken jwt))throw new AccessDeniedException("Patient authentication required");try{var self=selves.resolve(UUID.fromString(jwt.getToken().getSubject()));requireChild(self,child);accessed(self,child,"PEDIATRIC_RECORD","READ");}catch(ResourceNotFoundException|IllegalArgumentException exception){throw new AccessDeniedException("Linked patient identity required");}}
 private List<org.novasos.healthysv2.maternalandchildhealth.api.PatientMaternalChildDtos.Newborn> newborns(UUID delivery){return jdbc.query("select id,child_patient_id,birth_order,birth_weight,birth_height,head_circumference,apgar_1,apgar_5,status from maternal_child.newborn where delivery_id=? order by birth_order,id",(rs,row)->new org.novasos.healthysv2.maternalandchildhealth.api.PatientMaternalChildDtos.Newborn(uuid(rs,"id"),uuid(rs,"child_patient_id"),integer(rs,"birth_order"),rs.getBigDecimal("birth_weight"),rs.getBigDecimal("birth_height"),rs.getBigDecimal("head_circumference"),rs.getObject("apgar_1",Short.class),rs.getObject("apgar_5",Short.class),rs.getString("status")),delivery);}
 private PregnancySummary summary(ResultSet rs,int row)throws SQLException{return new PregnancySummary(uuid(rs,"id"),rs.getString("pregnancy_number"),uuid(rs,"mother_patient_id"),date(rs,"expected_delivery_date"),rs.getString("status"),instant(rs,"created_at"));}
 private ChildSummary childSummary(ResultSet rs,int row)throws SQLException{return new ChildSummary(uuid(rs,"id"),uuid(rs,"child_patient_id"),rs.getString("first_name"),rs.getString("last_name"),date(rs,"birth_date"),rs.getString("gender"),rs.getString("status"),instant(rs,"created_at"));}
 private UUID uuid(ResultSet rs,String key)throws SQLException{return rs.getObject(key,UUID.class);}private Integer integer(ResultSet rs,String key)throws SQLException{return rs.getObject(key,Integer.class);}private LocalDate date(ResultSet rs,String key)throws SQLException{return rs.getObject(key,LocalDate.class);}private Instant instant(ResultSet rs,String key)throws SQLException{var t=rs.getTimestamp(key);return t==null?null:t.toInstant();}
 private long count(String sql,Object...args){return Objects.requireNonNull(jdbc.queryForObject(sql,Long.class,args));}private void checkPage(int page,int size){if(page<0||size<1||size>100)throw new BusinessRuleException("INVALID_PAGE","error.malformed");}
 private void accessed(PatientSelfAccess.Identity self,UUID patient,String resource,String action){accessed(self,patient,patient,resource,action);}
 private void accessed(PatientSelfAccess.Identity self,UUID patient,UUID resourceId,String resource,String action){audit.access(self.person(),patient,null,resource,resourceId,action,"PATIENT_SELF",Map.of("allowed",!"DENIED".equals(action)));}
}
