package org.novasos.healthysv2.maternalandchildhealth;
import jakarta.persistence.*;import java.math.*;import java.time.*;import java.util.*;

@Entity @Table(name="pregnancy",schema="maternal_child") class Pregnancy{
 @Id private UUID id;@Column(name="pregnancy_number",nullable=false,unique=true,length=50)private String number;@Column(name="mother_patient_id",nullable=false)private UUID motherPatientId;@Column(name="estimated_conception_date")private LocalDate conceptionDate;@Column(name="last_menstrual_period")private LocalDate lastMenstrualPeriod;@Column(name="expected_delivery_date")private LocalDate expectedDeliveryDate;@Column(nullable=false,length=30)private String status;@Column(name="created_at",nullable=false,updatable=false)private Instant createdAt;
 @OneToMany(mappedBy="pregnancy",cascade=CascadeType.ALL,orphanRemoval=true)private List<PrenatalVisit> visits=new ArrayList<>();@OneToMany(mappedBy="pregnancy",cascade=CascadeType.ALL,orphanRemoval=true)private List<PregnancyRisk> risks=new ArrayList<>();@OneToOne(mappedBy="pregnancy",cascade=CascadeType.ALL)private Delivery delivery;@OneToMany(mappedBy="pregnancy",cascade=CascadeType.ALL,orphanRemoval=true)private List<PostpartumVisit> postpartumVisits=new ArrayList<>();
 protected Pregnancy(){}static Pregnancy start(UUID mother,LocalDate conception,LocalDate lmp,LocalDate due){validateDates(conception,lmp,due);var x=new Pregnancy();x.id=UUID.randomUUID();x.number="PRG-"+x.id.toString().replace("-","").substring(0,20).toUpperCase();x.motherPatientId=Objects.requireNonNull(mother);x.conceptionDate=conception;x.lastMenstrualPeriod=lmp;x.expectedDeliveryDate=due;x.status="ACTIVE";x.createdAt=Instant.now();return x;}
 PrenatalVisit addVisit(UUID consultation,UUID professional,Instant date,Integer weeks,BigDecimal weight,Integer systolic,Integer diastolic,Integer fetalHeartRate,String notes){ensureActive();var v=PrenatalVisit.create(this,consultation,professional,date,weeks,weight,systolic,diastolic,fetalHeartRate,notes);visits.add(v);return v;}PregnancyRisk addRisk(String type,String severity,String notes){ensureActive();var r=PregnancyRisk.create(this,type,severity,notes);risks.add(r);return r;}void resolveRisk(UUID id){ensureActive();var r=risks.stream().filter(x->x.getId().equals(id)).findFirst().orElseThrow(NoSuchElementException::new);r.resolve();}
 Delivery deliver(UUID organization,Instant date,String type,UUID professional,String complications,String notes,List<NewbornData> newborns){ensureActive();if(delivery!=null)throw new IllegalStateException("Delivery already exists");if(newborns==null||newborns.isEmpty())throw new IllegalArgumentException("A delivery needs a newborn");delivery=Delivery.create(this,organization,date,type,professional,complications,notes,newborns);status="DELIVERED";return delivery;}PostpartumVisit addPostpartumVisit(UUID mother,UUID professional,Instant date,String notes,String status){if(delivery==null)throw new IllegalStateException("Delivery is required");if(!motherPatientId.equals(mother))throw new IllegalArgumentException("Mother mismatch");var v=PostpartumVisit.create(this,mother,professional,date,notes,status);postpartumVisits.add(v);return v;}
 private void ensureActive(){if(!"ACTIVE".equals(status))throw new IllegalStateException("Pregnancy is not active");}private static void validateDates(LocalDate conception,LocalDate lmp,LocalDate due){LocalDate start=conception!=null?conception:lmp;if(start!=null&&due!=null&&!due.isAfter(start))throw new IllegalArgumentException("Invalid pregnancy dates");}
 UUID getId(){return id;}String getNumber(){return number;}UUID getMotherPatientId(){return motherPatientId;}LocalDate getConceptionDate(){return conceptionDate;}LocalDate getLastMenstrualPeriod(){return lastMenstrualPeriod;}LocalDate getExpectedDeliveryDate(){return expectedDeliveryDate;}String getStatus(){return status;}Instant getCreatedAt(){return createdAt;}List<PrenatalVisit> getVisits(){return visits;}List<PregnancyRisk> getRisks(){return risks;}Delivery getDelivery(){return delivery;}List<PostpartumVisit> getPostpartumVisits(){return postpartumVisits;}
 record NewbornData(UUID childPatientId,Integer birthOrder,BigDecimal weight,BigDecimal height,BigDecimal headCircumference,Short apgar1,Short apgar5){}
}
