import {useState} from 'react';
import {useMutation,useQuery} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import {searchPersons,createPerson} from '../api/persons';
import {useAuth} from '../auth/AuthContext';
import {ApiErrorMessage} from './ApiErrorMessage';

export function PersonPicker({value,onChange}:{value:string;onChange:(id:string)=>void}){
 const {t,i18n}=useTranslation();const fr=i18n.language.startsWith('fr');const [query,setQuery]=useState('');const [page,setPage]=useState(0);
 const auth=useAuth();const isAdmin=auth.hasAnyRole('PLATFORM_ADMIN');const [create,setCreate]=useState(false);const [form,setForm]=useState({firstName:'',lastName:'',birthDate:'',gender:''});const [createdName,setCreatedName]=useState('');const mutation=useMutation({mutationFn:createPerson,onSuccess:person=>{onChange(person.id);setCreatedName(`${person.firstName} ${person.lastName} · ${person.personNumber}`);setCreate(false)}});const persons=useQuery({enabled:isAdmin,queryKey:['persons','picker',query,page],queryFn:()=>searchPersons(query,page)});
 return <div className="relation-picker">{isAdmin&&<><label>{fr?'Rechercher une personne':'Search for a person'}<input type="search" value={query} placeholder={fr?'Nom ou code personne':'Name or person code'} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></label><label>{fr?'Personne':'Person'}<select required value={value} onChange={e=>onChange(e.target.value)}><option value="">{fr?'Sélectionner une personne':'Select a person'}</option>{value&&!persons.data?.content.some(person=>person.id===value)&&<option value={value}>{createdName||value}</option>}{persons.data?.content.map(person=><option key={person.id} value={person.id}>{person.firstName} {person.lastName} · {person.personNumber}</option>)}</select></label>{persons.isError&&<ApiErrorMessage error={persons.error}/>}<div className="inline-actions"><button type="button" className="button-secondary" disabled={page===0} onClick={()=>setPage(page-1)}>{fr?'Précédent':'Previous'}</button><span>{page+1} / {Math.max(1,persons.data?.page.totalPages??1)}</span><button type="button" className="button-secondary" disabled={!persons.data||page+1>=persons.data.page.totalPages} onClick={()=>setPage(page+1)}>{fr?'Suivant':'Next'}</button></div>{persons.isPending&&<p>{t('common.loading')}</p>}</>} {createdName&&<p role="status">{createdName}</p>}<button type="button" className="secondary" onClick={()=>setCreate(!create)}>{fr?'Créer une nouvelle personne':'Create a new person'}</button>{create&&<div className="form-grid"><label>{fr?'Prénom':'First name'}<input maxLength={120} value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></label><label>{fr?'Nom':'Last name'}<input maxLength={120} value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></label><label>{fr?'Date de naissance':'Birth date'}<input type="date" max={new Date().toISOString().slice(0,10)} value={form.birthDate} onChange={e=>setForm({...form,birthDate:e.target.value})}/></label><label>{fr?'Sexe':'Sex'}<select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option value="">—</option>{['female','male','other','unspecified'].map(gender=><option key={gender}>{gender}</option>)}</select></label><button type="button" disabled={mutation.isPending||!form.firstName.trim()||!form.lastName.trim()} onClick={()=>mutation.mutate({...form,birthDate:form.birthDate||undefined,gender:form.gender||undefined})}>{t('common.create')}</button>{mutation.isError&&<ApiErrorMessage error={mutation.error}/>}</div>}</div>;
}
