package org.novasos.healthysv2.patient;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.time.*; import java.util.*; import org.junit.jupiter.api.Test; import org.novasos.healthysv2.TestcontainersConfiguration; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.*; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.context.annotation.*; import org.springframework.http.HttpHeaders; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.oauth2.jwt.*; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc; import org.springframework.transaction.annotation.Transactional;

@ActiveProfiles("test") @SpringBootTest(properties={"spring.security.oauth2.resourceserver.jwt.issuer-uri=https://keycloak.example/realms/healthys","spring.security.oauth2.resourceserver.jwt.audiences=healthys-backend-apps","healthys.security.api-client-id=healthys-backend-apps","healthys.security.cors.allowed-origins=http://localhost:5173"}) @AutoConfigureMockMvc @Import({TestcontainersConfiguration.class,PatientAccessApiIntegrationTests.JwtFixtures.class}) @Transactional
class PatientAccessApiIntegrationTests {
 static final UUID DOCTOR_KEYCLOAK=UUID.fromString("10000000-0000-0000-0000-000000000001"),DOCTOR_PERSON=UUID.fromString("10000000-0000-0000-0000-000000000002"),DOCTOR_PROFESSIONAL=UUID.fromString("10000000-0000-0000-0000-000000000003"),UNASSIGNED_KEYCLOAK=UUID.fromString("10000000-0000-0000-0000-000000000004"),UNASSIGNED_PERSON=UUID.fromString("10000000-0000-0000-0000-000000000005"),UNASSIGNED_PROFESSIONAL=UUID.fromString("10000000-0000-0000-0000-000000000006"),ORGANIZATION=UUID.fromString("20000000-0000-0000-0000-000000000001"),OTHER_ORGANIZATION=UUID.fromString("20000000-0000-0000-0000-000000000002"),ADMIN_KEYCLOAK=UUID.fromString("30000000-0000-0000-0000-000000000001");
 @Autowired MockMvc mvc;@Autowired JdbcTemplate jdbc;
 @Test void authorizedDoctorWithValidConsent(){UUID patient=graph(true,true,"ACTIVE",Instant.now().plusSeconds(3600));mvc.perform(access(patient,"doctor")).andExpect(status().isOk()).andExpect(jsonPath("$.allowed").value(true)).andExpect(jsonPath("$.decision").value("CARE_CONTEXT_AUTHORIZED"));assertAudit(patient,"READ");}
 @Test void doctorWithoutAssignmentIsDenied(){UUID patient=graph(true,true,"ACTIVE",null);mvc.perform(access(patient,"unassigned")).andExpect(status().isForbidden());assertAudit(patient,"DENIED");}
 @Test void doctorFromAnotherOrganizationIsDenied(){UUID patient=graph(true,true,"ACTIVE",null);jdbc.update("insert into professional.professional_assignment(id,professional_id,organization_id,start_date,status) values (?,?,?,?,?)",UUID.randomUUID(),DOCTOR_PROFESSIONAL,OTHER_ORGANIZATION,LocalDate.now(),"ACTIVE");mvc.perform(access(patient,"other")).andExpect(status().isForbidden());assertAudit(patient,"DENIED");}
 @Test void missingCareRelationshipIsDenied(){UUID patient=graph(false,true,"ACTIVE",null);mvc.perform(access(patient,"doctor")).andExpect(status().isForbidden());}
 @Test void expiredConsentIsDenied(){UUID patient=graph(true,true,"ACTIVE",Instant.now().minusSeconds(1));mvc.perform(access(patient,"doctor")).andExpect(status().isForbidden());}
 @Test void revokedConsentIsDenied(){UUID patient=graph(true,true,"REVOKED",Instant.now().plusSeconds(3600));mvc.perform(access(patient,"doctor")).andExpect(status().isForbidden());}
 @Test void platformAdminBypassesCareContext(){UUID patient=graph(false,false,"ACTIVE",null);mvc.perform(access(patient,"admin")).andExpect(status().isOk()).andExpect(jsonPath("$.decision").value("PLATFORM_ADMIN"));}
 private org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder access(UUID patient,String token){return get("/api/v1/patients/{p}/access",patient).param("scope","MEDICAL_RECORD").header(HttpHeaders.AUTHORIZATION,"Bearer "+token);}
 private UUID graph(boolean relationship,boolean consent,String consentStatus,Instant expires){person(DOCTOR_PERSON,DOCTOR_KEYCLOAK);person(UNASSIGNED_PERSON,UNASSIGNED_KEYCLOAK);professional(DOCTOR_PROFESSIONAL,DOCTOR_PERSON);professional(UNASSIGNED_PROFESSIONAL,UNASSIGNED_PERSON);organization(ORGANIZATION);organization(OTHER_ORGANIZATION);UUID patientPerson=UUID.randomUUID();person(patientPerson,null);UUID patient=UUID.randomUUID();jdbc.update("insert into patient.patient(id,person_id,patient_number) values (?,?,?)",patient,patientPerson,"PAT-"+patient);jdbc.update("insert into professional.professional_assignment(id,professional_id,organization_id,start_date,status) values (?,?,?,?,?)",UUID.randomUUID(),DOCTOR_PROFESSIONAL,ORGANIZATION,LocalDate.now(),"ACTIVE");jdbc.update("insert into patient.patient_registration(id,patient_id,organization_id,registration_number,status) values (?,?,?,?,?)",UUID.randomUUID(),patient,ORGANIZATION,"REG-"+patient,"ACTIVE");if(relationship)jdbc.update("insert into patient.care_relationship(id,patient_id,professional_id,organization_id,relationship_type,status) values (?,?,?,?,?,?)",UUID.randomUUID(),patient,DOCTOR_PROFESSIONAL,ORGANIZATION,"ATTENDING","ACTIVE");if(consent)jdbc.update("insert into patient.consent(id,patient_id,grantee_person_id,scope,status,granted_at,expires_at) values (?,?,?,?,?,?,?)",UUID.randomUUID(),patient,DOCTOR_PERSON,"MEDICAL_RECORD",consentStatus,Instant.now().minusSeconds(7200),expires);return patient;}
 private void person(UUID id,UUID keycloak){jdbc.update("insert into identity.person(id,person_number,keycloak_user_id,first_name,last_name,status) values (?,?,?,?,?,?)",id,"PER-"+id,keycloak,"Test","User","ACTIVE");}private void professional(UUID id,UUID person){jdbc.update("insert into professional.professional(id,person_id,professional_number,professional_type,status) values (?,?,?,?,?)",id,person,"PRO-"+id,"DOCTOR","ACTIVE");}private void organization(UUID id){jdbc.update("insert into organization.organization(id,organization_number,name) values (?,?,?)",id,"ORG-"+id,"Hospital");}private void assertAudit(UUID patient,String action){Integer count=jdbc.queryForObject("select count(*) from audit.data_access_log where patient_id=? and action=?",Integer.class,patient,action);org.assertj.core.api.Assertions.assertThat(count).isPositive();}
 @TestConfiguration(proxyBeanMethods=false) static class JwtFixtures {@Bean JwtDecoder jwtDecoder(){return token->{Instant now=Instant.now();UUID subject;UUID organization=null;List<String> roles;switch(token){case"doctor"->{subject=DOCTOR_KEYCLOAK;organization=ORGANIZATION;roles=List.of("DOCTOR");}case"other"->{subject=DOCTOR_KEYCLOAK;organization=OTHER_ORGANIZATION;roles=List.of("DOCTOR");}case"unassigned"->{subject=UNASSIGNED_KEYCLOAK;organization=ORGANIZATION;roles=List.of("DOCTOR");}default->{subject=ADMIN_KEYCLOAK;roles=List.of("PLATFORM_ADMIN");}}var builder=Jwt.withTokenValue(token).header("alg","RS256").subject(subject.toString()).issuer("https://keycloak.example/realms/healthys").audience(List.of("healthys-backend-apps")).issuedAt(now).expiresAt(now.plusSeconds(300)).claim("realm_access",Map.of("roles",roles)).claim("resource_access",Map.of());if(organization!=null)builder.claim("organization_id",organization.toString());return builder.build();};}}
}
