package org.novasos.healthysv2.patient;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.time.Instant; import java.util.*;
import org.junit.jupiter.api.Test; import org.novasos.healthysv2.TestcontainersConfiguration;
import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.*; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.context.annotation.*; import org.springframework.http.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.oauth2.jwt.*; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc; import org.springframework.transaction.annotation.Transactional;

@ActiveProfiles("test") @SpringBootTest(properties={"spring.security.oauth2.resourceserver.jwt.issuer-uri=https://keycloak.example/realms/healthys","spring.security.oauth2.resourceserver.jwt.audiences=healthys-backend-apps","healthys.security.api-client-id=healthys-backend-apps","healthys.security.cors.allowed-origins=http://localhost:5173"}) @AutoConfigureMockMvc @Import({TestcontainersConfiguration.class,PatientApiIntegrationTests.JwtFixtures.class}) @Transactional
class PatientApiIntegrationTests {
 @Autowired MockMvc mvc; @Autowired JdbcTemplate jdbc;
 @Test void managesAdministrativeAndClinicalPatientRecord() throws Exception {UUID person=person();UUID org=organization();UUID company=company();String body=mvc.perform(post("/api/v1/patients").header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"personId\":\"%s\",\"bloodGroup\":\"O+\",\"rhesus\":\"POSITIVE\"}".formatted(person))).andExpect(status().isCreated()).andExpect(jsonPath("$.patientNumber").exists()).andReturn().getResponse().getContentAsString();UUID p=id(body);
  mvc.perform(post("/api/v1/patients/{p}/identifiers",p).header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"type\":\"NATIONAL_ID\",\"value\":\"ID-API\"}")).andExpect(status().isCreated());
  mvc.perform(post("/api/v1/patients/{p}/insurances",p).header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"insuranceCompanyId\":\"%s\",\"policyNumber\":\"POL-API\",\"primary\":true}".formatted(company))).andExpect(status().isCreated());
  mvc.perform(post("/api/v1/patients/{p}/registrations",p).header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"organizationId\":\"%s\",\"registrationNumber\":\"REG-API\"}".formatted(org))).andExpect(status().isCreated());
  mvc.perform(post("/api/v1/patients/{p}/allergies",p).header(HttpHeaders.AUTHORIZATION,"Bearer clinician").contentType(MediaType.APPLICATION_JSON).content("{\"allergen\":\"Penicillin\",\"severity\":\"HIGH\"}")).andExpect(status().isCreated());
  mvc.perform(post("/api/v1/patients/{p}/chronic-diseases",p).header(HttpHeaders.AUTHORIZATION,"Bearer clinician").contentType(MediaType.APPLICATION_JSON).content("{\"status\":\"ACTIVE\",\"notes\":\"Monitored\"}")).andExpect(status().isCreated());
  mvc.perform(post("/api/v1/patients/{p}/medical-histories",p).header(HttpHeaders.AUTHORIZATION,"Bearer clinician").contentType(MediaType.APPLICATION_JSON).content("{\"condition\":\"Asthma\",\"diagnosedAt\":\"2020-01-01\"}")).andExpect(status().isCreated());
  mvc.perform(post("/api/v1/patients/{p}/notes",p).header(HttpHeaders.AUTHORIZATION,"Bearer clinician").contentType(MediaType.APPLICATION_JSON).content("{\"content\":\"Follow up\"}")).andExpect(status().isCreated());
  mvc.perform(post("/api/v1/patients/{p}/flags",p).header(HttpHeaders.AUTHORIZATION,"Bearer clinician").contentType(MediaType.APPLICATION_JSON).content("{\"flagType\":\"RISK\",\"label\":\"Fall risk\",\"active\":true}")).andExpect(status().isCreated());
  mvc.perform(put("/api/v1/patients/{p}/emergency-profile",p).header(HttpHeaders.AUTHORIZATION,"Bearer clinician").contentType(MediaType.APPLICATION_JSON).content("{\"emergencyCode\":\"ICE-API\",\"bloodGroupVisible\":true,\"allergiesVisible\":true,\"conditionsVisible\":true,\"medicationsVisible\":false,\"emergencyContactVisible\":true,\"active\":true}")).andExpect(status().isOk());
  mvc.perform(get("/api/v1/patients/{p}",p).header(HttpHeaders.AUTHORIZATION,"Bearer agent")).andExpect(status().isOk()).andExpect(jsonPath("$.identifiers.length()").value(1)).andExpect(jsonPath("$.insurances.length()").value(1)).andExpect(jsonPath("$.registrations.length()").value(1)).andExpect(jsonPath("$.allergies.length()").value(1)).andExpect(jsonPath("$.chronicDiseases.length()").value(1)).andExpect(jsonPath("$.medicalHistories.length()").value(1)).andExpect(jsonPath("$.notes.length()").value(1)).andExpect(jsonPath("$.flags.length()").value(1)).andExpect(jsonPath("$.emergencyProfile.emergencyCode").value("ICE-API"));
  mvc.perform(get("/api/v1/patients").param("query","O+").header(HttpHeaders.AUTHORIZATION,"Bearer agent")).andExpect(status().isOk()).andExpect(jsonPath("$.content.length()").value(1)); }
 @Test void agentCannotCreatePatientOrWriteClinicalData() throws Exception {UUID person=person();mvc.perform(post("/api/v1/patients").header(HttpHeaders.AUTHORIZATION,"Bearer agent").contentType(MediaType.APPLICATION_JSON).content("{\"personId\":\"%s\"}".formatted(person))).andExpect(status().isForbidden());}
 @Test void validatesHistoryDates() throws Exception {UUID p=createPatient();mvc.perform(post("/api/v1/patients/{p}/medical-histories",p).header(HttpHeaders.AUTHORIZATION,"Bearer clinician").contentType(MediaType.APPLICATION_JSON).header(HttpHeaders.ACCEPT_LANGUAGE,"fr").content("{\"condition\":\"Asthme\",\"diagnosedAt\":\"2025-02-02\",\"resolvedAt\":\"2025-01-01\"}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.violations").isNotEmpty());}
 private UUID createPatient() throws Exception {UUID person=person();return id(mvc.perform(post("/api/v1/patients").header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"personId\":\"%s\"}".formatted(person))).andReturn().getResponse().getContentAsString());}
 private UUID person(){UUID id=UUID.randomUUID();jdbc.update("insert into identity.person(id,person_number,first_name,last_name,status) values (?,?,?,?,?)",id,"PER-"+id,"Ada","Lovelace","ACTIVE");return id;}private UUID organization(){UUID id=UUID.randomUUID();jdbc.update("insert into organization.organization(id,organization_number,name) values (?,?,?)",id,"ORG-"+id,"Hospital");return id;}private UUID company(){UUID id=UUID.randomUUID();jdbc.update("insert into catalog.insurance_company(id,code,name) values (?,?,?)",id,"INS-"+id,"Mutual");return id;}private UUID id(String body){var m=java.util.regex.Pattern.compile("\\\"id\\\":\\\"([^\\\"]+)\\\"").matcher(body);if(!m.find())throw new IllegalArgumentException(body);return UUID.fromString(m.group(1));}
 @TestConfiguration(proxyBeanMethods=false) static class JwtFixtures {@Bean JwtDecoder jwtDecoder(){return token->jwt(token,switch(token){case"admin"->List.of("PLATFORM_ADMIN");case"clinician"->List.of("DOCTOR");default->List.of("HOSPITAL_AGENT");});}private Jwt jwt(String token,List<String> roles){Instant now=Instant.now();return Jwt.withTokenValue(token).header("alg","RS256").subject(UUID.randomUUID().toString()).issuer("https://keycloak.example/realms/healthys").audience(List.of("healthys-backend-apps")).issuedAt(now).expiresAt(now.plusSeconds(300)).claim("realm_access",Map.of("roles",roles)).claim("resource_access",Map.of()).build();}}
}
