package org.novasos.healthysv2.patient;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.time.Instant; import java.util.*; import org.junit.jupiter.api.Test; import org.novasos.healthysv2.TestcontainersConfiguration; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.*; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.context.annotation.*; import org.springframework.http.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.oauth2.jwt.*; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc; import org.springframework.transaction.annotation.Transactional;

@ActiveProfiles("test") @SpringBootTest(properties={"spring.security.oauth2.resourceserver.jwt.issuer-uri=https://keycloak.example/realms/healthys","spring.security.oauth2.resourceserver.jwt.audiences=healthys-backend-apps","healthys.security.api-client-id=healthys-backend-apps","healthys.security.cors.allowed-origins=http://localhost:5173"}) @AutoConfigureMockMvc @Import({TestcontainersConfiguration.class,PatientAuthorizationApiIntegrationTests.JwtFixtures.class}) @Transactional
class PatientAuthorizationApiIntegrationTests {
 static final UUID ADMIN_SUBJECT=UUID.fromString("00000000-0000-0000-0000-000000000001");@Autowired MockMvc mvc;@Autowired JdbcTemplate jdbc;
 @Test void adminManagesRelationshipAndConsentLifecycle() throws Exception {Graph g=graph();String relationship=mvc.perform(post("/api/v1/patients/{p}/care-relationships",g.patient).header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"professionalId\":\"%s\",\"organizationId\":\"%s\",\"relationshipType\":\"ATTENDING\"}".formatted(g.professional,g.organization))).andExpect(status().isCreated()).andExpect(jsonPath("$.status").value("ACTIVE")).andReturn().getResponse().getContentAsString();UUID relationshipId=id(relationship);String consent=mvc.perform(post("/api/v1/patients/{p}/consents",g.patient).header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"granteePersonId\":\"%s\",\"scope\":\"MEDICAL_RECORD\",\"purpose\":\"Care\"}".formatted(g.doctorPerson))).andExpect(status().isCreated()).andExpect(jsonPath("$.scope").value("MEDICAL_RECORD")).andExpect(jsonPath("$.createdAt").exists()).andReturn().getResponse().getContentAsString();UUID consentId=id(consent);mvc.perform(post("/api/v1/patients/{p}/consents/{id}/revoke",g.patient,consentId).header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"reason\":\"Patient request\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("REVOKED"));mvc.perform(post("/api/v1/patients/{p}/care-relationships/{id}/end",g.patient,relationshipId).header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{}")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("ENDED"));assertThatAudit("Consent",consentId,"REVOKE");}
 @Test void validatesConsentXorInFrench() throws Exception {Graph g=graph();mvc.perform(post("/api/v1/patients/{p}/consents",g.patient).header(HttpHeaders.AUTHORIZATION,"Bearer admin").header(HttpHeaders.ACCEPT_LANGUAGE,"fr").contentType(MediaType.APPLICATION_JSON).content("{\"scope\":\"MEDICAL_RECORD\"}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.violations").isNotEmpty());}
 private void assertThatAudit(String type,UUID id,String action){Integer count=jdbc.queryForObject("select count(*) from audit.audit_log where entity_type=? and entity_id=? and action=?",Integer.class,type,id,action);org.assertj.core.api.Assertions.assertThat(count).isOne();}
 private Graph graph(){UUID doctorPerson=person(null),patientPerson=person(null),organization=organization(),professional=professional(doctorPerson),patient=patient(patientPerson);jdbc.update("insert into professional.professional_assignment(id,professional_id,organization_id,start_date,status) values (?,?,?,?,?)",UUID.randomUUID(),professional,organization,java.time.LocalDate.now(),"ACTIVE");jdbc.update("insert into patient.patient_registration(id,patient_id,organization_id,registration_number,status) values (?,?,?,?,?)",UUID.randomUUID(),patient,organization,"REG-"+UUID.randomUUID(),"ACTIVE");return new Graph(patient,professional,doctorPerson,organization);}
 private UUID person(UUID keycloak){UUID id=UUID.randomUUID();jdbc.update("insert into identity.person(id,person_number,keycloak_user_id,first_name,last_name,status) values (?,?,?,?,?,?)",id,"PER-"+id,keycloak,"Test","User","ACTIVE");return id;}private UUID patient(UUID person){UUID id=UUID.randomUUID();jdbc.update("insert into patient.patient(id,person_id,patient_number) values (?,?,?)",id,person,"PAT-"+id);return id;}private UUID professional(UUID person){UUID id=UUID.randomUUID();jdbc.update("insert into professional.professional(id,person_id,professional_number,professional_type) values (?,?,?,?)",id,person,"PRO-"+id,"DOCTOR");return id;}private UUID organization(){UUID id=UUID.randomUUID();jdbc.update("insert into organization.organization(id,organization_number,name) values (?,?,?)",id,"ORG-"+id,"Hospital");return id;}private UUID id(String body){var m=java.util.regex.Pattern.compile("\\\"id\\\":\\\"([^\\\"]+)\\\"").matcher(body);if(!m.find())throw new IllegalArgumentException(body);return UUID.fromString(m.group(1));}record Graph(UUID patient,UUID professional,UUID doctorPerson,UUID organization){}
 @TestConfiguration(proxyBeanMethods=false) static class JwtFixtures {@Bean JwtDecoder jwtDecoder(){return token->{Instant now=Instant.now();return Jwt.withTokenValue(token).header("alg","RS256").subject(ADMIN_SUBJECT.toString()).issuer("https://keycloak.example/realms/healthys").audience(List.of("healthys-backend-apps")).issuedAt(now).expiresAt(now.plusSeconds(300)).claim("realm_access",Map.of("roles",List.of("PLATFORM_ADMIN"))).claim("resource_access",Map.of()).build();};}}
}
