package org.novasos.healthysv2.appointment;

import java.time.Instant; import java.util.*; import jakarta.persistence.*;

@Entity @Table(name="appointment",schema="appointment")
class Appointment {
 @Id private UUID id;@Column(name="appointment_number",nullable=false,unique=true,length=50)private String number;@Column(name="patient_id",nullable=false)private UUID patientId;@Column(name="professional_id")private UUID professionalId;@Column(name="organization_id",nullable=false)private UUID organizationId;@Column(name="department_id")private UUID departmentId;@Column(nullable=false,length=50)private String type;@Column(name="scheduled_start",nullable=false)private Instant start;@Column(name="scheduled_end",nullable=false)private Instant end;@Column(columnDefinition="text")private String reason;@Column(nullable=false,length=30)private String status;@Column(name="created_by")private UUID createdBy;@Column(name="created_at",nullable=false,updatable=false)private Instant createdAt;@Column(name="updated_at",nullable=false)private Instant updatedAt;@Version private long version;
 @OneToMany(mappedBy="appointment",cascade=CascadeType.ALL,orphanRemoval=true)private List<AppointmentParticipant> participants=new ArrayList<>();@OneToMany(mappedBy="appointment",cascade=CascadeType.ALL,orphanRemoval=true)private List<AppointmentStatusHistory> history=new ArrayList<>();@OneToMany(mappedBy="appointment",cascade=CascadeType.ALL,orphanRemoval=true)private List<WaitingQueueEntry> queue=new ArrayList<>();
 protected Appointment(){}static Appointment create(UUID patient,UUID professional,UUID organization,UUID department,String type,Instant start,Instant end,String reason,UUID actor){var x=new Appointment();x.id=UUID.randomUUID();x.number="APT-"+x.id.toString().replace("-","").substring(0,20).toUpperCase();x.patientId=Objects.requireNonNull(patient);x.professionalId=Objects.requireNonNull(professional);x.organizationId=Objects.requireNonNull(organization);x.createdBy=actor;x.createdAt=Instant.now();x.status="SCHEDULED";x.update(department,type,start,end,reason);x.history.add(AppointmentStatusHistory.create(x,null,"SCHEDULED",actor,"Appointment created"));return x;}
 void update(UUID department,String type,Instant start,Instant end,String reason){validateTimes(start,end);departmentId=department;this.type=required(type).toUpperCase();this.start=start;this.end=end;this.reason=optional(reason);updatedAt=Instant.now();}
 void cancel(UUID actor,String reason){if(Set.of("CANCELLED","COMPLETED","NO_SHOW").contains(status))throw new IllegalStateException("Appointment cannot be cancelled");changeStatus("CANCELLED",actor,reason);}
 void reschedule(Instant start,Instant end,UUID actor,String reason){if(Set.of("CANCELLED","COMPLETED","NO_SHOW").contains(status))throw new IllegalStateException("Appointment cannot be rescheduled");validateTimes(start,end);this.start=start;this.end=end;changeStatus("RESCHEDULED",actor,reason);}
 void changeStatus(String next,UUID actor,String reason){String previous=status;status=required(next).toUpperCase();updatedAt=Instant.now();history.add(AppointmentStatusHistory.create(this,previous,status,actor,reason));}
 AppointmentParticipant addParticipant(UUID person,String role){if(participants.stream().anyMatch(p->p.getPersonId().equals(person)))throw new IllegalArgumentException("Participant already exists");var p=AppointmentParticipant.create(this,person,role);participants.add(p);return p;}
 WaitingQueueEntry checkIn(String number,UUID actor){if(queue.stream().anyMatch(WaitingQueueEntry::isOpen))throw new IllegalStateException("Appointment is already queued");var q=WaitingQueueEntry.create(this,organizationId,number);queue.add(q);changeStatus("CHECKED_IN",actor,"Patient checked in");return q;}
 private void validateTimes(Instant s,Instant e){if(s==null||e==null||!e.isAfter(s))throw new IllegalArgumentException("Invalid appointment times");}private static String required(String v){if(v==null||v.isBlank())throw new IllegalArgumentException("Required value");return v.trim();}private static String optional(String v){return v==null||v.isBlank()?null:v.trim();}
 UUID getId(){return id;}String getNumber(){return number;}UUID getPatientId(){return patientId;}UUID getProfessionalId(){return professionalId;}UUID getOrganizationId(){return organizationId;}UUID getDepartmentId(){return departmentId;}String getType(){return type;}Instant getStart(){return start;}Instant getEnd(){return end;}String getReason(){return reason;}String getStatus(){return status;}UUID getCreatedBy(){return createdBy;}Instant getCreatedAt(){return createdAt;}Instant getUpdatedAt(){return updatedAt;}long getVersion(){return version;}List<AppointmentParticipant> getParticipants(){return participants;}List<AppointmentStatusHistory> getHistory(){return history;}List<WaitingQueueEntry> getQueue(){return queue;}
}
