import {apiRequest} from './client';
export type PrenatalVisit={id:string;consultationId?:string;professionalId?:string;visitDate:string;gestationalAgeWeeks?:number;weight?:number;systolicPressure?:number;diastolicPressure?:number;fetalHeartRate?:number;notes?:string};
export type PregnancyRisk={id:string;riskType:string;severity:string;identifiedAt:string;notes?:string;status:string};
export type Newborn={id:string;childPatientId:string;birthOrder:number;birthWeight?:number;birthHeight?:number;headCircumference?:number;apgar1?:number;apgar5?:number;status:string};
export type Delivery={id:string;organizationId?:string;deliveryDate:string;deliveryType:string;professionalId?:string;complications?:string;notes?:string;newborns:Newborn[]};
export type PregnancySummary={id:string;pregnancyNumber:string;motherPatientId:string;expectedDeliveryDate:string;status:string;createdAt:string};
export type Pregnancy=PregnancySummary&{estimatedConceptionDate?:string;lastMenstrualPeriod?:string;prenatalVisits:PrenatalVisit[];risks:PregnancyRisk[];delivery?:Delivery;postpartumVisits:{id:string;professionalId?:string;visitDate:string;notes?:string;status:string}[]};
export type Vaccination={id:string;vaccineCatalogId:string;vaccineCode:string;vaccineName:string;doseNumber?:number;administeredAt?:string;administeredBy?:string;organizationId?:string;batchNumber?:string;nextDueDate?:string;status:string};
export type GrowthMeasurement={id:string;measuredAt:string;weight?:number;height?:number;headCircumference?:number;bmi?:number;measuredBy?:string};
export type ChildHealthRecord={id:string;childPatientId:string;motherPatientId?:string;createdAt:string;status:string;vaccinations:Vaccination[];growthMeasurements:GrowthMeasurement[]};
export const maternalKeys={pregnancies:(mother:string)=>['maternal-child','pregnancies',mother]as const,pregnancy:(id:string)=>['maternal-child','pregnancy',id]as const,child:(id:string)=>['maternal-child','child',id]as const};
export const listPregnancies=(mother:string)=>apiRequest<PregnancySummary[]>(`/pregnancies?${new URLSearchParams({motherPatientId:mother})}`);export const getPregnancy=(id:string)=>apiRequest<Pregnancy>(`/pregnancies/${id}`);export const startPregnancy=(input:Record<string,unknown>)=>apiRequest<Pregnancy>('/pregnancies',{method:'POST',body:JSON.stringify(input)});const pregnancyPost=<T>(id:string,path:string,input?:unknown)=>apiRequest<T>(`/pregnancies/${id}/${path}`,{method:'POST',...(input===undefined?{}:{body:JSON.stringify(input)})});export const addPrenatalVisit=(id:string,input:Record<string,unknown>)=>pregnancyPost<PrenatalVisit>(id,'prenatal-visits',input);export const addPregnancyRisk=(id:string,input:Record<string,unknown>)=>pregnancyPost<PregnancyRisk>(id,'risks',input);export const resolvePregnancyRisk=(id:string,risk:string)=>pregnancyPost<PregnancyRisk>(id,`risks/${risk}/resolve`);export const registerDelivery=(id:string,input:Record<string,unknown>)=>pregnancyPost<Delivery>(id,'delivery',input);export const addPostpartumVisit=(id:string,input:Record<string,unknown>)=>pregnancyPost<Pregnancy['postpartumVisits'][number]>(id,'postpartum-visits',input);
export const getChildHealthRecord=(child:string)=>apiRequest<ChildHealthRecord>(`/child-health-records/${child}`);export const addVaccination=(child:string,input:Record<string,unknown>)=>apiRequest<Vaccination>(`/child-health-records/${child}/vaccinations`,{method:'POST',body:JSON.stringify(input)});export const addGrowthMeasurement=(child:string,input:Record<string,unknown>)=>apiRequest<GrowthMeasurement>(`/child-health-records/${child}/growth-measurements`,{method:'POST',body:JSON.stringify(input)});export const hasGrowthValue=(input:Record<string,unknown>)=>['weight','height','headCircumference'].some(key=>input[key]!==''&&input[key]!=null);

// Patient projections deliberately omit private clinical narrative and mutation endpoints.
export type PatientChildSummary={id:string;childPatientId:string;firstName:string;lastName:string;dateOfBirth?:string;sex?:string;status:string;createdAt:string};
export type PatientPregnancyDetail={pregnancy:PregnancySummary;estimatedConceptionDate?:string;lastMenstrualPeriod?:string;prenatalVisits:{id:string;visitDate:string;gestationalAgeWeeks?:number;weightKg?:number;systolicPressure?:number;diastolicPressure?:number;fetalHeartRate?:number}[];delivery?:{id:string;deliveryDate:string;deliveryType:string;newborns:{id:string;childPatientId:string;birthOrder:number;birthWeightKg?:number;birthHeightCm?:number;headCircumferenceCm?:number;apgar1?:number;apgar5?:number;status:string}[]}};
export type PatientChildDetail={child:PatientChildSummary;birth?:{deliveryDate:string;deliveryType:string};vaccinations:{id:string;vaccineCatalogId:string;vaccineCode:string;vaccineName:string;doseNumber?:number;administeredAt?:string;nextDueDate?:string;status:string}[];growthMeasurements:{id:string;measuredAt:string;weightKg?:number;heightCm?:number;headCircumferenceCm?:number;bmi?:number}[]};
const ownMaternal='/patients/me/maternal-child';
export const listMyPregnancies=(page=0)=>apiRequest<import('./organizations').Page<PregnancySummary>>(`${ownMaternal}/pregnancies?page=${page}&size=20`);
export const listMyChildren=(page=0)=>apiRequest<import('./organizations').Page<PatientChildSummary>>(`${ownMaternal}/children?page=${page}&size=20`);
export const getMyPregnancy=async(id:string):Promise<Pregnancy>=>{const p=await apiRequest<PatientPregnancyDetail>(`${ownMaternal}/pregnancies/${id}`);return {...p.pregnancy,estimatedConceptionDate:p.estimatedConceptionDate,lastMenstrualPeriod:p.lastMenstrualPeriod,prenatalVisits:p.prenatalVisits.map(v=>({...v,weight:v.weightKg})),risks:[],postpartumVisits:[],delivery:p.delivery?{...p.delivery,newborns:p.delivery.newborns.map(n=>({...n,birthWeight:n.birthWeightKg,birthHeight:n.birthHeightCm,headCircumference:n.headCircumferenceCm}))}:undefined};};
export const getMyChildHealthRecord=async(id:string):Promise<ChildHealthRecord>=>{const p=await apiRequest<PatientChildDetail>(`${ownMaternal}/children/${id}`);return {id:p.child.id,childPatientId:p.child.childPatientId,createdAt:p.child.createdAt,status:p.child.status,vaccinations:p.vaccinations,growthMeasurements:p.growthMeasurements.map(m=>({...m,weight:m.weightKg,height:m.heightCm,headCircumference:m.headCircumferenceCm}))};};
