import {apiRequest} from './client';import type {Page} from './organizations';import {validAccessToken} from '../auth/keycloak';
export type ConversationParticipant={personId:string;displayName:string;role?:string;joinedAt:string;status:string};
export type ConversationSummary={id:string;conversationNumber:string;type:string;subject?:string;patientId?:string;createdAt:string;status:string;lastMessage?:string;lastMessageAt?:string;unreadCount:number;participants:ConversationParticipant[]};
export type Conversation=Pick<ConversationSummary,'id'|'conversationNumber'|'type'|'subject'|'patientId'|'createdAt'|'status'|'participants'>&{createdBy:string};
export type ChatMessage={id:string;conversationId:string;senderPersonId:string;senderName:string;type:string;content?:string;replyToMessageId?:string;sentAt:string;editedAt?:string;deletedAt?:string;documentIds:string[];readByCurrentUser:boolean};
export const messagingKeys={conversations:['messaging','conversations'] as const,conversation:(id:string)=>['messaging','conversation',id] as const,messages:(id:string)=>['messaging','messages',id] as const};
export const listConversations=()=>apiRequest<Page<ConversationSummary>>('/conversations?size=100');
export const getConversation=(id:string)=>apiRequest<Conversation>(`/conversations/${id}`);
export const listMessages=(id:string)=>apiRequest<Page<ChatMessage>>(`/conversations/${id}/messages?size=100`);
export const createConversation=(input:{type:string;subject?:string;patientId?:string;participantPersonIds:string[]})=>apiRequest<Conversation>('/conversations',{method:'POST',body:JSON.stringify(input)});
export const sendMessage=(conversationId:string,input:{type:string;content?:string;replyToMessageId?:string;documentIds?:string[]})=>apiRequest<ChatMessage>(`/conversations/${conversationId}/messages`,{method:'POST',body:JSON.stringify(input)});
export const markMessageRead=(messageId:string)=>apiRequest(`/conversations/messages/${messageId}/read`,{method:'POST'});

export async function subscribeToConversation(conversationId:string,onMessage:(message:ChatMessage)=>void,onState:(connected:boolean)=>void){const api=new URL(import.meta.env.VITE_API_BASE_URL,window.location.origin);api.protocol=api.protocol==='https:'?'wss:':'ws:';api.pathname=api.pathname.replace(/\/api\/v1\/?$/,'/ws');api.search='';let socket:WebSocket|undefined;let stopped=false;let retry:number|undefined;const connect=async()=>{const token=await validAccessToken();if(stopped)return;let buffer='';socket=new WebSocket(api);socket.onopen=()=>socket?.send(`CONNECT\naccept-version:1.2\nheart-beat:10000,10000\nAuthorization:Bearer ${token}\n\n\0`);socket.onmessage=event=>{buffer+=String(event.data);const frames=buffer.split('\0');buffer=frames.pop()??'';for(const raw of frames){const frame=raw.replace(/^\n+/, '');if(frame.startsWith('CONNECTED')){onState(true);socket?.send(`SUBSCRIBE\nid:conversation-${conversationId}\ndestination:/topic/conversations/${conversationId}\nack:auto\n\n\0`);}else if(frame.startsWith('MESSAGE')){const separator=frame.indexOf('\n\n');if(separator>=0)onMessage(JSON.parse(frame.slice(separator+2)) as ChatMessage);}else if(frame.startsWith('ERROR'))onState(false);}};socket.onerror=()=>onState(false);socket.onclose=()=>{onState(false);if(!stopped)retry=window.setTimeout(()=>void connect(),3000)}};await connect();return()=>{stopped=true;if(retry)window.clearTimeout(retry);if(socket?.readyState===WebSocket.OPEN)socket.send('DISCONNECT\nreceipt:close\n\n\0');socket?.close();};}
