import {apiRequest} from './client';
import type {Page} from './organizations';

export type ProfessionalSummary={id:string;personId:string;professionalNumber:string;professionalType:string;status:string};
export type License={id:string;licenseNumber:string;issuingAuthority?:string;countryId?:string;issuedAt?:string;expiresAt?:string;status:string};
export type Speciality={specialityCatalogId:string;code:string;name:string;primary:boolean};
export type Schedule={id:string;dayOfWeek:number;startTime:string;endTime:string;slotDurationMinutes:number};
export type Availability={id:string;startAt:string;endAt:string;availabilityType:string;status:string};
export type Assignment={id:string;organizationId:string;departmentId?:string;serviceId?:string;position?:string;employeeNumber?:string;startDate:string;endDate?:string;status:string;schedules:Schedule[];availabilities:Availability[]};
export type Professional=ProfessionalSummary&{createdAt:string;updatedAt:string;licenses:License[];specialities:Speciality[];assignments:Assignment[]};
export type ProfessionalInput={personId:string;professionalNumber:string;professionalType:string;status?:string};
export type SpecialityCatalog={id:string;code:string;name:string};
export const professionalKeys={all:['professionals'] as const,list:(query:string)=>['professionals','list',query] as const,detail:(id:string)=>['professionals',id] as const,specialities:['professional-specialities'] as const};
export const listProfessionals=(query='')=>apiRequest<Page<ProfessionalSummary>>(`/professionals?size=100&sort=number,asc&query=${encodeURIComponent(query)}`);
export const getProfessional=(id:string)=>apiRequest<Professional>(`/professionals/${id}`);
export const createProfessional=(input:ProfessionalInput)=>apiRequest<Professional>('/professionals',{method:'POST',body:JSON.stringify(input)});
export const updateProfessional=(id:string,input:Pick<ProfessionalInput,'professionalType'|'status'>)=>apiRequest<Professional>(`/professionals/${id}`,{method:'PUT',body:JSON.stringify(input)});
export const listSpecialityCatalog=()=>apiRequest<SpecialityCatalog[]>('/professionals/specialities');
export const addLicense=(p:string,input:Omit<License,'id'>)=>apiRequest<License>(`/professionals/${p}/licenses`,{method:'POST',body:JSON.stringify(input)});
export const addSpeciality=(p:string,input:{specialityCatalogId:string;primary:boolean})=>apiRequest<Speciality>(`/professionals/${p}/specialities`,{method:'POST',body:JSON.stringify(input)});
export const addAssignment=(p:string,input:Omit<Assignment,'id'|'schedules'|'availabilities'>)=>apiRequest<Assignment>(`/professionals/${p}/assignments`,{method:'POST',body:JSON.stringify(input)});
export const addSchedule=(p:string,a:string,input:Omit<Schedule,'id'>)=>apiRequest<Schedule>(`/professionals/${p}/assignments/${a}/schedules`,{method:'POST',body:JSON.stringify(input)});
export const addAvailability=(p:string,a:string,input:Omit<Availability,'id'>)=>apiRequest<Availability>(`/professionals/${p}/assignments/${a}/availabilities`,{method:'POST',body:JSON.stringify(input)});
