package org.novasos.healthysv2.consultation;
import static org.novasos.healthysv2.consultation.api.ConsultationDtos.*;
import java.time.*;import java.util.*;import org.novasos.healthysv2.patient.PatientAccessService;import org.novasos.healthysv2.shared.api.error.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service @Transactional class ConsultationService{
 private final ConsultationRepository repository;private final JdbcTemplate jdbc;private final PatientAccessService access;
 ConsultationService(ConsultationRepository repository,JdbcTemplate jdbc,PatientAccessService access){this.repository=repository;this.jdbc=jdbc;this.access=access;}
 ConsultationResponse start(StartConsultationRequest r){access.requireAccess(r.patientId(),"MEDICAL_RECORD","WRITE");validateContext(r);var c=Consultation.start(r.patientId(),r.professionalId(),r.organizationId(),r.appointmentId(),r.encounterId(),r.type(),r.reason());repository.saveAndFlush(c);audit(c,"START");return response(c);}
 @Transactional(readOnly=true) ConsultationResponse find(UUID id){var c=get(id);access.requireAccess(c.getPatientId(),"MEDICAL_RECORD","READ");return response(c);}
 @Transactional(readOnly=true) PatientSummary patientSummary(UUID id){var c=get(id);access.requireAccess(c.getPatientId(),"MEDICAL_RECORD","READ");return jdbc.query("select p.id,p.patient_number,i.first_name,i.last_name,i.birth_date,i.gender,p.blood_group,p.rhesus,p.status from patient.patient p join identity.person i on i.id=p.person_id where p.id=?",rs->{if(!rs.next())throw notFound("Patient",c.getPatientId());return new PatientSummary((UUID)rs.getObject(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getObject(5,LocalDate.class),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),strings("select allergen from patient.allergy where patient_id=? and status='ACTIVE' order by allergen",c.getPatientId()),strings("select coalesce(dc.label,cd.notes,'Chronic disease') from patient.chronic_disease cd left join catalog.diagnosis_catalog dc on dc.id=cd.diagnosis_catalog_id where cd.patient_id=? and cd.status='ACTIVE' order by 1",c.getPatientId()),strings("select label from patient.patient_flag where patient_id=? and active=true order by label",c.getPatientId()));},c.getPatientId());}
 VitalSignResponse addVitalSign(UUID id,VitalSignRequest r){var c=write(id);UUID by=professional(r.measuredBy());var v=c.addVitalSign(r.temperature(),r.weight(),r.height(),r.systolicPressure(),r.diastolicPressure(),r.heartRate(),r.respiratoryRate(),r.oxygenSaturation(),r.measuredAt(),by);repository.flush();audit(c,"ADD_VITAL_SIGN");return vital(v);}
 DiagnosisResponse addDiagnosis(UUID id,DiagnosisRequest r){var c=write(id);if(r.diagnosisCatalogId()!=null)requireActiveCatalog(r.diagnosisCatalogId());var d=c.addDiagnosis(r.diagnosisCatalogId(),r.diagnosisType(),r.description(),r.status());repository.flush();audit(c,"ADD_DIAGNOSIS");return diagnosis(d);}
 NoteResponse addNote(UUID id,NoteRequest r){var c=write(id);requireProfessional(r.authorProfessionalId());var n=c.addNote(r.authorProfessionalId(),r.noteType(),r.content());repository.flush();audit(c,"ADD_NOTE");return note(n);}
 ObservationResponse addObservation(UUID id,ObservationRequest r){var c=write(id);UUID author=r.authorProfessionalId()==null?professional(null):professional(r.authorProfessionalId());var o=c.addObservation(author,r.type(),r.value(),r.notes(),r.observedAt());repository.flush();audit(c,"ADD_OBSERVATION");return observation(o);}
 TreatmentResponse addTreatment(UUID id,TreatmentRequest r){var c=write(id);var t=c.addTreatment(r.description(),r.startDate(),r.endDate(),r.status());repository.flush();audit(c,"ADD_TREATMENT");return treatment(t);}
 FollowUpResponse addFollowUp(UUID id,FollowUpRequest r){var c=write(id);if(r.recommendedDate()!=null&&r.recommendedDate().isBefore(LocalDate.now()))throw rule("INVALID_FOLLOW_UP_DATE","validation.consultation.follow-up-date");var f=c.addFollowUp(r.recommendedDate(),r.instructions(),r.status());repository.flush();audit(c,"ADD_FOLLOW_UP");return followUp(f);}
 ConsultationResponse complete(UUID id){var c=write(id);try{c.complete();repository.flush();}catch(IllegalStateException e){throw rule("CONSULTATION_ALREADY_COMPLETED","error.consultation.completed");}audit(c,"COMPLETE");return response(c);}
 @Transactional(readOnly=true) List<DiagnosisCatalogResponse> catalog(String query){String q=query==null?"":query.trim();return jdbc.query("select id,code,system,label from catalog.diagnosis_catalog where active=true and (?='' or lower(code) like lower(?) or lower(label) like lower(?)) order by code limit 100",(rs,n)->new DiagnosisCatalogResponse((UUID)rs.getObject(1),rs.getString(2),rs.getString(3),rs.getString(4)),q,"%"+q+"%","%"+q+"%");}
 private Consultation write(UUID id){var c=get(id);access.requireAccess(c.getPatientId(),"MEDICAL_RECORD","WRITE");if(!"IN_PROGRESS".equals(c.getStatus()))throw rule("CONSULTATION_ALREADY_COMPLETED","error.consultation.completed");return c;}private Consultation get(UUID id){return repository.findById(id).orElseThrow(()->notFound("Consultation",id));}
 private void validateContext(StartConsultationRequest r){require("patient.patient",r.patientId(),"Patient");require("professional.professional",r.professionalId(),"Professional");require("organization.organization",r.organizationId(),"Organization");if(!exists("select count(*) from professional.professional_assignment where professional_id=? and organization_id=? and status='ACTIVE' and start_date<=current_date and (end_date is null or end_date>=current_date)",r.professionalId(),r.organizationId()))throw rule("PROFESSIONAL_NOT_ASSIGNED","error.consultation.assignment");if(r.appointmentId()!=null){if(!exists("select count(*) from appointment.appointment where id=? and patient_id=? and professional_id=? and organization_id=?",r.appointmentId(),r.patientId(),r.professionalId(),r.organizationId()))throw rule("APPOINTMENT_CONTEXT_MISMATCH","error.consultation.appointment");if(repository.existsByAppointmentId(r.appointmentId()))throw new ConflictException("APPOINTMENT_CONSULTATION_EXISTS","error.consultation.appointment-exists");}if(r.encounterId()!=null&&!exists("select count(*) from registration.encounter where id=? and patient_id=? and organization_id=?",r.encounterId(),r.patientId(),r.organizationId()))throw rule("ENCOUNTER_CONTEXT_MISMATCH","error.consultation.encounter");}
 private void requireActiveCatalog(UUID id){if(!exists("select count(*) from catalog.diagnosis_catalog where id=? and active=true",id))throw notFound("DiagnosisCatalog",id);}private void requireProfessional(UUID id){require("professional.professional",id,"Professional");}private UUID professional(UUID requested){if(requested!=null){requireProfessional(requested);return requested;}UUID person=actor();UUID id=person==null?null:jdbc.query("select id from professional.professional where person_id=? and status='ACTIVE' limit 1",rs->rs.next()?(UUID)rs.getObject(1):null,person);if(id==null)throw rule("PROFESSIONAL_CONTEXT_REQUIRED","error.consultation.professional-context");return id;}
 private void require(String table,UUID id,String resource){if(!exists("select count(*) from "+table+" where id=?",id))throw notFound(resource,id);}private boolean exists(String sql,Object...args){return Objects.requireNonNull(jdbc.queryForObject(sql,Integer.class,args))>0;}private List<String> strings(String sql,UUID id){return jdbc.queryForList(sql,String.class,id);}private UUID actor(){var a=SecurityContextHolder.getContext().getAuthentication();if(!(a instanceof JwtAuthenticationToken jwt))return null;try{UUID sub=UUID.fromString(jwt.getToken().getSubject());return jdbc.query("select id from identity.person where keycloak_user_id=? or id=? limit 1",rs->rs.next()?(UUID)rs.getObject(1):null,sub,sub);}catch(IllegalArgumentException e){return null;}}
 private void audit(Consultation c,String action){jdbc.update("insert into audit.audit_log(actor_person_id,organization_id,module,entity_type,entity_id,action,new_value) values (?,?,?,?,?,?,?::jsonb)",actor(),c.getOrganizationId(),"CONSULTATION","Consultation",c.getId(),action,"{\"status\":\""+c.getStatus()+"\"}");}
 private ConsultationResponse response(Consultation c){return new ConsultationResponse(c.getId(),c.getNumber(),c.getPatientId(),c.getProfessionalId(),c.getOrganizationId(),c.getAppointmentId(),c.getEncounterId(),c.getType(),c.getReason(),c.getStartedAt(),c.getCompletedAt(),c.getStatus(),c.getCreatedAt(),c.getUpdatedAt(),c.getVersion(),c.getVitalSigns().stream().map(this::vital).toList(),c.getDiagnoses().stream().map(this::diagnosis).toList(),c.getNotes().stream().map(this::note).toList(),c.getObservations().stream().map(this::observation).toList(),c.getTreatments().stream().map(this::treatment).toList(),c.getFollowUps().stream().map(this::followUp).toList());}
 private VitalSignResponse vital(VitalSign v){return new VitalSignResponse(v.getId(),v.getTemperature(),v.getWeight(),v.getHeight(),v.getBmi(),v.getSystolic(),v.getDiastolic(),v.getHeartRate(),v.getRespiratoryRate(),v.getOxygen(),v.getMeasuredAt(),v.getMeasuredBy());}private DiagnosisResponse diagnosis(Diagnosis d){String[] catalog=d.getCatalogId()==null?null:jdbc.query("select code,label from catalog.diagnosis_catalog where id=?",rs->rs.next()?new String[]{rs.getString(1),rs.getString(2)}:null,d.getCatalogId());return new DiagnosisResponse(d.getId(),d.getCatalogId(),catalog==null?null:catalog[0],catalog==null?null:catalog[1],d.getType(),d.getDescription(),d.getStatus(),d.getDiagnosedAt());}private NoteResponse note(ConsultationNote n){return new NoteResponse(n.getId(),n.getAuthorId(),n.getType(),n.getContent(),n.getCreatedAt(),n.getUpdatedAt());}private ObservationResponse observation(ClinicalObservation o){return new ObservationResponse(o.getId(),o.getAuthorId(),o.getType(),o.getValue(),o.getNotes(),o.getObservedAt());}private TreatmentResponse treatment(TreatmentPlan t){return new TreatmentResponse(t.getId(),t.getDescription(),t.getStartDate(),t.getEndDate(),t.getStatus());}private FollowUpResponse followUp(FollowUp f){return new FollowUpResponse(f.getId(),f.getDate(),f.getInstructions(),f.getStatus());}
 private ResourceNotFoundException notFound(String r,Object id){return new ResourceNotFoundException(r,id);}private BusinessRuleException rule(String code,String key){return new BusinessRuleException(code,key);}
}
