package org.novasos.healthysv2.pharmacy;
import jakarta.persistence.*;import java.math.*;import java.time.*;import java.util.*;
@Entity @Table(name="prescription",schema="pharmacy") class Prescription{
 @Id private UUID id;@Column(name="prescription_number",nullable=false,unique=true,length=50)private String number;@Column(name="patient_id",nullable=false)private UUID patientId;@Column(name="consultation_id")private UUID consultationId;@Column(name="prescriber_id",nullable=false)private UUID prescriberId;@Column(name="organization_id")private UUID organizationId;@Column(name="prescribed_at",nullable=false)private Instant prescribedAt;@Column(name="expires_at")private Instant expiresAt;@Column(nullable=false,length=30)private String status;
 @OneToMany(mappedBy="prescription",cascade=CascadeType.ALL,orphanRemoval=true)private List<PrescriptionItem>items=new ArrayList<>();@OneToMany(mappedBy="prescription",cascade=CascadeType.ALL,orphanRemoval=true)private List<Dispense>dispenses=new ArrayList<>();
 protected Prescription(){}static Prescription create(UUID patient,UUID consultation,UUID prescriber,UUID organization,Instant expiresAt){var x=new Prescription();x.id=UUID.randomUUID();x.number="RX-"+x.id.toString().replace("-","").substring(0,20).toUpperCase();x.patientId=Objects.requireNonNull(patient);x.consultationId=consultation;x.prescriberId=Objects.requireNonNull(prescriber);x.organizationId=organization;x.prescribedAt=Instant.now();if(expiresAt!=null&&!expiresAt.isAfter(x.prescribedAt))throw new IllegalArgumentException("Invalid expiration");x.expiresAt=expiresAt;x.status="ACTIVE";return x;}
 PrescriptionItem addItem(UUID medication,String dosage,String frequency,String route,String duration,BigDecimal quantity,String instructions){ensureActive();if(items.stream().anyMatch(i->i.getMedicationId().equals(medication)))throw new IllegalArgumentException("Duplicate medication");var item=PrescriptionItem.create(this,medication,dosage,frequency,route,duration,quantity,instructions);items.add(item);return item;}
 Dispense dispense(UUID pharmacy,UUID pharmacist,List<DispenseLine>lines){ensureActive();if(expired())throw new IllegalStateException("Prescription expired");if(lines==null||lines.isEmpty())throw new IllegalArgumentException("Empty dispense");var seen=new HashSet<UUID>();var d=Dispense.create(this,pharmacy,pharmacist);for(var line:lines){if(!seen.add(line.itemId()))throw new IllegalArgumentException("Duplicate dispense item");var item=item(line.itemId());BigDecimal remaining=item.getQuantity().subtract(dispensed(item.getId()));if(line.quantity().signum()<=0||line.quantity().compareTo(remaining)>0)throw new IllegalArgumentException("Invalid dispense quantity");d.addItem(item,line.quantity(),line.batch());}dispenses.add(d);status=items.stream().allMatch(i->dispensed(i.getId()).compareTo(i.getQuantity())>=0)?"DISPENSED":"PARTIALLY_DISPENSED";return d;}
 void cancel(){if(Set.of("DISPENSED","CANCELLED").contains(status))throw new IllegalStateException("Prescription cannot be cancelled");status="CANCELLED";}boolean expired(){return expiresAt!=null&&!expiresAt.isAfter(Instant.now());}private void ensureActive(){if(Set.of("DISPENSED","CANCELLED").contains(status))throw new IllegalStateException("Prescription closed");}PrescriptionItem item(UUID id){return items.stream().filter(i->i.getId().equals(id)).findFirst().orElseThrow(NoSuchElementException::new);}BigDecimal dispensed(UUID item){return dispenses.stream().flatMap(d->d.getItems().stream()).filter(i->i.getPrescriptionItemId().equals(item)).map(DispenseItem::getQuantity).reduce(BigDecimal.ZERO,BigDecimal::add);}
 UUID getId(){return id;}String getNumber(){return number;}UUID getPatientId(){return patientId;}UUID getConsultationId(){return consultationId;}UUID getPrescriberId(){return prescriberId;}UUID getOrganizationId(){return organizationId;}Instant getPrescribedAt(){return prescribedAt;}Instant getExpiresAt(){return expiresAt;}String getStatus(){return status;}List<PrescriptionItem>getItems(){return items;}List<Dispense>getDispenses(){return dispenses;}record DispenseLine(UUID itemId,BigDecimal quantity,String batch){}
}
