import {useState,type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import {adminKeys,getAuditDashboard,listAuditLogs,listAuthenticationLogs,listDataAccessLogs,listSecurityEvents,resolveSecurityEvent,type AuditFilters} from '../api/admin';
import {ApiErrorMessage} from '../components/ApiErrorMessage';

export function AuditSecurityDashboardPage(){
 const{t,i18n}=useTranslation();const cache=useQueryClient();const[days,setDays]=useState(7);const[tab,setTab]=useState<'audit'|'access'|'authentication'|'security'>('audit');const[filters,setFilters]=useState<AuditFilters>({});const[applied,setApplied]=useState<AuditFilters>({});
 const dashboard=useQuery({queryKey:adminKeys.dashboard(days),queryFn:()=>getAuditDashboard(days)});const audit=useQuery({queryKey:adminKeys.audit(applied),queryFn:()=>listAuditLogs(applied),enabled:tab==='audit'});const access=useQuery({queryKey:adminKeys.access(applied),queryFn:()=>listDataAccessLogs(applied),enabled:tab==='access'});const auth=useQuery({queryKey:adminKeys.auth,queryFn:listAuthenticationLogs,enabled:tab==='authentication'});const security=useQuery({queryKey:adminKeys.security,queryFn:listSecurityEvents,enabled:tab==='security'});
 const resolve=useMutation({mutationFn:resolveSecurityEvent,onSuccess:()=>{void cache.invalidateQueries({queryKey:adminKeys.security});void cache.invalidateQueries({queryKey:['admin','audit-dashboard']})}});
 if(dashboard.isPending)return<p>{t('common.loading')}</p>;if(dashboard.isError)return<ApiErrorMessage error={dashboard.error}/>;const data=dashboard.data;const peak=Math.max(...data.daily.map(d=>d.changes+d.dataAccesses+d.authFailures),1);const search=(event:FormEvent)=>{event.preventDefault();setApplied(filters)};
 return<section><Link to="/admin">← {t('common.back')}</Link><div className="page-heading"><div><p className="eyebrow">{t('audit.eyebrow')}</p><h1>{t('audit.title')}</h1></div><label className="period-select">{t('audit.period')}<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>{t('audit.days',{count:7})}</option><option value={14}>{t('audit.days',{count:14})}</option><option value={30}>{t('audit.days',{count:30})}</option></select></label></div>
 <div className="audit-summary"><Metric label={t('audit.changes')} value={data.totalChanges}/><Metric label={t('audit.accesses')} value={data.totalDataAccesses}/><Metric label={t('audit.denied')} value={data.deniedAccesses} alert={data.deniedAccesses>0}/><Metric label={t('audit.authFailures')} value={data.authenticationFailures} alert={data.authenticationFailures>0}/><Metric label={t('audit.openSecurity')} value={data.unresolvedSecurityEvents} alert={data.unresolvedSecurityEvents>0}/></div>
 <section className="audit-chart" aria-label={t('audit.activityChart')}>{data.daily.map(day=>{const total=day.changes+day.dataAccesses+day.authFailures;return<div className="audit-day" key={day.date}><div className="audit-bar"><span className="audit-bar-changes" style={{height:`${day.changes/peak*100}%`}}/><span className="audit-bar-access" style={{height:`${day.dataAccesses/peak*100}%`}}/><span className="audit-bar-denied" style={{height:`${(day.deniedAccesses+day.authFailures)/peak*100}%`}}/></div><small>{new Date(`${day.date}T00:00:00`).toLocaleDateString(i18n.language,{weekday:'short'})}</small><b>{total}</b></div>})}</section>
 <div className="tabs">{(['audit','access','authentication','security'] as const).map(value=><button className={tab===value?'active':''} key={value} onClick={()=>setTab(value)}>{t(`audit.tabs.${value}`)}</button>)}</div>
 {(tab==='audit'||tab==='access')&&<form className="search-form audit-filters" onSubmit={search}><input placeholder={tab==='audit'?t('audit.module'):t('audit.resourceType')} value={(tab==='audit'?filters.module:filters.resourceType)||''} onChange={e=>setFilters({...filters,[tab==='audit'?'module':'resourceType']:e.target.value})}/><input placeholder={t('audit.action')} value={filters.action||''} onChange={e=>setFilters({...filters,action:e.target.value})}/><input placeholder={t('audit.actor')} value={filters.actorPersonId||''} onChange={e=>setFilters({...filters,actorPersonId:e.target.value})}/>{tab==='access'&&<input placeholder={t('audit.patient')} value={filters.patientId||''} onChange={e=>setFilters({...filters,patientId:e.target.value})}/>}<button>{t('common.search')}</button></form>}
 {tab==='audit'&&<LogTable error={audit.error} headers={[t('audit.date'),t('audit.module'),t('audit.action'),t('audit.entity'),t('audit.actor'),t('audit.correlation')]} rows={audit.data?.content.map(x=>[new Date(x.occurredAt).toLocaleString(i18n.language),x.module,x.action,`${x.entityType} · ${x.entityId||'—'}`,x.actorPersonId||'—',x.correlationId||'—'])}/>}
 {tab==='access'&&<LogTable error={access.error} headers={[t('audit.date'),t('audit.action'),t('audit.resourceType'),t('audit.patient'),t('audit.actor'),t('audit.reason')]} rows={access.data?.content.map(x=>[new Date(x.occurredAt).toLocaleString(i18n.language),x.action,x.resourceType,x.patientId||'—',x.actorPersonId||'—',x.accessReason||'—'])}/>}
 {tab==='authentication'&&<LogTable error={auth.error} headers={[t('audit.date'),t('audit.eventType'),t('audit.success'),t('audit.person'),t('audit.ip')]} rows={auth.data?.content.map(x=>[new Date(x.occurredAt).toLocaleString(i18n.language),x.eventType,x.success?t('common.yes','Yes'):t('common.no','No'),x.personId||'—',x.ipAddress||'—'])}/>}
 {tab==='security'&&<div className="security-events">{security.isError&&<ApiErrorMessage error={security.error}/>} {security.data?.map(event=><article className={`security-event severity-${event.severity.toLowerCase()}`} key={event.id}><div><strong>{event.eventType}</strong><span>{event.severity}</span></div><p>{event.description}</p><small>{new Date(event.occurredAt).toLocaleString(i18n.language)} · {event.ipAddress||'—'}</small>{!event.resolvedAt&&<button onClick={()=>resolve.mutate(event.id)} disabled={resolve.isPending}>{t('audit.resolve')}</button>}</article>)}</div>}
 </section>;
}
function Metric({label,value,alert=false}:{label:string;value:number;alert?:boolean}){return<article className={`audit-metric ${alert?'metric-alert':''}`}><span>{label}</span><strong>{value}</strong></article>}
function LogTable({headers,rows,error}:{headers:string[];rows?:string[][];error:unknown}){if(error)return<ApiErrorMessage error={error}/>;return<div className="table-scroll"><table className="audit-table"><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows?.map((row,index)=><tr key={index}>{row.map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></table></div>}
