import {useState,type FormEvent} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import {useAuth} from '../auth/AuthContext';
import {ClinicalReferenceSelect} from '../components/ClinicalReferenceSelect';
import {ResourceTable} from '../components/ResourceTable';
import {ApiErrorMessage} from '../components/ApiErrorMessage';
import {billingKeys,createInvoice,listInvoices,validInvoiceItem,type InvoiceFilters,type InvoiceItemInput} from '../api/billing';

const line=():InvoiceItemInput=>({itemType:'CONSULTATION',description:'',quantity:1,unitPrice:0,taxAmount:0});
export function BillingPage(){
 const{t,i18n}=useTranslation();const auth=useAuth();const navigate=useNavigate();const cache=useQueryClient();
 const[page,setPage]=useState(0);const[filters,setFilters]=useState<InvoiceFilters>({});const[applied,setApplied]=useState<InvoiceFilters>({});const[show,setShow]=useState(false);const[error,setError]=useState('');
 const[form,setForm]=useState({patientId:'',organizationId:'',encounterId:'',currency:'CAD',dueAt:'',items:[line()]});
 const invoices=useQuery({queryKey:[...billingKeys.invoices(applied),page],queryFn:()=>listInvoices(applied,page)});
 const create=useMutation({mutationFn:createInvoice,onSuccess:invoice=>{void cache.invalidateQueries({queryKey:['billing','invoices']});navigate(`/billing/invoices/${invoice.id}`)}});
 const canWrite=auth.hasAnyRole('PLATFORM_ADMIN','HOSPITAL_ADMIN','HOSPITAL_AGENT','CASHIER','ACCOUNTANT');
 const update=(index:number,key:keyof InvoiceItemInput,value:string|number)=>setForm({...form,items:form.items.map((item,i)=>i===index?{...item,[key]:value}:item)});
 const submit=(event:FormEvent)=>{event.preventDefault();if(!form.patientId||!form.organizationId||!form.items.every(validInvoiceItem)){setError(t('billing.validation'));return}setError('');create.mutate({...form,encounterId:form.encounterId||undefined,dueAt:form.dueAt?new Date(form.dueAt).toISOString():undefined,currency:form.currency.toUpperCase()})};
 const money=(amount:number,currency:string)=>new Intl.NumberFormat(i18n.language,{style:'currency',currency}).format(amount);
 return <section><div className="page-heading"><div><p className="eyebrow">{t('billing.eyebrow')}</p><h1>{t('billing.title')}</h1></div>{canWrite&&<button onClick={()=>setShow(!show)}>{t('billing.newInvoice')}</button>}</div>
 <form className="search-form" onSubmit={e=>{e.preventDefault();setApplied(filters);setPage(0)}}>{canWrite&&<ClinicalReferenceSelect kind="patient" label={t('billing.patientId')} value={filters.patientId||''} onChange={patientId=>setFilters({...filters,patientId})}/>}{canWrite&&<ClinicalReferenceSelect kind="organization" label={t('billing.organizationId')} value={filters.organizationId||''} onChange={organizationId=>setFilters({...filters,organizationId})}/>}<select aria-label={t('common.status')} value={filters.status||''} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">{t('billing.allStatuses')}</option>{['DRAFT','ISSUED','PARTIALLY_PAID','PAID','CANCELLED'].map(s=><option value={s} key={s}>{t(`status.${s}`,s)}</option>)}</select><button>{t('common.search')}</button></form>
 {show&&<form className="entity-form billing-form form-grid" onSubmit={submit}><h2>{t('billing.newInvoice')}</h2>{(['patientId','organizationId'] as const).map(key=><ClinicalReferenceSelect key={key} required kind={key==='patientId'?'patient':'organization'} label={t(`billing.${key}`)} value={form[key]} onChange={value=>setForm({...form,[key]:value})}/>)}<label>{t('billing.currency')}<select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}>{['CAD','USD','EUR','XAF','XOF'].map(currency=><option key={currency}>{currency}</option>)}</select></label><label>{t('billing.dueAt')}<input type="datetime-local" value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})}/></label>{form.items.map((item,index)=><fieldset className="invoice-item-form" key={index}><legend>{t('billing.item')} {index+1}</legend>{(['itemType','referenceId','description'] as const).map(key=><label key={key}>{t(`billing.${key}`)}<input required={key!=='referenceId'} value={item[key]||''} onChange={e=>update(index,key,e.target.value)}/></label>)}{(['quantity','unitPrice','taxAmount'] as const).map(key=><label key={key}>{t(`billing.${key}`)}<input type="number" min={key==='quantity'?'0.001':'0'} step="0.01" required value={item[key]} onChange={e=>update(index,key,Number(e.target.value))}/></label>)}{form.items.length>1&&<button type="button" className="danger" onClick={()=>setForm({...form,items:form.items.filter((_,i)=>i!==index)})}>{t('common.delete')}</button>}</fieldset>)}<button type="button" className="button-secondary" onClick={()=>setForm({...form,items:[...form.items,line()]})}>{t('billing.addItem')}</button><button type="button" className="button-secondary" onClick={()=>setShow(false)}>{t('common.cancel')}</button><button disabled={create.isPending}>{t('common.create')}</button>{error&&<p className="field-error">{error}</p>}{create.isError&&<ApiErrorMessage error={create.error}/>}</form>}
 {invoices.isPending&&<p>{t('common.loading')}</p>}{invoices.isError&&<ApiErrorMessage error={invoices.error}/>}{invoices.data&&<ResourceTable data={invoices.data} page={page} onPageChange={setPage} empty={t('billing.empty')} columns={[{label:t('billing.item'),render:invoice=><Link to={`/billing/invoices/${invoice.id}`}>{invoice.invoiceNumber}</Link>},{label:t('billing.patientId'),render:invoice=>invoice.patientId},{label:t('common.status'),render:invoice=><span className="status-badge">{t(`status.${invoice.status}`,invoice.status)}</span>},{label:t('billing.total'),render:invoice=>money(invoice.totalAmount,invoice.currency)},{label:t('billing.balance'),render:invoice=>money(invoice.balance,invoice.currency)}]} actions={invoice=><Link to={`/billing/invoices/${invoice.id}`}>{t('common.view')}</Link>}/>}</section>;
}
