import {useState,type FormEvent} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import {useAuth} from '../auth/AuthContext';
import {ApiErrorMessage} from '../components/ApiErrorMessage';
import {billingKeys,createInvoice,listInvoices,validInvoiceItem,type InvoiceFilters,type InvoiceItemInput} from '../api/billing';

const line=():InvoiceItemInput=>({itemType:'CONSULTATION',description:'',quantity:1,unitPrice:0,taxAmount:0});
export function BillingPage(){
 const{t,i18n}=useTranslation();const auth=useAuth();const navigate=useNavigate();const cache=useQueryClient();
 const[filters,setFilters]=useState<InvoiceFilters>({});const[applied,setApplied]=useState<InvoiceFilters>({});const[show,setShow]=useState(false);const[error,setError]=useState('');
 const[form,setForm]=useState({patientId:'',organizationId:'',encounterId:'',currency:'CAD',dueAt:'',items:[line()]});
 const invoices=useQuery({queryKey:billingKeys.invoices(applied),queryFn:()=>listInvoices(applied)});
 const create=useMutation({mutationFn:createInvoice,onSuccess:invoice=>{void cache.invalidateQueries({queryKey:['billing','invoices']});navigate(`/billing/invoices/${invoice.id}`)}});
 const canWrite=auth.hasAnyRole('PLATFORM_ADMIN','HOSPITAL_ADMIN','HOSPITAL_AGENT','CASHIER','ACCOUNTANT');
 const update=(index:number,key:keyof InvoiceItemInput,value:string|number)=>setForm({...form,items:form.items.map((item,i)=>i===index?{...item,[key]:value}:item)});
 const submit=(event:FormEvent)=>{event.preventDefault();if(!form.patientId||!form.organizationId||!form.items.every(validInvoiceItem)){setError(t('billing.validation'));return}setError('');create.mutate({...form,encounterId:form.encounterId||undefined,dueAt:form.dueAt?new Date(form.dueAt).toISOString():undefined,currency:form.currency.toUpperCase()})};
 const money=(amount:number,currency:string)=>new Intl.NumberFormat(i18n.language,{style:'currency',currency}).format(amount);
 return <section><div className="page-heading"><div><p className="eyebrow">{t('billing.eyebrow')}</p><h1>{t('billing.title')}</h1></div>{canWrite&&<button onClick={()=>setShow(!show)}>{t('billing.newInvoice')}</button>}</div>
 <form className="search-form" onSubmit={e=>{e.preventDefault();setApplied(filters)}}><input placeholder={t('billing.patientId')} value={filters.patientId||''} onChange={e=>setFilters({...filters,patientId:e.target.value})}/><input placeholder={t('billing.organizationId')} value={filters.organizationId||''} onChange={e=>setFilters({...filters,organizationId:e.target.value})}/><select value={filters.status||''} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">{t('billing.allStatuses')}</option>{['DRAFT','ISSUED','PARTIALLY_PAID','PAID','CANCELLED'].map(s=><option value={s} key={s}>{t(`status.${s}`,s)}</option>)}</select><button>{t('common.search')}</button></form>
 {show&&<form className="entity-form billing-form" onSubmit={submit}><h2>{t('billing.newInvoice')}</h2>{(['patientId','organizationId','encounterId'] as const).map(key=><label key={key}>{t(`billing.${key}`)}<input required={key!=='encounterId'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>{t('billing.currency')}<input required maxLength={3} value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}/></label><label>{t('billing.dueAt')}<input type="datetime-local" value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})}/></label>{form.items.map((item,index)=><fieldset className="invoice-item-form" key={index}><legend>{t('billing.item')} {index+1}</legend>{(['itemType','referenceId','description'] as const).map(key=><label key={key}>{t(`billing.${key}`)}<input required={key!=='referenceId'} value={item[key]||''} onChange={e=>update(index,key,e.target.value)}/></label>)}{(['quantity','unitPrice','taxAmount'] as const).map(key=><label key={key}>{t(`billing.${key}`)}<input type="number" min={key==='quantity'?'0.001':'0'} step="0.01" required value={item[key]} onChange={e=>update(index,key,Number(e.target.value))}/></label>)}{form.items.length>1&&<button type="button" className="danger" onClick={()=>setForm({...form,items:form.items.filter((_,i)=>i!==index)})}>{t('common.delete')}</button>}</fieldset>)}<button type="button" className="button-secondary" onClick={()=>setForm({...form,items:[...form.items,line()]})}>{t('billing.addItem')}</button><button disabled={create.isPending}>{t('common.create')}</button>{error&&<p className="field-error">{error}</p>}{create.isError&&<ApiErrorMessage error={create.error}/>}</form>}
 {invoices.isPending&&<p>{t('common.loading')}</p>}{invoices.isError&&<ApiErrorMessage error={invoices.error}/>}<div className="invoice-grid">{invoices.data?.content.map(invoice=><Link className="invoice-card" to={`/billing/invoices/${invoice.id}`} key={invoice.id}><div><strong>{invoice.invoiceNumber}</strong><span className={`status-badge status-${invoice.status.toLowerCase().replace('_','-')}`}>{t(`status.${invoice.status}`,invoice.status)}</span></div><p>{t('billing.patientId')}: {invoice.patientId}</p><b>{money(invoice.totalAmount,invoice.currency)}</b><small>{t('billing.balance')}: {money(invoice.balance,invoice.currency)} · {new Date(invoice.issuedAt).toLocaleString(i18n.language)}</small></Link>)}</div>{invoices.data?.content.length===0&&<p>{t('billing.empty')}</p>}</section>;
}
