import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {useTranslation} from 'react-i18next';
import {listConsultations} from '../api/consultations';
import {ResourceTable} from '../components/ResourceTable';
import {ApiErrorMessage} from '../components/ApiErrorMessage';
import {useAuth} from '../auth/AuthContext';
export function ConsultationsPage(){const {t,i18n}=useTranslation();const auth=useAuth();const [page,setPage]=useState(0);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const query=useQuery({queryKey:['consultations','list',page,search,status],queryFn:()=>listConsultations(page,search,status)});return <section><div className="page-heading"><h1>{t('nav.consultations')}</h1>{auth.hasAnyRole('PLATFORM_ADMIN','HOSPITAL_ADMIN','DOCTOR')&&<Link className="button" to="/consultations/new">{t('common.add')}</Link>}</div><div className="table-filters"><label>{t('common.search')}<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/></label><label>{t('common.status')}<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0)}}><option value="">{t('common.all',{defaultValue:'Tous / All'})}</option>{['IN_PROGRESS','COMPLETED'].map(value=><option key={value} value={value}>{t(`status.${value}`,value)}</option>)}</select></label></div>{query.isPending&&<p>{t('common.loading')}</p>}{query.isError&&<ApiErrorMessage error={query.error}/>} {query.data&&<ResourceTable data={query.data} page={page} onPageChange={setPage} empty={t('common.empty')} columns={[{label:t('nav.consultations'),render:c=>c.consultationNumber},{label:t('consultation.type'),render:c=>c.type},{label:t('agenda.scheduledStart'),render:c=>new Date(c.startedAt).toLocaleString(i18n.language)},{label:t('common.status'),render:c=>t(`status.${c.status}`,c.status)}]} actions={c=><Link className="button-secondary" to={`/consultations/${c.id}`}>{t('common.view')}</Link>}/>}</section>}
