import {useState,type FormEvent} from 'react';
import {Link,useParams} from 'react-router-dom';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import {billingKeys,cancelInvoice,getInvoice,issueInvoice,recordPayment} from '../api/billing';
import {useAuth} from '../auth/AuthContext';
import {ApiErrorMessage} from '../components/ApiErrorMessage';

export function InvoiceDetailPage(){
 const{id=''}=useParams();const{t,i18n}=useTranslation();const auth=useAuth();const cache=useQueryClient();
 const invoice=useQuery({queryKey:billingKeys.invoice(id),queryFn:()=>getInvoice(id),enabled:!!id});
 const[form,setForm]=useState({amount:'',paymentMethod:'CASH',provider:'',externalTransactionId:''});
 const refresh=()=>{void cache.invalidateQueries({queryKey:billingKeys.invoice(id)});void cache.invalidateQueries({queryKey:['billing','invoices']})};
 const issue=useMutation({mutationFn:()=>issueInvoice(id),onSuccess:refresh});const cancel=useMutation({mutationFn:()=>cancelInvoice(id),onSuccess:refresh});
 const pay=useMutation({mutationFn:()=>recordPayment(id,{amount:Number(form.amount),currency:invoice.data!.currency,paymentMethod:form.paymentMethod,provider:form.provider||undefined,externalTransactionId:form.externalTransactionId||undefined}),onSuccess:()=>{setForm({...form,amount:'',externalTransactionId:''});refresh()}});
 if(invoice.isPending)return<p>{t('common.loading')}</p>;if(invoice.isError)return<ApiErrorMessage error={invoice.error}/>;const data=invoice.data;
 const canWrite=auth.hasAnyRole('PLATFORM_ADMIN','HOSPITAL_ADMIN','HOSPITAL_AGENT','CASHIER','ACCOUNTANT');const payable=['ISSUED','PARTIALLY_PAID'].includes(data.status);
 const money=(amount:number)=>new Intl.NumberFormat(i18n.language,{style:'currency',currency:data.currency}).format(amount);
 const submit=(e:FormEvent)=>{e.preventDefault();if(Number(form.amount)>0)pay.mutate()};const mutationError=issue.error||cancel.error||pay.error;
 return <section><Link to="/billing">← {t('common.back')}</Link><div className="page-heading"><div><p className="eyebrow">{t('billing.invoice')}</p><h1>{data.invoiceNumber}</h1></div><span className={`status-badge status-${data.status.toLowerCase().replace('_','-')}`}>{t(`status.${data.status}`,data.status)}</span></div>
 <dl className="profile-grid"><div><dt>{t('billing.patientId')}</dt><dd>{data.patientId}</dd></div><div><dt>{t('billing.organizationId')}</dt><dd>{data.organizationId}</dd></div><div><dt>{t('billing.total')}</dt><dd>{money(data.totalAmount)}</dd></div><div><dt>{t('billing.amountPaid')}</dt><dd>{money(data.amountPaid)}</dd></div><div><dt>{t('billing.balance')}</dt><dd>{money(data.balance)}</dd></div><div><dt>{t('billing.dueAt')}</dt><dd>{data.dueAt?new Date(data.dueAt).toLocaleString(i18n.language):'—'}</dd></div></dl>
 {canWrite&&<div className="card-actions billing-actions">{data.status==='DRAFT'&&<button onClick={()=>issue.mutate()} disabled={issue.isPending}>{t('billing.issue')}</button>}{['DRAFT','ISSUED'].includes(data.status)&&data.amountPaid===0&&<button className="danger" onClick={()=>cancel.mutate()} disabled={cancel.isPending}>{t('billing.cancelInvoice')}</button>}</div>}
 <section className="detail-section"><h2>{t('billing.items')}</h2><div className="table-scroll"><table><thead><tr><th>{t('billing.description')}</th><th>{t('billing.itemType')}</th><th>{t('billing.quantity')}</th><th>{t('billing.unitPrice')}</th><th>{t('billing.taxAmount')}</th><th>{t('billing.total')}</th></tr></thead><tbody>{data.items.map(item=><tr key={item.id}><td>{item.description}</td><td>{item.itemType}</td><td>{item.quantity}</td><td>{money(item.unitPrice)}</td><td>{money(item.taxAmount)}</td><td>{money(item.totalAmount)}</td></tr>)}</tbody></table></div></section>
 {canWrite&&payable&&<section className="detail-section"><h2>{t('billing.recordPayment')}</h2><form className="entity-form payment-form" onSubmit={submit}><label>{t('billing.amount')}<input required type="number" min="0.01" max={data.balance} step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>{t('billing.paymentMethod')}<select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}>{['CASH','CARD','MOBILE_MONEY','INSURANCE','MUTUAL','THIRD_PARTY'].map(method=><option value={method} key={method}>{t(`billing.methods.${method}`,method)}</option>)}</select></label><label>{t('billing.provider')}<input value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}/></label><label>{t('billing.externalReference')}<input value={form.externalTransactionId} onChange={e=>setForm({...form,externalTransactionId:e.target.value})}/></label><button disabled={pay.isPending}>{t('billing.confirmPayment')}</button></form></section>}
 <section className="detail-section"><h2>{t('billing.payments')}</h2><div className="payment-list">{data.payments.map(payment=><article className="payment-card" key={payment.id}><div><strong>{payment.paymentNumber}</strong><span>{t(`billing.methods.${payment.paymentMethod}`,payment.paymentMethod)}</span></div><b>{money(payment.amount)}</b><small>{new Date(payment.paidAt).toLocaleString(i18n.language)}{payment.transactions[0]?.provider&&` · ${payment.transactions[0].provider}`}{payment.transactions[0]?.externalTransactionId&&` · ${payment.transactions[0].externalTransactionId}`}</small></article>)}</div>{data.payments.length===0&&<p>{t('billing.noPayments')}</p>}</section>
 {mutationError&&<ApiErrorMessage error={mutationError}/>}</section>;
}
