// @vitest-environment jsdom
import {afterEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
vi.mock('react-i18next',()=>({useTranslation:()=>({i18n:{language:'fr'},t:(key:string,fallback?:string)=>fallback??key})}));
vi.mock('../api/client',()=>({ApiError:class extends Error{}}));
vi.mock('../components/ThemeSwitch',()=>({ThemeSwitch:()=>null}));
vi.mock('../api/preferences',()=>({getPreferences:vi.fn().mockResolvedValue({theme:'DARK',avatarUrl:null}),updatePreferences:vi.fn()}));
vi.mock('../api/persons',()=>({getMyProfile:vi.fn(),updateMyProfile:vi.fn()}));
import {getMyProfile,updateMyProfile,type MyProfile} from '../api/persons';
import {getPreferences,updatePreferences} from '../api/preferences';
import {MePage} from './MePage';
const profile:MyProfile={person:{id:'person',keycloakUserId:'subject',personNumber:'P-001',firstName:'Anne',lastName:'Martin',status:'ACTIVE',birthDate:'1990-05-12',gender:'female',preferredLanguageId:'fr',addresses:[],contacts:[{id:'contact',type:'EMAIL',value:'anne@example.com',primary:true,verified:true}],emergencyContacts:[]},languages:[{id:'fr',code:'fr',label:'Français'}],countries:[{id:'ca',iso2:'CA',name:'Canada'}]};
afterEach(()=>{cleanup();vi.clearAllMocks()});
function show(){vi.mocked(getMyProfile).mockResolvedValue(profile);vi.mocked(updateMyProfile).mockResolvedValue(profile);render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MePage/></QueryClientProvider>)}
describe('database personal profile',()=>{it('edits personal data without changing authentication identity and clears verification of a changed contact',async()=>{show();await screen.findByLabelText('Prénom');fireEvent.change(screen.getByLabelText('Prénom'),{target:{value:'Anna'}});fireEvent.change(screen.getByLabelText('Coordonnée'),{target:{value:'anna@example.com'}});fireEvent.change(screen.getByLabelText('Adresse'),{target:{value:'123 rue Principale'}});fireEvent.change(screen.getByLabelText('Ville'),{target:{value:'Québec'}});fireEvent.change(screen.getByLabelText('Pays'),{target:{value:'ca'}});fireEvent.click(screen.getByRole('button',{name:'common.save'}));await waitFor(()=>expect(updateMyProfile).toHaveBeenCalled());const payload=vi.mocked(updateMyProfile).mock.calls[0]![0];expect(payload).toMatchObject({firstName:'Anna',birthDate:'1990-05-12',gender:'female',preferredLanguageId:'fr',homeAddress:{line1:'123 rue Principale',city:'Québec',countryId:'ca'},contacts:[{value:'anna@example.com',verified:false}]});expect(payload).not.toHaveProperty('keycloakUserId');expect(payload).not.toHaveProperty('personNumber')});it('offers real reference choices and preserves an existing uncommon gender value',async()=>{vi.mocked(getMyProfile).mockResolvedValue({...profile,person:{...profile.person,gender:'non-binary'}});render(<QueryClientProvider client={new QueryClient()}><MePage/></QueryClientProvider>);const gender=await screen.findByLabelText('Sexe');expect((gender as HTMLSelectElement).value).toBe('non-binary');expect(screen.getByRole('option',{name:'Canada'})).toBeTruthy();expect((screen.getByLabelText('Date de naissance') as HTMLInputElement).type).toBe('date')})});

it('saves a profile photo while retaining the database theme preference',async()=>{show();vi.mocked(updatePreferences).mockResolvedValue({theme:'DARK',avatarUrl:'https://images.example.com/photo.jpg'});const photo=await screen.findByLabelText('Photo de profil (lien HTTPS)');fireEvent.change(photo,{target:{value:'https://images.example.com/photo.jpg'}});fireEvent.click(screen.getByRole('button',{name:'Enregistrer la personnalisation'}));await waitFor(()=>expect(updatePreferences).toHaveBeenCalledWith({theme:'DARK',avatarUrl:'https://images.example.com/photo.jpg'},expect.anything()));expect(getPreferences).toHaveBeenCalled()});
