import {FormEvent,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Link,useParams} from 'react-router-dom';
import {useTranslation} from 'react-i18next';
import {addBed,addDepartment,addRoom,addService,getOrganization,organizationKeys} from '../api/organizations';
import {useAuth} from '../auth/AuthContext';
import {ApiErrorMessage} from '../components/ApiErrorMessage';

export function OrganizationDetailPage(){const {id=''}=useParams();const {t}=useTranslation();const auth=useAuth();const client=useQueryClient();const query=useQuery({queryKey:organizationKeys.detail(id),queryFn:()=>getOrganization(id)});const refresh=()=>client.invalidateQueries({queryKey:organizationKeys.detail(id)});const [departmentId,setDepartmentId]=useState('');const [roomId,setRoomId]=useState('');
 const dept=useMutation({mutationFn:(v:{code:string;name:string})=>addDepartment(id,v),onSuccess:refresh});const svc=useMutation({mutationFn:(v:{code:string;name:string})=>addService(id,departmentId,v),onSuccess:refresh});const room=useMutation({mutationFn:(v:{roomNumber:string})=>addRoom(id,{...v,departmentId:departmentId||undefined}),onSuccess:refresh});const bed=useMutation({mutationFn:(v:{bedNumber:string})=>addBed(id,roomId,v),onSuccess:refresh});
 if(query.isPending)return <p>{t('common.loading')}</p>;if(query.isError)return <ApiErrorMessage error={query.error}/>;const o=query.data;const canWrite=auth.hasAnyRole('PLATFORM_ADMIN','HOSPITAL_ADMIN');
 return <section><div className="page-heading"><div><p className="eyebrow">{t('organizations.details')}</p><h1>{o.name}</h1><p>{o.number} · {o.status}</p></div>{canWrite&&<Link className="button" to={`/organizations/${id}/edit`}>{t('common.edit')}</Link>}</div>
 <h2>{t('organizations.departments')}</h2>{o.departments.map(d=><article className="structure-card" key={d.id}><h3>{d.code} — {d.name}</h3><ul>{d.services.map(s=><li key={s.id}>{s.code} — {s.name}</li>)}</ul></article>)}
 {canWrite&&<><InlineForm title={t('organizations.addDepartment')} fields={['code','name']} onSubmit={dept.mutate}/><InlineForm title={t('organizations.addService')} fields={['code','name']} select={{value:departmentId,onChange:setDepartmentId,items:o.departments.map(d=>({id:d.id,label:d.name}))}} onSubmit={svc.mutate}/></>}
 <h2>{t('organizations.rooms')} / {t('organizations.beds')}</h2>{o.rooms.map(r=><article className="structure-card" key={r.id}><h3>{r.roomNumber}</h3><ul>{r.beds.map(b=><li key={b.id}>{b.bedNumber} — {b.status}</li>)}</ul></article>)}
 {canWrite&&<><InlineForm title={t('organizations.addRoom')} fields={['roomNumber']} select={{value:departmentId,onChange:setDepartmentId,items:o.departments.map(d=>({id:d.id,label:d.name}))}} onSubmit={room.mutate}/><InlineForm title={t('organizations.addBed')} fields={['bedNumber']} select={{value:roomId,onChange:setRoomId,items:o.rooms.map(r=>({id:r.id,label:r.roomNumber}))}} onSubmit={bed.mutate}/></>}
 {[dept,svc,room,bed].some(m=>m.isError)&&<ApiErrorMessage error={[dept,svc,room,bed].find(m=>m.error)?.error}/>}</section>}
function InlineForm({title,fields,select,onSubmit}:{title:string;fields:string[];select?:{value:string;onChange:(v:string)=>void;items:{id:string;label:string}[]};onSubmit:(v:any)=>void}){const [values,setValues]=useState<Record<string,string>>({});const submit=(e:FormEvent)=>{e.preventDefault();if(fields.every(f=>values[f]?.trim())&&(!select||select.value))onSubmit(values)};return <form className="inline-form" onSubmit={submit}><strong>{title}</strong>{select&&<select value={select.value} onChange={e=>select.onChange(e.target.value)} required><option value="">—</option>{select.items.map(i=><option value={i.id} key={i.id}>{i.label}</option>)}</select>}{fields.map(f=><input key={f} value={values[f]??''} placeholder={f} required onChange={e=>setValues({...values,[f]:e.target.value})}/>)}<button>+</button></form>}
