import {FormEvent,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {useTranslation} from 'react-i18next';
import {createPatient,getPatient,updatePatient,type PatientInput} from '../api/patients';
import {ApiErrorMessage} from '../components/ApiErrorMessage';
import {PersonPicker} from '../components/PersonPicker';

export function PatientFormPage(){const {id}=useParams();const query=useQuery({queryKey:['patients',id],queryFn:()=>getPatient(id!),enabled:!!id});if(id&&query.isPending)return <p>…</p>;if(query.isError)return <ApiErrorMessage error={query.error}/>;return <PatientEditor key={id??'new'} id={id} initial={query.data}/>}
function PatientEditor({id,initial}:{id?:string;initial?:PatientInput}){const {t}=useTranslation();const navigate=useNavigate();const cache=useQueryClient();const [form,setForm]=useState({status:initial?.status??'ACTIVE',personId:initial?.personId??'',bloodGroup:initial?.bloodGroup??'',rhesus:initial?.rhesus??'',maritalStatus:initial?.maritalStatus??'',occupation:initial?.occupation??''});const mutation=useMutation({mutationFn:(input:PatientInput)=>id?updatePatient(id,input):createPatient(input),onSuccess:async p=>{await cache.invalidateQueries({queryKey:['patients']});navigate(`/patients/${p.id}`)}});const submit=(e:FormEvent)=>{e.preventDefault();mutation.mutate(form)};return <section><div className="page-heading"><div><p className="eyebrow">{t('patients.eyebrow')}</p><h1>{id?t('common.edit'):t('patients.create')}</h1></div></div>{mutation.isError&&<ApiErrorMessage error={mutation.error}/>}<form className="entity-form" onSubmit={submit}><fieldset><legend>{t('patients.personId')}</legend>{id?<p>{initial?.personId}</p>:<PersonPicker value={form.personId} onChange={personId=>setForm({...form,personId})}/>}</fieldset><fieldset><legend>{t('patients.eyebrow')}</legend><div className="form-grid">{(['bloodGroup','rhesus','maritalStatus'] as const).map(name=><label key={name}>{t(`patients.${name}`)}<select value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})}><option value="">—</option>{form[name]&&!(name==='bloodGroup'?['A','B','AB','O']:name==='rhesus'?['POSITIVE','NEGATIVE']:['SINGLE','MARRIED','DIVORCED','WIDOWED','OTHER']).includes(form[name])&&<option value={form[name]}>{form[name]}</option>}{(name==='bloodGroup'?['A','B','AB','O']:name==='rhesus'?['POSITIVE','NEGATIVE']:['SINGLE','MARRIED','DIVORCED','WIDOWED','OTHER']).map(value=><option key={value} value={value}>{t(`status.${value}`,value)}</option>)}</select></label>)}<label>{t('patients.occupation')}<input maxLength={150} value={form.occupation} onChange={e=>setForm({...form,occupation:e.target.value})}/></label><label>{t('patients.status')}<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></label></div></fieldset><div className="form-actions"><Link className="button button-secondary" to="/patients">{t('common.cancel')}</Link><button disabled={mutation.isPending||!form.personId}>{id?t('common.save'):t('common.create')}</button></div></form></section>}
