// @vitest-environment jsdom
import {afterEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
vi.mock('../api/client',()=>({ApiError:class extends Error{}}));
vi.mock('../auth/AuthContext',()=>({useAuth:()=>({login:vi.fn()})}));
vi.mock('react-i18next',()=>({useTranslation:()=>({t:(key:string)=>key})}));
vi.mock('../api/professionalOnboarding',()=>({getMyDossier:vi.fn(),listCountries:vi.fn().mockResolvedValue([{id:'cm',name:'Cameroun'}]),listSpecialities:vi.fn().mockResolvedValue([]),saveDossier:vi.fn(),uploadDocument:vi.fn(),submitDossier:vi.fn(),onboardingKeys:{me:['onboarding','me']}}));
import {getMyDossier,uploadDocument} from '../api/professionalOnboarding';
import {ProfessionalOnboardingPage,minimumIdentityExpiry} from './ProfessionalOnboardingPage';
afterEach(()=>{cleanup();vi.clearAllMocks();});
function show(){render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><ProfessionalOnboardingPage/></QueryClientProvider>);}
describe('professional application',()=>{it('allows an independent draft without an organization field',async()=>{vi.mocked(getMyDossier).mockResolvedValue(null);show();await screen.findByRole('heading',{name:'onboarding.title'});expect(screen.queryByLabelText('professionals.organizationId')).toBeNull();expect(screen.getByText('onboarding.independent')).toBeTruthy();expect(screen.getByLabelText('onboarding.country').tagName).toBe('SELECT');});it('disables submission until evidence is uploaded and rejects oversized evidence',async()=>{vi.mocked(getMyDossier).mockResolvedValue({id:'id',personId:'p',keycloakUserId:'k',profession:'medecin',licenseNumber:'ABC',issuingAuthority:'Order',countryId:'cm',status:'DRAFT',proofUploaded:false,createdAt:'now',updatedAt:'now'});show();await screen.findByRole('heading',{name:'onboarding.title'});expect(screen.getByRole('button',{name:'onboarding.submit'}).hasAttribute('disabled')).toBe(true);const oversized=new File([new Uint8Array(5*1024*1024+1)],'proof.pdf',{type:'application/pdf'});fireEvent.change(screen.getByLabelText('onboarding.documentKinds.LICENSE'),{target:{files:[oversized]}});await waitFor(()=>expect(screen.getByRole('alert')).toBeTruthy());expect(uploadDocument).not.toHaveBeenCalled();});});

it('clamps three calendar months and rejects the threshold day',()=>{expect(minimumIdentityExpiry(new Date(2026,0,31))).toBe('2026-05-01');});
it('allows a specialty outside catalog suggestions',async()=>{vi.mocked(getMyDossier).mockResolvedValue(null);show();await screen.findByRole('heading',{name:'onboarding.title'});const input=screen.getByLabelText(/onboarding.speciality/);expect(input.tagName).toBe('INPUT');expect(input.getAttribute('list')).toBe('professional-specialities');fireEvent.change(input,{target:{value:'New speciality'}});expect((input as HTMLInputElement).value).toBe('New speciality');});
it('requires both identity sides as well as the licence before submission',async()=>{vi.mocked(getMyDossier).mockResolvedValue({id:'id',personId:'p',keycloakUserId:'k',profession:'medecin',licenseNumber:'ABC',issuingAuthority:'Order',countryId:'cm',status:'DRAFT',proofUploaded:true,identityFrontUploaded:true,identityBackUploaded:false,identityDocumentType:'PASSPORT',identityExpiresOn:'2099-01-01',createdAt:'now',updatedAt:'now'});show();await screen.findByRole('heading',{name:'onboarding.title'});expect(screen.getByRole('button',{name:'onboarding.submit'}).hasAttribute('disabled')).toBe(true);expect(screen.getByLabelText('onboarding.documentKinds.ID_FRONT')).toBeTruthy();expect(screen.getByLabelText('onboarding.documentKinds.ID_BACK')).toBeTruthy();});
it('shows identity number and all three upload controls before the first save',async()=>{vi.mocked(getMyDossier).mockResolvedValue(null);show();await screen.findByRole('heading',{name:'onboarding.title'});const number=screen.getByLabelText('onboarding.identityDocumentNumber');expect(number.hasAttribute('required')).toBe(true);expect(number.getAttribute('maxlength')).toBe('100');for(const kind of ['ID_FRONT','ID_BACK','LICENSE'])expect(screen.getByLabelText(`onboarding.documentKinds.${kind}`).hasAttribute('disabled')).toBe(true);expect(screen.getByText('onboarding.saveBeforeUpload')).toBeTruthy();expect(screen.getByRole('button',{name:'onboarding.submit'}).hasAttribute('disabled')).toBe(true);});
it('enables the three upload controls once a draft has been saved',async()=>{vi.mocked(getMyDossier).mockResolvedValue({id:'id',personId:'p',keycloakUserId:'k',profession:'medecin',licenseNumber:'ABC',issuingAuthority:'Order',countryId:'cm',status:'DRAFT',proofUploaded:false,identityDocumentNumber:'N123',createdAt:'now',updatedAt:'now'});show();await screen.findByRole('heading',{name:'onboarding.title'});for(const kind of ['ID_FRONT','ID_BACK','LICENSE'])expect(screen.getByLabelText(`onboarding.documentKinds.${kind}`).hasAttribute('disabled')).toBe(false);expect((screen.getByLabelText('onboarding.identityDocumentNumber') as HTMLInputElement).value).toBe('N123');});
