import {FormEvent,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {useTranslation} from 'react-i18next';
import {createProfessional,getProfessional,updateProfessional,professionalKeys,ProfessionalInput} from '../api/professionals';
import {ApiErrorMessage} from '../components/ApiErrorMessage';
import {PersonPicker} from '../components/PersonPicker';
export function ProfessionalFormPage(){const {id}=useParams();const query=useQuery({queryKey:['professionals',id],queryFn:()=>getProfessional(id!),enabled:!!id});if(id&&query.isPending)return <p>…</p>;if(query.isError)return <ApiErrorMessage error={query.error}/>;return <ProfessionalEditor key={id??'new'} id={id} initial={query.data}/>}
function ProfessionalEditor({id,initial}:{id?:string;initial?:ProfessionalInput}){const {t}=useTranslation();const navigate=useNavigate();const client=useQueryClient();const [v,setV]=useState<ProfessionalInput>({personId:'',professionalNumber:'',professionalType:'DOCTOR',status:'ACTIVE',...initial});const mutation=useMutation({mutationFn:(input:ProfessionalInput)=>id?updateProfessional(id,input):createProfessional(input),onSuccess:async p=>{await client.invalidateQueries({queryKey:professionalKeys.all});navigate(`/professionals/${p.id}`)}});const submit=(e:FormEvent)=>{e.preventDefault();if(v.personId&&v.professionalNumber.trim())mutation.mutate(v)};return <section><h1>{id?t('common.edit'):t('professionals.create')}</h1>{mutation.isError&&<ApiErrorMessage error={mutation.error}/>}<form className="entity-form" onSubmit={submit}><fieldset><legend>{t('professionals.personId')}</legend>{id?<p>{initial?.personId}</p>:<PersonPicker value={v.personId} onChange={personId=>setV({...v,personId})}/>}</fieldset><fieldset><legend>{t('professionals.title')}</legend><div className="form-grid"><label>{t('professionals.number')}<input readOnly={!!id} required maxLength={50} value={v.professionalNumber} onChange={e=>setV({...v,professionalNumber:e.target.value})}/></label><label>{t('professionals.type')}<select required value={v.professionalType} onChange={e=>setV({...v,professionalType:e.target.value})}>{!['DOCTOR','NURSE','LAB_TECHNICIAN'].includes(v.professionalType)&&<option value={v.professionalType}>{v.professionalType}</option>}{['DOCTOR','NURSE','LAB_TECHNICIAN'].map(type=><option key={type} value={type}>{t(`roles.${type}`,type)}</option>)}</select></label></div></fieldset><div className="form-actions"><Link className="button button-secondary" to="/professionals">{t('common.cancel')}</Link><button disabled={mutation.isPending||!v.personId}>{t('common.save')}</button></div></form></section>}
