import {FormEvent,useState} from 'react';
import type {ReactNode} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useParams} from 'react-router-dom';
import {useTranslation} from 'react-i18next';
import {addAssignment,addAvailability,addLicense,addSchedule,addSpeciality,getProfessional,listSpecialityCatalog,professionalKeys} from '../api/professionals';
import {listOrganizations,organizationKeys} from '../api/organizations';
import {ApiErrorMessage} from '../components/ApiErrorMessage';
import {useAuth} from '../auth/AuthContext';

type Values=Record<string,string|boolean>;
export function ProfessionalDetailPage(){const {id=''}=useParams();const {t}=useTranslation();const auth=useAuth();const cache=useQueryClient();const query=useQuery({queryKey:professionalKeys.detail(id),queryFn:()=>getProfessional(id)});const catalog=useQuery({queryKey:professionalKeys.specialities,queryFn:listSpecialityCatalog});const organizations=useQuery({queryKey:organizationKeys.all,queryFn:listOrganizations});const refresh=()=>cache.invalidateQueries({queryKey:professionalKeys.detail(id)});const [assignmentId,setAssignmentId]=useState('');
 const license=useMutation({mutationFn:(v:Values)=>addLicense(id,{licenseNumber:String(v.licenseNumber),issuingAuthority:String(v.issuingAuthority||'')||undefined,issuedAt:String(v.issuedAt||'')||undefined,expiresAt:String(v.expiresAt||'')||undefined,status:'ACTIVE'}),onSuccess:refresh});
 const speciality=useMutation({mutationFn:(v:Values)=>addSpeciality(id,{specialityCatalogId:String(v.specialityCatalogId),primary:Boolean(v.primary)}),onSuccess:refresh});
 const assignment=useMutation({mutationFn:(v:Values)=>addAssignment(id,{organizationId:String(v.organizationId),departmentId:String(v.departmentId||'')||undefined,serviceId:String(v.serviceId||'')||undefined,position:String(v.position||'')||undefined,employeeNumber:String(v.employeeNumber||'')||undefined,startDate:String(v.startDate),endDate:String(v.endDate||'')||undefined,status:'ACTIVE'}),onSuccess:refresh});
 const schedule=useMutation({mutationFn:(v:Values)=>addSchedule(id,assignmentId,{dayOfWeek:Number(v.dayOfWeek),startTime:String(v.startTime),endTime:String(v.endTime),slotDurationMinutes:Number(v.slotDurationMinutes)}),onSuccess:refresh});
 const availability=useMutation({mutationFn:(v:Values)=>addAvailability(id,assignmentId,{startAt:new Date(String(v.startAt)).toISOString(),endAt:new Date(String(v.endAt)).toISOString(),availabilityType:String(v.availabilityType),status:'AVAILABLE'}),onSuccess:refresh});
 if(query.isPending)return <p>{t('common.loading')}</p>;if(query.isError)return <ApiErrorMessage error={query.error}/>;const p=query.data;const canWrite=auth.hasAnyRole('PLATFORM_ADMIN','HOSPITAL_ADMIN');const error=[license,speciality,assignment,schedule,availability].find(m=>m.isError)?.error;
 return <section><p className="eyebrow">{t('professionals.details')}</p><h1>{p.professionalNumber}</h1><dl className="profile-grid"><Info label={t('professionals.type')} value={p.professionalType}/><Info label={t('professionals.personId')} value={p.personId}/><Info label={t('professionals.status')} value={p.status}/></dl>{error&&<ApiErrorMessage error={error}/>}<Section title={t('professionals.licenses')}>{p.licenses.length?p.licenses.map(x=><article className="structure-card" key={x.id}><strong>{x.licenseNumber}</strong><p>{x.issuingAuthority||'—'} · {x.status}</p><small>{x.issuedAt||'—'} → {x.expiresAt||'—'}</small></article>):<p>{t('common.none')}</p>}{canWrite&&<DynamicForm title={t('professionals.addLicense')} fields={[['licenseNumber','text'],['issuingAuthority','text'],['issuedAt','date'],['expiresAt','date']]} required={['licenseNumber']} onSubmit={license.mutate}/>}</Section>
 <Section title={t('professionals.specialities')}>{p.specialities.length?<ul>{p.specialities.map(x=><li key={x.specialityCatalogId}>{x.name} ({x.code}){x.primary?` — ${t('professionals.primary')}`:''}</li>)}</ul>:<p>{t('common.none')}</p>}{canWrite&&<DynamicForm title={t('professionals.addSpeciality')} fields={[]} selects={[{name:'specialityCatalogId',items:(catalog.data??[]).map(x=>({id:x.id,label:`${x.code} — ${x.name}`}))}]} checks={['primary']} required={['specialityCatalogId']} onSubmit={speciality.mutate}/>}</Section>
 <Section title={t('professionals.assignments')}>{p.assignments.map(a=><article className="structure-card" key={a.id}><h3>{a.position||t('professionals.assignment')} · {a.status}</h3><p>{t('professionals.organizationId')}: {a.organizationId}</p><p>{a.startDate} → {a.endDate||'—'}</p><h4>{t('professionals.schedule')}</h4>{a.schedules.map(s=><p key={s.id}>{t(`weekdays.${s.dayOfWeek}`)} · {s.startTime}–{s.endTime} · {s.slotDurationMinutes} min</p>)}<h4>{t('professionals.availabilities')}</h4>{a.availabilities.map(v=><p key={v.id}>{new Date(v.startAt).toLocaleString()} → {new Date(v.endAt).toLocaleString()} · {v.availabilityType}</p>)}</article>)}{canWrite&&<><DynamicForm title={t('professionals.addAssignment')} fields={[['departmentId','text'],['serviceId','text'],['position','text'],['employeeNumber','text'],['startDate','date'],['endDate','date']]} selects={[{name:'organizationId',items:(organizations.data?.content??[]).map(o=>({id:o.id,label:o.name}))}]} required={['organizationId','startDate']} onSubmit={assignment.mutate}/><AssignmentSelect value={assignmentId} onChange={setAssignmentId} items={p.assignments.map(a=>({id:a.id,label:a.position||a.organizationId}))}/><DynamicForm title={t('professionals.addSchedule')} fields={[['dayOfWeek','number'],['startTime','time'],['endTime','time'],['slotDurationMinutes','number']]} required={['dayOfWeek','startTime','endTime','slotDurationMinutes']} disabled={!assignmentId} onSubmit={schedule.mutate}/><DynamicForm title={t('professionals.addAvailability')} fields={[['startAt','datetime-local'],['endAt','datetime-local'],['availabilityType','text']]} required={['startAt','endAt','availabilityType']} disabled={!assignmentId} onSubmit={availability.mutate}/></>}</Section></section>}
function Info({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="detail-section"><h2>{title}</h2>{children}</section>}
function AssignmentSelect({value,onChange,items}:{value:string;onChange:(v:string)=>void;items:{id:string;label:string}[]}){const {t}=useTranslation();return <label className="assignment-select">{t('professionals.assignment')}<select value={value} onChange={e=>onChange(e.target.value)}><option value="">—</option>{items.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>}
function DynamicForm({title,fields,selects=[],checks=[],required,onSubmit,disabled=false}:{title:string;fields:[string,string][];selects?:{name:string;items:{id:string;label:string}[]}[];checks?:string[];required:string[];onSubmit:(v:Values)=>void;disabled?:boolean}){const {t}=useTranslation();const [v,setV]=useState<Values>({});const submit=(e:FormEvent)=>{e.preventDefault();if(required.every(x=>String(v[x]??'').trim()))onSubmit(v)};return <form className="entity-form compact-form" onSubmit={submit}><strong>{title}</strong>{selects.map(s=><label key={s.name}>{t(`professionals.${s.name}`)}<select value={String(v[s.name]??'')} required={required.includes(s.name)} onChange={e=>setV({...v,[s.name]:e.target.value})}><option value="">—</option>{s.items.map(i=><option key={i.id} value={i.id}>{i.label}</option>)}</select></label>)}{fields.map(([name,type])=><label key={name}>{t(`professionals.${name}`)}<input type={type} required={required.includes(name)} value={String(v[name]??'')} onChange={e=>setV({...v,[name]:e.target.value})}/></label>)}{checks.map(name=><label className="check-field" key={name}><input type="checkbox" checked={Boolean(v[name])} onChange={e=>setV({...v,[name]:e.target.checked})}/>{t(`professionals.${name}`)}</label>)}<button disabled={disabled}>{t('common.add')}</button></form>}
