import {useState,type FormEvent} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import {createCountry,downloadProof,listDossiers,onboardingKeys,reviewDossier,type Dossier} from '../api/professionalOnboarding';
import {ApiErrorMessage} from '../components/ApiErrorMessage';
export function ProfessionalReviewPage(){const {t}=useTranslation();const query=useQuery({queryKey:onboardingKeys.requests,queryFn:listDossiers});return <section><h1>{t('onboarding.reviewTitle')}</h1><p>{t('onboarding.reviewHint')}</p><CountryForm/>{query.isPending&&<p>{t('common.loading')}</p>}{query.isError&&<ApiErrorMessage error={query.error}/>}<div className="card-grid">{query.data?.map(d=><ReviewCard key={d.id} dossier={d}/>)}</div>{query.data?.length===0&&<p>{t('common.none')}</p>}</section>;}
function ReviewCard({dossier:d}:{dossier:Dossier}){const {t}=useTranslation();const client=useQueryClient();const [reason,setReason]=useState('');const [downloadError,setDownloadError]=useState<unknown>();const review=useMutation({mutationFn:(decision:'APPROVE'|'REJECT'|'SUSPEND')=>reviewDossier(d.id,decision,reason.trim()),onSuccess:()=>client.invalidateQueries({queryKey:onboardingKeys.requests})});return <article className="structure-card"><h2>{t(`onboarding.professions.${d.profession}`)}</h2><p>{[d.firstName,d.lastName].filter(Boolean).join(' ')}</p><p>{t('onboarding.license')}: {d.licenseNumber}</p><p>{t('onboarding.authority')}: {d.issuingAuthority}</p><strong>{t(`onboarding.status.${d.status}`)}</strong>{d.roleSyncStatus&&d.roleSyncStatus!=='SYNCED'&&<p>{t(d.roleSyncStatus==='FAILED'?'onboarding.roleSyncFailed':'onboarding.roleSyncPending')}</p>}{d.reason&&<p>{d.reason}</p>}{d.proofUploaded&&<p><button className="button-secondary" onClick={()=>void downloadProof(d.id).catch(setDownloadError)}>{t('onboarding.openProof')}</button></p>}{['SUBMITTED','APPROVED','SUSPENDED'].includes(d.status)&&<><label>{t('onboarding.reason')}<textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="form-actions">{(d.status==='SUBMITTED'||d.status==='SUSPENDED')&&<><button disabled={review.isPending||!reason.trim()} onClick={()=>review.mutate('APPROVE')}>{t('onboarding.approve')}</button>{d.status==='SUBMITTED'&&<button className="button-secondary" disabled={review.isPending||!reason.trim()} onClick={()=>review.mutate('REJECT')}>{t('onboarding.reject')}</button>}</>}{d.status==='APPROVED'&&<button className="button-secondary" disabled={review.isPending||!reason.trim()} onClick={()=>review.mutate('SUSPEND')}>{t('onboarding.suspend')}</button>}</div></>}{review.isError&&<ApiErrorMessage error={review.error}/>} {!!downloadError&&<ApiErrorMessage error={downloadError}/>}</article>;}

function CountryForm(){const {t}=useTranslation();const client=useQueryClient();const create=useMutation({mutationFn:createCountry,onSuccess:()=>client.invalidateQueries({queryKey:["onboarding-countries"]})});function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);create.mutate({iso2:String(data.get("iso2")).toUpperCase(),name:String(data.get("name")).trim()});}return <form className="entity-form" onSubmit={submit}><h2>{t("onboarding.configureCountries")}</h2><label>{t("onboarding.countryCode")}<input name="iso2" required pattern="[A-Za-z]{2}" maxLength={2}/></label><label>{t("organizations.name")}<input name="name" required maxLength={150}/></label><button disabled={create.isPending}>{t("common.add")}</button>{create.isError&&<ApiErrorMessage error={create.error}/>} {create.isSuccess&&<p role="status">{t("organizations.saved")}</p>}</form>;}
