package org.novasos.healthysv2.professional;
import static org.assertj.core.api.Assertions.*;
import java.time.*; import java.util.UUID; import jakarta.persistence.EntityManager;
import org.junit.jupiter.api.Test; import org.novasos.healthysv2.TestcontainersConfiguration; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.context.annotation.Import; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.context.ActiveProfiles; import org.springframework.transaction.annotation.Transactional;
@ActiveProfiles("test") @Import(TestcontainersConfiguration.class) @SpringBootTest @Transactional
class ProfessionalRepositoryIntegrationTests {
 @Autowired ProfessionalRepository repository; @Autowired JdbcTemplate jdbc; @Autowired EntityManager entityManager;
 @Test void persistsCompleteAggregateAndMultipleOrganizations(){UUID person=person();UUID firstOrg=organization("A");UUID secondOrg=organization("B");UUID speciality=UUID.randomUUID();jdbc.update("insert into catalog.speciality_catalog(id,code,name) values (?,?,?)",speciality,"CARD-"+speciality,"Cardiology");var p=Professional.create(person,"PRO-REPO","DOCTOR",null);p.addLicense("LIC-REPO","College",null,LocalDate.now(),null,null);p.addSpeciality(speciality,true);var first=p.addAssignment(firstOrg,null,null,"Doctor",null,LocalDate.now(),null,null);first.addSchedule(1,LocalTime.of(8,0),LocalTime.of(12,0),30);first.addAvailability(Instant.now(),Instant.now().plusSeconds(3600),"CONSULTATION",null);p.addAssignment(secondOrg,null,null,"Consultant",null,LocalDate.now(),null,null);repository.saveAndFlush(p);entityManager.clear();var loaded=repository.findById(p.getId()).orElseThrow();assertThat(loaded.getAssignments()).hasSize(2);assertThat(loaded.getLicenses()).hasSize(1);assertThat(loaded.getSpecialities()).hasSize(1);}
 @Test void databaseEnforcesPersonAndNumberUniqueness(){UUID person=person();repository.saveAndFlush(Professional.create(person,"PRO-UNIQUE","DOCTOR",null));assertThatThrownBy(()->repository.saveAndFlush(Professional.create(person,"PRO-OTHER","NURSE",null))).isInstanceOf(DataIntegrityViolationException.class);}
 private UUID person(){UUID id=UUID.randomUUID();jdbc.update("insert into identity.person(id,person_number,first_name,last_name,status) values (?,?,?,?,?)",id,"PER-"+id,"Test","User","ACTIVE");return id;}
 private UUID organization(String suffix){UUID id=UUID.randomUUID();jdbc.update("insert into organization.organization(id,organization_number,name) values (?,?,?)",id,"ORG-"+suffix+id,"Hospital "+suffix);return id;}
}
