package org.novasos.healthysv2.professional;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.time.Instant; import java.util.*; import org.junit.jupiter.api.*; import org.novasos.healthysv2.TestcontainersConfiguration; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.*; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.context.annotation.*; import org.springframework.http.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.oauth2.jwt.*; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc; import org.springframework.transaction.annotation.Transactional;
@ActiveProfiles("test") @SpringBootTest(properties={"spring.security.oauth2.resourceserver.jwt.issuer-uri=https://keycloak.example/realms/healthys","spring.security.oauth2.resourceserver.jwt.audiences=healthys-backend-apps","healthys.security.api-client-id=healthys-backend-apps","healthys.security.cors.allowed-origins=http://localhost:5173"}) @AutoConfigureMockMvc @Import({TestcontainersConfiguration.class,ProfessionalApiIntegrationTests.JwtFixtures.class}) @Transactional
class ProfessionalApiIntegrationTests {
 @Autowired MockMvc mvc; @Autowired JdbcTemplate jdbc;
 @Test void adminManagesCompleteProfessionalProfile() throws Exception {UUID person=person();UUID org=organization();UUID speciality=speciality();String body=mvc.perform(post("/api/v1/professionals").header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"personId\":\"%s\",\"professionalNumber\":\"PRO-API\",\"professionalType\":\"DOCTOR\"}".formatted(person))).andExpect(status().isCreated()).andExpect(jsonPath("$.professionalNumber").value("PRO-API")).andReturn().getResponse().getContentAsString();UUID p=id(body);
  mvc.perform(post("/api/v1/professionals/{p}/licenses",p).header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"licenseNumber\":\"LIC-API\",\"issuingAuthority\":\"College\"}")).andExpect(status().isCreated());
  mvc.perform(post("/api/v1/professionals/{p}/specialities",p).header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"specialityCatalogId\":\"%s\",\"primary\":true}".formatted(speciality))).andExpect(status().isCreated());
  String assignment=mvc.perform(post("/api/v1/professionals/{p}/assignments",p).header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"organizationId\":\"%s\",\"position\":\"Doctor\",\"startDate\":\"2026-01-01\"}".formatted(org))).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();UUID a=id(assignment);
  mvc.perform(post("/api/v1/professionals/{p}/assignments/{a}/schedules",p,a).header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"dayOfWeek\":1,\"startTime\":\"08:00:00\",\"endTime\":\"12:00:00\",\"slotDurationMinutes\":30}")).andExpect(status().isCreated());
  mvc.perform(post("/api/v1/professionals/{p}/assignments/{a}/availabilities",p,a).header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"startAt\":\"2026-01-01T08:00:00Z\",\"endAt\":\"2026-01-01T12:00:00Z\",\"availabilityType\":\"CONSULTATION\"}")).andExpect(status().isCreated());
  mvc.perform(get("/api/v1/professionals/{p}",p).header(HttpHeaders.AUTHORIZATION,"Bearer agent")).andExpect(status().isOk()).andExpect(jsonPath("$.licenses.length()").value(1)).andExpect(jsonPath("$.specialities[0].primary").value(true)).andExpect(jsonPath("$.assignments[0].schedules.length()").value(1)).andExpect(jsonPath("$.assignments[0].availabilities.length()").value(1));
  mvc.perform(get("/api/v1/professionals").param("query","PRO-API").header(HttpHeaders.AUTHORIZATION,"Bearer agent")).andExpect(status().isOk()).andExpect(jsonPath("$.content.length()").value(1)); }
 @Test void agentCannotCreateProfessional() throws Exception {mvc.perform(post("/api/v1/professionals").header(HttpHeaders.AUTHORIZATION,"Bearer agent").contentType(MediaType.APPLICATION_JSON).content("{}" )).andExpect(status().isForbidden());}
 @Test void rejectsAssignmentToUnknownOrganization() throws Exception {UUID p=createProfessional();mvc.perform(post("/api/v1/professionals/{p}/assignments",p).header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"organizationId\":\"%s\",\"startDate\":\"2026-01-01\"}".formatted(UUID.randomUUID()))).andExpect(status().isNotFound());}
 private UUID createProfessional() throws Exception {UUID person=person();String b=mvc.perform(post("/api/v1/professionals").header(HttpHeaders.AUTHORIZATION,"Bearer admin").contentType(MediaType.APPLICATION_JSON).content("{\"personId\":\"%s\",\"professionalNumber\":\"PRO-%s\",\"professionalType\":\"NURSE\"}".formatted(person,person))).andReturn().getResponse().getContentAsString();return id(b);}
 private UUID person(){UUID id=UUID.randomUUID();jdbc.update("insert into identity.person(id,person_number,first_name,last_name,status) values (?,?,?,?,?)",id,"PER-"+id,"Ada","Lovelace","ACTIVE");return id;} private UUID organization(){UUID id=UUID.randomUUID();jdbc.update("insert into organization.organization(id,organization_number,name) values (?,?,?)",id,"ORG-"+id,"Hospital");return id;} private UUID speciality(){UUID id=UUID.randomUUID();jdbc.update("insert into catalog.speciality_catalog(id,code,name) values (?,?,?)",id,"SPEC-"+id,"Cardiology");return id;} private UUID id(String body){var m=java.util.regex.Pattern.compile("\\\"id\\\":\\\"([^\\\"]+)\\\"").matcher(body);if(!m.find())throw new IllegalArgumentException(body);return UUID.fromString(m.group(1));}
 @TestConfiguration(proxyBeanMethods=false) static class JwtFixtures {@Bean JwtDecoder jwtDecoder(){return token->jwt(token,token.equals("admin")?List.of("PLATFORM_ADMIN"):List.of("HOSPITAL_AGENT"));}private Jwt jwt(String token,List<String> roles){Instant now=Instant.now();return Jwt.withTokenValue(token).header("alg","RS256").subject(UUID.randomUUID().toString()).issuer("https://keycloak.example/realms/healthys").audience(List.of("healthys-backend-apps")).issuedAt(now).expiresAt(now.plusSeconds(300)).claim("realm_access",Map.of("roles",roles)).claim("resource_access",Map.of()).build();}}
}
