package org.novasos.healthysv2.patient.api;
import java.time.*; import java.util.*; import jakarta.validation.constraints.*;
public final class PatientDtos {private PatientDtos(){}
 public record PatientRequest(@NotNull UUID personId,@Size(max=10) String bloodGroup,@Size(max=10) String rhesus,@Size(max=30) String maritalStatus,@Size(max=150) String occupation,@Size(max=30) String status){} public record PatientUpdateRequest(@Size(max=10) String bloodGroup,@Size(max=10) String rhesus,@Size(max=30) String maritalStatus,@Size(max=150) String occupation,@Size(max=30) String status){}
 public record IdentifierRequest(@NotBlank @Size(max=50) String type,@NotBlank @Size(max=150) String value,@Size(max=255) String issuer,UUID countryId,LocalDate expirationDate){}
 public record InsuranceRequest(@NotNull UUID insuranceCompanyId,@Size(max=100) String policyNumber,@Size(max=100) String memberNumber,LocalDate startDate,LocalDate endDate,boolean primary){@AssertTrue(message="{validation.patient.insurance-dates}") public boolean isDatesValid(){return startDate==null||endDate==null||!endDate.isBefore(startDate);}}
 public record RegistrationRequest(@NotNull UUID organizationId,@NotBlank @Size(max=100) String registrationNumber,Instant registeredAt,@Size(max=30) String status){}
 public record AllergyRequest(@NotBlank @Size(max=255) String allergen,@Size(max=80) String allergyType,String reaction,@Size(max=30) String severity,@Size(max=30) String status,Instant recordedAt,UUID recordedBy){}
 public record ChronicDiseaseRequest(UUID diagnosisCatalogId,LocalDate diagnosedAt,@Size(max=30) String status,String notes){}
 public record MedicalHistoryRequest(@NotBlank @Size(max=500) String condition,LocalDate diagnosedAt,LocalDate resolvedAt,String notes){@AssertTrue(message="{validation.patient.history-dates}")public boolean isDatesValid(){return diagnosedAt==null||resolvedAt==null||!resolvedAt.isBefore(diagnosedAt);}}
 public record SurgicalHistoryRequest(@NotBlank @Size(max=500) String procedureName,LocalDate procedureDate,UUID organizationId,String notes){} public record FamilyHistoryRequest(@Size(max=100) String relationship,@NotBlank @Size(max=500) String condition,String notes){} public record DisabilityRequest(@NotBlank @Size(max=100) String type,String description,LocalDate startDate,@Size(max=30) String status){} public record NoteRequest(UUID authorPersonId,@Size(max=50) String noteType,@NotBlank String content){} public record FlagRequest(@NotBlank @Size(max=50) String flagType,@NotBlank @Size(max=255) String label,@Size(max=30) String severity,boolean active){} public record EmergencyProfileRequest(@Size(max=100) String emergencyCode,boolean bloodGroupVisible,boolean allergiesVisible,boolean conditionsVisible,boolean medicationsVisible,boolean emergencyContactVisible,boolean active){}
 public record PatientSummary(UUID id,UUID personId,String patientNumber,String bloodGroup,String rhesus,String status){}
 public record PatientResponse(UUID id,UUID personId,String patientNumber,String bloodGroup,String rhesus,String maritalStatus,String occupation,String status,Instant createdAt,Instant updatedAt,List<IdentifierResponse> identifiers,List<InsuranceResponse> insurances,List<RegistrationResponse> registrations,List<AllergyResponse> allergies,List<ChronicDiseaseResponse> chronicDiseases,List<MedicalHistoryResponse> medicalHistories,List<SurgicalHistoryResponse> surgicalHistories,List<FamilyHistoryResponse> familyHistories,List<DisabilityResponse> disabilities,List<NoteResponse> notes,List<FlagResponse> flags,EmergencyProfileResponse emergencyProfile){}
 public record IdentifierResponse(UUID id,String type,String value,String issuer,UUID countryId,LocalDate expirationDate){} public record InsuranceResponse(UUID id,UUID insuranceCompanyId,String policyNumber,String memberNumber,LocalDate startDate,LocalDate endDate,boolean primary){} public record RegistrationResponse(UUID id,UUID organizationId,String registrationNumber,Instant registeredAt,String status){} public record AllergyResponse(UUID id,String allergen,String allergyType,String reaction,String severity,String status,Instant recordedAt,UUID recordedBy){} public record ChronicDiseaseResponse(UUID id,UUID diagnosisCatalogId,LocalDate diagnosedAt,String status,String notes){} public record MedicalHistoryResponse(UUID id,String condition,LocalDate diagnosedAt,LocalDate resolvedAt,String notes){} public record SurgicalHistoryResponse(UUID id,String procedureName,LocalDate procedureDate,UUID organizationId,String notes){} public record FamilyHistoryResponse(UUID id,String relationship,String condition,String notes){} public record DisabilityResponse(UUID id,String type,String description,LocalDate startDate,String status){} public record NoteResponse(UUID id,UUID authorPersonId,String noteType,String content,Instant createdAt){} public record FlagResponse(UUID id,String flagType,String label,String severity,boolean active,Instant createdAt){} public record EmergencyProfileResponse(UUID id,String emergencyCode,boolean bloodGroupVisible,boolean allergiesVisible,boolean conditionsVisible,boolean medicationsVisible,boolean emergencyContactVisible,boolean active){}
}
