import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import {initReactI18next} from 'react-i18next';

const resources = {
  en: {translation: {
    common: {loading: 'Loading…', save: 'Save', add: 'Add', none: 'None', cancel: 'Cancel', edit: 'Edit', create: 'Create', delete: 'Delete', actions: 'Actions', back: 'Back'},
    auth: {sessionInitializing: 'Initializing session…', keycloakInitializing: 'Initializing Keycloak…', securePortal: 'Secure portal', welcome: "Welcome to HEALTH'YS", intro: "Sign in with your HEALTH'YS account to access your health space.", login: 'Sign in', logout: 'Sign out'},
    registration: {createAccount: 'Create a patient account', creatingProfile: 'Creating your patient profile…'},
    nav: {main: 'Main navigation', home: 'Home', profile: 'My profile', organizations: 'Organizations', professionals: 'Professionals', patients:'Patients',agenda:'Agenda',pharmacy:'Pharmacy'},
    dashboard: {eyebrow: 'Dashboard', title: "Your HEALTH'YS space", description: 'The web application is connected to Keycloak and the Spring Boot API.'},
    profile: {eyebrow: 'My profile', loading: 'Loading your profile…', number: "HEALTH'YS number", status: 'Status', contacts: 'Contacts', emergencyContacts: 'Emergency contacts'},
    errors: {forbidden: 'Access denied: you do not have the required permissions.', unexpected: 'An unexpected error occurred.', sessionExpired: 'Your session is no longer valid. Please sign in again.', requestFailed: 'The request failed.'},
    organizations: {title: 'Organizations', new: 'New organization', loading: 'Loading organizations…', empty: 'No organization found.', number: 'Number', name: 'Name', legalName: 'Legal name', typeId: 'Organization type ID', phone: 'Phone', email: 'Email', website: 'Website', status: 'Status', details: 'Organization details', edit: 'Edit organization', create: 'Create organization', departments: 'Departments', services: 'Services', rooms: 'Rooms', beds: 'Beds', code: 'Code', description: 'Description', roomNumber: 'Room number', bedNumber: 'Bed number', roomType: 'Room type', addDepartment: 'Add department', addService: 'Add service', addRoom: 'Add room', addBed: 'Add bed', required: 'This field is required.', invalidEmail: 'Enter a valid email address.', invalidUrl: 'Enter a valid URL.', saved: 'Changes saved.'},
    professionals: {title:'Professionals',new:'New professional',create:'Create a professional',details:'Professional profile',search:'Search',searchPlaceholder:'Number, type or status',empty:'No professional found.',number:'Professional number',type:'Professional type',personId:'Person ID',status:'Status',licenses:'Licences',specialities:'Specialities',assignments:'Assignments',schedule:'Schedule',availabilities:'Availabilities',addLicense:'Add licence',addSpeciality:'Add speciality',addAssignment:'Add assignment',addSchedule:'Add schedule',addAvailability:'Add availability',primary:'Primary speciality',assignment:'Assignment',organizationId:'Organization',departmentId:'Department ID',serviceId:'Service ID',position:'Position',employeeNumber:'Employee number',startDate:'Start date',endDate:'End date',licenseNumber:'Licence number',issuingAuthority:'Issuing authority',issuedAt:'Issued on',expiresAt:'Expires on',specialityCatalogId:'Speciality',dayOfWeek:'Day',startTime:'Start time',endTime:'End time',slotDurationMinutes:'Slot duration (minutes)',startAt:'Start',endAt:'End',availabilityType:'Availability type'},
    patients:{eyebrow:'Patient records',title:'Patients',new:'New patient',create:'Create a patient',details:'Patient record',search:'Search',searchPlaceholder:'Patient number, status, occupation or blood group',empty:'No patient found.',personId:'Person ID',bloodGroup:'Blood group',rhesus:'Rhesus',maritalStatus:'Marital status',occupation:'Occupation',status:'Status',type:'Identifier type',value:'Identifier value',issuer:'Issuer',insuranceCompanyId:'Insurance company ID',policyNumber:'Policy number',memberNumber:'Member number',startDate:'Start date',endDate:'End date',primary:'Primary insurance',allergen:'Allergen',allergyType:'Allergy type',reaction:'Reaction',severity:'Severity',condition:'Condition',diagnosedAt:'Diagnosed on',resolvedAt:'Resolved on',notes:'Notes',diagnosisCatalogId:'Diagnosis catalogue ID',authorPersonId:'Author person ID',noteType:'Note type',content:'Content',flagType:'Flag type',label:'Label',active:'Active',organizationId:'Organization ID',registrationNumber:'Registration number',note:'Note',uncatalogued:'Uncatalogued diagnosis',tabs:{identity:'Identity',insurance:'Insurance',allergies:'Allergies',histories:'Medical history',chronicDiseases:'Chronic diseases',notes:'Notes',flags:'Alerts',establishments:'Facilities'}},
    agenda:{title:'Appointments',mine:'My agenda',management:'Appointment management',create:'Create appointment',empty:'No appointment found.',patientId:'Patient ID',professionalId:'Professional ID',organizationId:'Organization ID',departmentId:'Department ID',type:'Appointment type',scheduledStart:'Start',scheduledEnd:'End',reason:'Reason',patient:'Patient',professional:'Professional',status:'Status',cancel:'Cancel',reschedule:'Reschedule',cancelReason:'Cancelled from agenda',rescheduleReason:'Rescheduled from agenda',types:{CONSULTATION:'Consultation',FOLLOW_UP:'Follow-up',TELECONSULTATION:'Teleconsultation'}},
    pharmacy:{eyebrow:'Prescription and pharmacy',prescriptions:'Prescriptions',prescription:'Prescription',newPrescription:'New prescription',emptyPrescriptions:'No prescription found.',search:'Search',status:'Status',allStatuses:'All statuses',patientId:'Patient ID',prescriberId:'Prescriber ID',consultationId:'Consultation ID',organizationId:'Organization ID',prescribedAt:'Prescribed on',expiresAt:'Expires on',catalogSearch:'Search medication catalogue',medication:'Medication',selectMedication:'Select a medication',allMedications:'All medications',item:'Item',items:'Prescription items',addItem:'Add medication',dosage:'Dosage',frequency:'Frequency',route:'Route',duration:'Duration',quantity:'Quantity',instructions:'Instructions',remaining:'Remaining',cancelPrescription:'Cancel prescription',dispense:'Dispense prescription',selectItem:'Select an item',pharmacistId:'Pharmacist ID',quantityDispensed:'Quantity dispensed',batchNumber:'Batch number',confirmDispense:'Confirm dispense',dispenseHistory:'Dispense history',stock:'Medication stock',replenish:'Replenish stock',expirationDate:'Expiration date',expired:'Expired',emptyStock:'No stock found.',validation:'Complete all required fields with valid values.'},
    weekdays:{1:'Monday',2:'Tuesday',3:'Wednesday',4:'Thursday',5:'Friday',6:'Saturday',7:'Sunday'},
    status: {ACTIVE:'Active', INACTIVE:'Inactive', AVAILABLE:'Available', OCCUPIED:'Occupied',SCHEDULED:'Scheduled',CONFIRMED:'Confirmed',RESCHEDULED:'Rescheduled',CHECKED_IN:'Checked in',IN_PROGRESS:'In progress',COMPLETED:'Completed',CANCELLED:'Cancelled',NO_SHOW:'No-show',PARTIALLY_DISPENSED:'Partially dispensed',DISPENSED:'Dispensed'}
  }},
  fr: {translation: {
    common: {loading: 'Chargement…', save: 'Enregistrer', add: 'Ajouter', none: 'Aucun', cancel: 'Annuler', edit: 'Modifier', create: 'Créer', delete: 'Supprimer', actions: 'Actions', back: 'Retour'},
    auth: {sessionInitializing: 'Initialisation de la session…', keycloakInitializing: 'Initialisation de Keycloak…', securePortal: 'Portail sécurisé', welcome: "Bienvenue sur HEALTH'YS", intro: "Connectez-vous avec votre compte HEALTH'YS pour accéder à votre espace santé.", login: 'Se connecter', logout: 'Déconnexion'},
    registration: {createAccount: 'Créer un compte patient', creatingProfile: 'Création de votre profil patient…'},
    nav: {main: 'Navigation principale', home: 'Accueil', profile: 'Mon profil', organizations: 'Organisations', professionals: 'Professionnels', patients:'Patients',agenda:'Agenda',pharmacy:'Pharmacie'},
    dashboard: {eyebrow: 'Tableau de bord', title: "Votre espace HEALTH'YS", description: "Le socle web est connecté à Keycloak et à l'API Spring Boot."},
    profile: {eyebrow: 'Mon profil', loading: 'Chargement de votre profil…', number: "Numéro HEALTH'YS", status: 'Statut', contacts: 'Contacts', emergencyContacts: "Contacts d'urgence"},
    errors: {forbidden: "Accès refusé : vous ne disposez pas des droits nécessaires.", unexpected: 'Une erreur inattendue est survenue.', sessionExpired: "Votre session n'est plus valide. Veuillez vous reconnecter.", requestFailed: 'La requête a échoué.'},
    organizations: {title: 'Organisations', new: 'Nouvelle organisation', loading: 'Chargement des organisations…', empty: 'Aucune organisation trouvée.', number: 'Numéro', name: 'Nom', legalName: 'Raison sociale', typeId: "ID du type d'organisation", phone: 'Téléphone', email: 'Courriel', website: 'Site web', status: 'Statut', details: "Fiche de l'organisation", edit: "Modifier l'organisation", create: 'Créer une organisation', departments: 'Départements', services: 'Services', rooms: 'Chambres', beds: 'Lits', code: 'Code', description: 'Description', roomNumber: 'Numéro de chambre', bedNumber: 'Numéro du lit', roomType: 'Type de chambre', addDepartment: 'Ajouter un département', addService: 'Ajouter un service', addRoom: 'Ajouter une chambre', addBed: 'Ajouter un lit', required: 'Ce champ est obligatoire.', invalidEmail: 'Saisissez un courriel valide.', invalidUrl: 'Saisissez une URL valide.', saved: 'Modifications enregistrées.'},
    professionals: {title:'Professionnels',new:'Nouveau professionnel',create:'Créer un professionnel',details:'Fiche professionnelle',search:'Rechercher',searchPlaceholder:'Numéro, type ou statut',empty:'Aucun professionnel trouvé.',number:'Numéro professionnel',type:'Type de professionnel',personId:'ID de la personne',status:'Statut',licenses:'Licences',specialities:'Spécialités',assignments:'Affectations',schedule:'Planning',availabilities:'Disponibilités',addLicense:'Ajouter une licence',addSpeciality:'Ajouter une spécialité',addAssignment:'Ajouter une affectation',addSchedule:'Ajouter une plage au planning',addAvailability:'Ajouter une disponibilité',primary:'Spécialité principale',assignment:'Affectation',organizationId:'Établissement',departmentId:'ID du département',serviceId:'ID du service',position:'Poste',employeeNumber:'Matricule employé',startDate:'Date de début',endDate:'Date de fin',licenseNumber:'Numéro de licence',issuingAuthority:'Autorité émettrice',issuedAt:'Date d’émission',expiresAt:'Date d’expiration',specialityCatalogId:'Spécialité',dayOfWeek:'Jour',startTime:'Heure de début',endTime:'Heure de fin',slotDurationMinutes:'Durée du créneau (minutes)',startAt:'Début',endAt:'Fin',availabilityType:'Type de disponibilité'},
    patients:{eyebrow:'Dossiers patients',title:'Patients',new:'Nouveau patient',create:'Créer un patient',details:'Fiche patient',search:'Rechercher',searchPlaceholder:'Numéro patient, statut, profession ou groupe sanguin',empty:'Aucun patient trouvé.',personId:'ID de la personne',bloodGroup:'Groupe sanguin',rhesus:'Rhésus',maritalStatus:'Situation matrimoniale',occupation:'Profession',status:'Statut',type:"Type d'identifiant",value:"Valeur de l'identifiant",issuer:'Émetteur',insuranceCompanyId:"ID de l'assurance",policyNumber:'Numéro de police',memberNumber:"Numéro d'adhérent",startDate:'Date de début',endDate:'Date de fin',primary:'Assurance principale',allergen:'Allergène',allergyType:"Type d'allergie",reaction:'Réaction',severity:'Sévérité',condition:'Affection',diagnosedAt:'Diagnostiquée le',resolvedAt:'Résolue le',notes:'Notes',diagnosisCatalogId:'ID du diagnostic catalogue',authorPersonId:"ID de l'auteur",noteType:'Type de note',content:'Contenu',flagType:"Type d'alerte",label:'Libellé',active:'Active',organizationId:"ID de l'établissement",registrationNumber:"Numéro d'inscription",note:'Note',uncatalogued:'Diagnostic non catalogué',tabs:{identity:'Identité',insurance:'Assurance',allergies:'Allergies',histories:'Antécédents',chronicDiseases:'Maladies chroniques',notes:'Notes',flags:'Alertes',establishments:'Établissements'}},
    agenda:{title:'Rendez-vous',mine:'Mon agenda',management:'Gestion des rendez-vous',create:'Créer le rendez-vous',empty:'Aucun rendez-vous trouvé.',patientId:'ID du patient',professionalId:'ID du professionnel',organizationId:"ID de l’établissement",departmentId:'ID du département',type:'Type de rendez-vous',scheduledStart:'Début',scheduledEnd:'Fin',reason:'Motif',patient:'Patient',professional:'Professionnel',status:'Statut',cancel:'Annuler',reschedule:'Replanifier',cancelReason:"Annulé depuis l’agenda",rescheduleReason:"Replanifié depuis l’agenda",types:{CONSULTATION:'Consultation',FOLLOW_UP:'Suivi',TELECONSULTATION:'Téléconsultation'}},
    pharmacy:{eyebrow:'Prescription et pharmacie',prescriptions:'Ordonnances',prescription:'Ordonnance',newPrescription:'Nouvelle ordonnance',emptyPrescriptions:'Aucune ordonnance trouvée.',search:'Rechercher',status:'Statut',allStatuses:'Tous les statuts',patientId:'ID du patient',prescriberId:'ID du prescripteur',consultationId:'ID de la consultation',organizationId:"ID de l’établissement",prescribedAt:'Prescrite le',expiresAt:'Expire le',catalogSearch:'Rechercher dans le catalogue',medication:'Médicament',selectMedication:'Sélectionner un médicament',allMedications:'Tous les médicaments',item:'Ligne',items:"Lignes de l’ordonnance",addItem:'Ajouter un médicament',dosage:'Dosage',frequency:'Fréquence',route:"Voie d’administration",duration:'Durée',quantity:'Quantité',instructions:'Instructions',remaining:'Restant',cancelPrescription:"Annuler l’ordonnance",dispense:"Dispenser l’ordonnance",selectItem:'Sélectionner une ligne',pharmacistId:'ID du pharmacien',quantityDispensed:'Quantité dispensée',batchNumber:'Numéro de lot',confirmDispense:'Confirmer la dispensation',dispenseHistory:'Historique des dispensations',stock:'Stock de médicaments',replenish:'Réapprovisionner',expirationDate:"Date d’expiration",expired:'Expiré',emptyStock:'Aucun stock trouvé.',validation:'Complétez tous les champs obligatoires avec des valeurs valides.'},
    weekdays:{1:'Lundi',2:'Mardi',3:'Mercredi',4:'Jeudi',5:'Vendredi',6:'Samedi',7:'Dimanche'},
    status: {ACTIVE:'Actif', INACTIVE:'Inactif', AVAILABLE:'Disponible', OCCUPIED:'Occupé',SCHEDULED:'Planifié',CONFIRMED:'Confirmé',RESCHEDULED:'Replanifié',CHECKED_IN:'Enregistré',IN_PROGRESS:'En cours',COMPLETED:'Terminé',CANCELLED:'Annulé',NO_SHOW:'Absent',PARTIALLY_DISPENSED:'Partiellement dispensée',DISPENSED:'Dispensée'}
  }},
} as const;

void i18n.use(LanguageDetector).use(initReactI18next).init({
  resources,
  supportedLngs: ['en', 'fr'],
  fallbackLng: 'en',
  interpolation: {escapeValue: false},
  detection: {order: ['navigator'], caches: []},
});

export default i18n;
