package org.novasos.healthysv2.consultation.api;
import java.math.*;import java.time.*;import java.util.*;import jakarta.validation.constraints.*;
public final class ConsultationDtos{private ConsultationDtos(){}
 public record StartConsultationRequest(@NotNull UUID patientId,@NotNull UUID professionalId,@NotNull UUID organizationId,UUID appointmentId,UUID encounterId,@NotBlank @Size(max=50)String type,String reason){}
 public record VitalSignRequest(@DecimalMin("30.0")@DecimalMax("45.0")BigDecimal temperature,@DecimalMin("0.1")@DecimalMax("500.0")BigDecimal weight,@DecimalMin("20.0")@DecimalMax("300.0")BigDecimal height,@Min(40)@Max(300)Integer systolicPressure,@Min(20)@Max(200)Integer diastolicPressure,@Min(20)@Max(300)Integer heartRate,@Min(5)@Max(100)Integer respiratoryRate,@DecimalMin("50.0")@DecimalMax("100.0")BigDecimal oxygenSaturation,Instant measuredAt,UUID measuredBy,@AssertTrue(message="{validation.consultation.vital-sign}")Boolean atLeastOne){public VitalSignRequest{atLeastOne=temperature!=null||weight!=null||height!=null||systolicPressure!=null||diastolicPressure!=null||heartRate!=null||respiratoryRate!=null||oxygenSaturation!=null;}}
 public record DiagnosisRequest(UUID diagnosisCatalogId,@NotBlank @Size(max=50)String diagnosisType,String description,@Size(max=30)String status,@AssertTrue(message="{validation.consultation.diagnosis}")Boolean diagnosisDefined){public DiagnosisRequest{diagnosisDefined=diagnosisCatalogId!=null||(description!=null&&!description.isBlank());}}
 public record NoteRequest(@NotNull UUID authorProfessionalId,@NotBlank @Size(max=50)String noteType,@NotBlank String content){}
 public record ObservationRequest(UUID authorProfessionalId,@NotBlank @Size(max=100)String type,String value,String notes,Instant observedAt,@AssertTrue(message="{validation.consultation.observation}")Boolean contentDefined){public ObservationRequest{contentDefined=(value!=null&&!value.isBlank())||(notes!=null&&!notes.isBlank());}}
 public record TreatmentRequest(@NotBlank String description,LocalDate startDate,LocalDate endDate,@Size(max=30)String status,@AssertTrue(message="{validation.consultation.treatment-dates}")Boolean datesValid){public TreatmentRequest{datesValid=startDate==null||endDate==null||!endDate.isBefore(startDate);}}
 public record FollowUpRequest(LocalDate recommendedDate,@NotBlank String instructions,@Size(max=30)String status){}
 public record VitalSignResponse(UUID id,BigDecimal temperature,BigDecimal weight,BigDecimal height,BigDecimal bmi,Integer systolicPressure,Integer diastolicPressure,Integer heartRate,Integer respiratoryRate,BigDecimal oxygenSaturation,Instant measuredAt,UUID measuredBy){}
 public record DiagnosisResponse(UUID id,UUID diagnosisCatalogId,String catalogCode,String catalogLabel,String diagnosisType,String description,String status,Instant diagnosedAt){}
 public record NoteResponse(UUID id,UUID authorProfessionalId,String noteType,String content,Instant createdAt,Instant updatedAt){}
 public record ObservationResponse(UUID id,UUID authorProfessionalId,String type,String value,String notes,Instant observedAt){}
 public record TreatmentResponse(UUID id,String description,LocalDate startDate,LocalDate endDate,String status){}
 public record FollowUpResponse(UUID id,LocalDate recommendedDate,String instructions,String status){}
 public record ConsultationResponse(UUID id,String consultationNumber,UUID patientId,UUID professionalId,UUID organizationId,UUID appointmentId,UUID encounterId,String type,String reason,Instant startedAt,Instant completedAt,String status,Instant createdAt,Instant updatedAt,long version,List<VitalSignResponse>vitalSigns,List<DiagnosisResponse>diagnoses,List<NoteResponse>notes,List<ObservationResponse>observations,List<TreatmentResponse>treatments,List<FollowUpResponse>followUps){}
 public record PatientSummary(UUID patientId,String patientNumber,String firstName,String lastName,LocalDate birthDate,String gender,String bloodGroup,String rhesus,String status,List<String>activeAllergies,List<String>activeChronicDiseases,List<String>activeFlags){}
 public record DiagnosisCatalogResponse(UUID id,String code,String system,String label){}
}
