package org.novasos.healthysv2.messaging;
import static org.assertj.core.api.Assertions.*;import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;import org.novasos.healthysv2.TestcontainersConfiguration;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.context.annotation.Import;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;import org.springframework.test.context.ActiveProfiles;import org.springframework.transaction.annotation.Transactional;
@ActiveProfiles("test")@Import(TestcontainersConfiguration.class)@SpringBootTest@Transactional class ConversationRepositoryIntegrationTests{@Autowired JdbcTemplate jdbc;@Autowired ConversationService service;
 @Test void storesConversationParticipantsMessagesAndReceipts(){UUID first=person(),second=person(),conversation=UUID.randomUUID(),message=UUID.randomUUID();jdbc.update("insert into communication.conversation(id,conversation_number,type,subject,created_by) values (?,?, 'DIRECT','Follow-up',?)",conversation,"CONV-TEST",first);jdbc.update("insert into communication.conversation_participant(conversation_id,person_id) values (?,?),(?,?)",conversation,first,conversation,second);jdbc.update("insert into communication.message(id,conversation_id,sender_person_id,type,content) values (?,?,?,'TEXT','Hello')",message,conversation,first);jdbc.update("insert into communication.message_receipt(message_id,person_id,delivered_at) values (?,?,now())",message,second);assertThat(jdbc.queryForObject("select count(*) from communication.message where conversation_id=?",Integer.class,conversation)).isEqualTo(1);}
 @Test void rejectsInvalidConversationType(){UUID person=person();assertThatThrownBy(()->jdbc.update("insert into communication.conversation(conversation_number,type,created_by) values ('BAD-CONV','INVALID',?)",person)).isInstanceOf(DataIntegrityViolationException.class);}
 @Test void rejectsTextMessageWithoutContent(){UUID person=person(),conversation=UUID.randomUUID();jdbc.update("insert into communication.conversation(id,conversation_number,type,created_by) values (?,?,'DIRECT',?)",conversation,"CONV-EMPTY",person);assertThatThrownBy(()->jdbc.update("insert into communication.message(conversation_id,sender_person_id,type) values (?,?,'TEXT')",conversation,person)).isInstanceOf(DataIntegrityViolationException.class);}
 @Test void websocketSubscriptionRequiresAnActiveParticipant(){UUID member=person(),outsider=person(),conversation=UUID.randomUUID();jdbc.update("insert into communication.conversation(id,conversation_number,type,created_by) values (?,?,'DIRECT',?)",conversation,"CONV-WS",member);jdbc.update("insert into communication.conversation_participant(conversation_id,person_id) values (?,?)",conversation,member);assertThat(service.maySubscribe(authentication(member),conversation)).isTrue();assertThat(service.maySubscribe(authentication(outsider),conversation)).isFalse();}
 private JwtAuthenticationToken authentication(UUID subject){Instant now=Instant.now();return new JwtAuthenticationToken(Jwt.withTokenValue("test").header("alg","none").subject(subject.toString()).issuedAt(now).expiresAt(now.plusSeconds(60)).build());}
 private UUID person(){UUID id=UUID.randomUUID();jdbc.update("insert into identity.person(id,person_number,first_name,last_name,status) values (?,?,?,?,?)",id,"PER-"+id,"Chat","User","ACTIVE");return id;}}
