package org.novasos.healthysv2.messaging;
import static org.assertj.core.api.Assertions.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import com.fasterxml.jackson.databind.*;import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;import org.novasos.healthysv2.TestcontainersConfiguration;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.*;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.context.annotation.*;import org.springframework.http.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.oauth2.jwt.*;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.MockMvc;import org.springframework.transaction.annotation.Transactional;
@ActiveProfiles("test")@SpringBootTest(properties={"spring.security.oauth2.resourceserver.jwt.issuer-uri=https://keycloak.example/realms/healthys","healthys.security.api-client-id=healthys-backend-apps","healthys.security.cors.allowed-origins=http://localhost:5173"})@AutoConfigureMockMvc@Import({TestcontainersConfiguration.class,ConversationApiIntegrationTests.JwtFixtures.class})@Transactional class ConversationApiIntegrationTests{
 @Autowired MockMvc mvc;@Autowired JdbcTemplate jdbc;private final ObjectMapper json=new ObjectMapper().findAndRegisterModules();
 @Test void createsConversationSendsMessageAndMarksItRead()throws Exception{Graph graph=graph();String conversationBody=mvc.perform(post("/api/v1/conversations").header(HttpHeaders.AUTHORIZATION,"Bearer actor").contentType(MediaType.APPLICATION_JSON).content("{\"type\":\"DIRECT\",\"subject\":\"Care follow-up\",\"participantPersonIds\":[\"%s\"]}".formatted(graph.other))).andExpect(status().isCreated()).andExpect(jsonPath("$.participants.length()").value(2)).andReturn().getResponse().getContentAsString();UUID conversation=UUID.fromString(json.readTree(conversationBody).path("id").asText());String messageBody=mvc.perform(post("/api/v1/conversations/{id}/messages",conversation).header(HttpHeaders.AUTHORIZATION,"Bearer actor").contentType(MediaType.APPLICATION_JSON).content("{\"type\":\"TEXT\",\"content\":\"Your results are available\"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.content").value("Your results are available")).andReturn().getResponse().getContentAsString();UUID message=UUID.fromString(json.readTree(messageBody).path("id").asText());mvc.perform(get("/api/v1/conversations").header(HttpHeaders.AUTHORIZATION,"Bearer actor")).andExpect(status().isOk()).andExpect(jsonPath("$.content[0].id").value(conversation.toString()));mvc.perform(post("/api/v1/conversations/messages/{id}/read",message).header(HttpHeaders.AUTHORIZATION,"Bearer other")).andExpect(status().isOk()).andExpect(jsonPath("$.personId").value(graph.other.toString()));assertThat(jdbc.queryForObject("select count(*) from audit.audit_log where module='MESSAGING' and entity_id=?",Integer.class,conversation)).isEqualTo(2);}
 @Test void preventsNonParticipantFromReadingConversation()throws Exception{Graph graph=graph();UUID outsider=person("outsider");String body=mvc.perform(post("/api/v1/conversations").header(HttpHeaders.AUTHORIZATION,"Bearer actor").contentType(MediaType.APPLICATION_JSON).content("{\"type\":\"DIRECT\",\"participantPersonIds\":[\"%s\"]}".formatted(graph.other))).andReturn().getResponse().getContentAsString();UUID conversation=UUID.fromString(json.readTree(body).path("id").asText());mvc.perform(get("/api/v1/conversations/{id}",conversation).header(HttpHeaders.AUTHORIZATION,"Bearer outsider")).andExpect(status().isForbidden());assertThat(outsider).isNotNull();}
 private Graph graph(){return new Graph(person("actor"),person("other"));}private UUID person(String token){UUID id=UUID.randomUUID();jdbc.update("insert into identity.person(id,keycloak_user_id,person_number,first_name,last_name,status) values (?,?,?,?,?,?)",id,id,"PER-"+id,token,"User","ACTIVE");JwtFixtures.SUBJECTS.put(token,id);return id;}record Graph(UUID actor,UUID other){}
 @TestConfiguration(proxyBeanMethods=false)static class JwtFixtures{static final Map<String,UUID>SUBJECTS=new HashMap<>();@Bean JwtDecoder jwtDecoder(){return token->{UUID subject=SUBJECTS.getOrDefault(token,UUID.randomUUID());Instant now=Instant.now();return Jwt.withTokenValue(token).header("alg","RS256").subject(subject.toString()).issuer("https://keycloak.example/realms/healthys").issuedAt(now).expiresAt(now.plusSeconds(300)).claim("realm_access",Map.of("roles",List.of("PLATFORM_ADMIN"))).claim("resource_access",Map.of()).build();};}}
}
