package org.novasos.healthysv2.appointment.api;
import java.time.Instant;import java.util.*;import jakarta.validation.constraints.*;
public final class AppointmentDtos{private AppointmentDtos(){}
 public record AppointmentRequest(@NotNull UUID patientId,@NotNull UUID professionalId,@NotNull UUID organizationId,UUID departmentId,@NotBlank @Size(max=50)String type,@NotNull Instant scheduledStart,@NotNull Instant scheduledEnd,String reason,@AssertTrue(message="{validation.appointment.times}")Boolean timesValid){public AppointmentRequest{timesValid=scheduledStart==null||scheduledEnd==null||scheduledEnd.isAfter(scheduledStart);}}
 public record AppointmentUpdateRequest(UUID departmentId,@NotBlank @Size(max=50)String type,@NotNull Instant scheduledStart,@NotNull Instant scheduledEnd,String reason,@AssertTrue(message="{validation.appointment.times}")Boolean timesValid){public AppointmentUpdateRequest{timesValid=scheduledStart==null||scheduledEnd==null||scheduledEnd.isAfter(scheduledStart);}}
 public record RescheduleRequest(@NotNull Instant scheduledStart,@NotNull Instant scheduledEnd,String reason,@AssertTrue(message="{validation.appointment.times}")Boolean timesValid){public RescheduleRequest{timesValid=scheduledStart==null||scheduledEnd==null||scheduledEnd.isAfter(scheduledStart);}}
 public record CancelRequest(String reason){}public record StatusRequest(@NotBlank String status,String reason){}public record ParticipantRequest(@NotNull UUID personId,@NotBlank @Size(max=50)String role){}public record ParticipantStatusRequest(@NotBlank String status){}
 public record AppointmentSummary(UUID id,String appointmentNumber,UUID patientId,UUID professionalId,UUID organizationId,String type,Instant scheduledStart,Instant scheduledEnd,String status){}
 public record AppointmentResponse(UUID id,String appointmentNumber,UUID patientId,UUID professionalId,UUID organizationId,UUID departmentId,String type,Instant scheduledStart,Instant scheduledEnd,String reason,String status,UUID createdBy,Instant createdAt,Instant updatedAt,long version,List<ParticipantResponse>participants,List<StatusHistoryResponse>history,List<QueueResponse>queue){}
 public record ParticipantResponse(UUID id,UUID personId,String role,String status){}public record StatusHistoryResponse(UUID id,String previousStatus,String newStatus,UUID changedBy,Instant changedAt,String reason){}public record QueueResponse(UUID id,UUID organizationId,String queueNumber,Instant checkedInAt,Instant calledAt,Instant completedAt,String status){}public record AvailabilityResponse(UUID professionalId,UUID organizationId,Instant start,Instant end,boolean available,String reason){}
}
