package org.novasos.healthysv2.teleconsultation;

import static org.novasos.healthysv2.teleconsultation.api.TeleconsultationDtos.*;
import java.time.*;import java.util.*;
import org.novasos.healthysv2.patient.CurrentUserContext;import org.novasos.healthysv2.shared.api.error.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.AccessDeniedException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service @Transactional
class TeleconsultationService {
    private final JdbcTemplate jdbc;private final VideoSessionRepository repository;private final CurrentUserContext users;private final LiveKitTokenService tokens;
    TeleconsultationService(JdbcTemplate jdbc,VideoSessionRepository repository,CurrentUserContext users,LiveKitTokenService tokens){this.jdbc=jdbc;this.repository=repository;this.users=users;this.tokens=tokens;}
    VideoSessionResponse create(CreateVideoSessionRequest request){var user=requirePerson();Source source=request.appointmentId()!=null?appointment(request.appointmentId()):consultation(request.consultationId());boolean organizationAdmin=user.has("HOSPITAL_ADMIN")&&Objects.equals(user.organizationId(),source.organizationId());if(!user.has("PLATFORM_ADMIN")&&!organizationAdmin&&!Objects.equals(user.personId(),source.professionalPerson()))throw new AccessDeniedException("Only the assigned professional can create the session");UUID id=UUID.randomUUID();String number="TEL-"+compact(id),room="healthys-"+id;Instant scheduled=request.scheduledStart()!=null?request.scheduledStart():source.scheduled();jdbc.update("insert into teleconsultation.video_session(id,session_number,appointment_id,consultation_id,provider,external_room_id,scheduled_start,status) values (?,?,?,?, 'LIVEKIT',?,?,'SCHEDULED')",id,number,request.appointmentId(),request.consultationId(),room,java.sql.Timestamp.from(scheduled));participant(id,source.patientPerson(),"PATIENT");participant(id,source.professionalPerson(),"PROFESSIONAL");audit(user,id,"CREATE");return response(session(id));}
    List<VideoSessionResponse> list(){var user=requirePerson();UUID adminOrganization=user.has("HOSPITAL_ADMIN")?user.organizationId():null;return repository.list(user.personId(),user.has("PLATFORM_ADMIN"),adminOrganization).stream().map(this::response).toList();}
    @Transactional(readOnly=true) VideoSessionResponse find(UUID id){var session=session(id);requireParticipantOrAdmin(id);return response(session);}
    WaitingRoomResponse enter(UUID id){var user=requirePerson();var session=session(id);if(!"PATIENT".equals(repository.role(id,user.personId())))throw new AccessDeniedException("Only the patient can enter the waiting room");UUID patient=jdbc.query("select p.id from patient.patient p where p.person_id=?",rs->rs.next()?(UUID)rs.getObject(1):null,user.personId());if(patient==null)throw new AccessDeniedException("Patient profile missing");jdbc.update("insert into teleconsultation.waiting_room(id,video_session_id,patient_id,status) values (?,?,?,'WAITING') on conflict(video_session_id,patient_id) do update set entered_at=now(),admitted_at=null,status='WAITING'",UUID.randomUUID(),id,patient);if("SCHEDULED".equals(session.status()))jdbc.update("update teleconsultation.video_session set status='WAITING' where id=?",id);audit(user,id,"ENTER_WAITING_ROOM");return repository.waiting(id).stream().filter(w->w.patientId().equals(patient)).findFirst().orElseThrow();}
    WaitingRoomResponse admit(UUID id,UUID entry){var user=requireClinical(id);int changed=jdbc.update("update teleconsultation.waiting_room set status='ADMITTED',admitted_at=now() where id=? and video_session_id=? and status='WAITING'",entry,id);if(changed==0)throw new BusinessRuleException("WAITING_ENTRY_NOT_AVAILABLE","error.teleconsultation.waiting-entry");audit(user,id,"ADMIT_PATIENT");return repository.waiting(id).stream().filter(w->w.id().equals(entry)).findFirst().orElseThrow(()->new ResourceNotFoundException("waiting-room",entry));}
    JoinTokenResponse token(UUID id){var user=requirePerson();var session=session(id);if(!repository.participant(id,user.personId())&&!user.has("PLATFORM_ADMIN"))throw new AccessDeniedException("Not a session participant");String role=repository.role(id,user.personId());if("PATIENT".equals(role)&&!Boolean.TRUE.equals(jdbc.queryForObject("select exists(select 1 from teleconsultation.waiting_room w join patient.patient p on p.id=w.patient_id where w.video_session_id=? and p.person_id=? and w.status='ADMITTED')",Boolean.class,id,user.personId())))throw new AccessDeniedException("Patient has not been admitted");if(Set.of("COMPLETED","CANCELLED").contains(session.status()))throw new BusinessRuleException("VIDEO_SESSION_CLOSED","error.teleconsultation.closed");jdbc.update("update teleconsultation.video_participant set joined_at=coalesce(joined_at,now()),left_at=null where video_session_id=? and person_id=?",id,user.personId());audit(user,id,"ISSUE_JOIN_TOKEN");return tokens.create(user.personId(),session.room(),role==null?"HOST":role);}
    VideoSessionResponse start(UUID id){var user=requireClinical(id);var session=session(id);if(!Set.of("SCHEDULED","WAITING").contains(session.status()))throw new BusinessRuleException("VIDEO_SESSION_NOT_STARTABLE","error.teleconsultation.not-startable");jdbc.update("update teleconsultation.video_session set status='ACTIVE',started_at=coalesce(started_at,now()) where id=?",id);audit(user,id,"START");return response(session(id));}
    VideoSessionResponse complete(UUID id){var user=requireClinical(id);if(!"ACTIVE".equals(session(id).status()))throw new BusinessRuleException("VIDEO_SESSION_NOT_ACTIVE","error.teleconsultation.not-active");jdbc.update("update teleconsultation.video_session set status='COMPLETED',ended_at=now() where id=?",id);jdbc.update("update teleconsultation.video_participant set left_at=coalesce(left_at,now()) where video_session_id=? and joined_at is not null",id);audit(user,id,"COMPLETE");return response(session(id));}
    void leave(UUID id){var user=requirePerson();if(!repository.participant(id,user.personId()))throw new AccessDeniedException("Not a session participant");jdbc.update("update teleconsultation.video_participant set left_at=now() where video_session_id=? and person_id=?",id,user.personId());audit(user,id,"LEAVE");}
    private CurrentUserContext.UserContext requireClinical(UUID id){var user=requirePerson();if(!user.hasAny("PLATFORM_ADMIN","HOSPITAL_ADMIN","DOCTOR","NURSE"))throw new AccessDeniedException("Clinical role required");boolean admin=user.has("PLATFORM_ADMIN")||(user.has("HOSPITAL_ADMIN")&&repository.organization(id,user.organizationId()));if(!admin&&!repository.participant(id,user.personId()))throw new AccessDeniedException("Not a session participant");return user;}
    private void requireParticipantOrAdmin(UUID id){var user=requirePerson();boolean admin=user.has("PLATFORM_ADMIN")||(user.has("HOSPITAL_ADMIN")&&repository.organization(id,user.organizationId()));if(!admin&&!repository.participant(id,user.personId()))throw new AccessDeniedException("Not a session participant");}
    private CurrentUserContext.UserContext requirePerson(){var user=users.current();if(user.personId()==null)throw new AccessDeniedException("Person context missing");return user;}
    private VideoSessionRepository.Session session(UUID id){return repository.find(id).orElseThrow(()->new ResourceNotFoundException("video-session",id));}
    private VideoSessionResponse response(VideoSessionRepository.Session s){return new VideoSessionResponse(s.id(),s.number(),s.appointmentId(),s.consultationId(),s.room(),s.scheduled(),s.started(),s.ended(),s.status(),repository.participants(s.id()),repository.waiting(s.id()));}
    private void participant(UUID session,UUID person,String role){if(person!=null)jdbc.update("insert into teleconsultation.video_participant(video_session_id,person_id,role) values (?,?,?) on conflict do nothing",session,person,role);}
    private Source appointment(UUID id){Source value=jdbc.query("select a.patient_id,pat.person_id,pro.person_id,a.organization_id,a.scheduled_start from appointment.appointment a join patient.patient pat on pat.id=a.patient_id join professional.professional pro on pro.id=a.professional_id where a.id=?",rs->rs.next()?new Source((UUID)rs.getObject(1),(UUID)rs.getObject(2),(UUID)rs.getObject(3),(UUID)rs.getObject(4),rs.getTimestamp(5).toInstant()):null,id);return value==null?missing("appointment",id):value;}
    private Source consultation(UUID id){Source value=jdbc.query("select c.patient_id,pat.person_id,pro.person_id,c.organization_id,c.started_at from consultation.consultation c join patient.patient pat on pat.id=c.patient_id join professional.professional pro on pro.id=c.professional_id where c.id=?",rs->rs.next()?new Source((UUID)rs.getObject(1),(UUID)rs.getObject(2),(UUID)rs.getObject(3),(UUID)rs.getObject(4),rs.getTimestamp(5).toInstant()):null,id);return value==null?missing("consultation",id):value;}
    private Source missing(String resource,UUID id){throw new ResourceNotFoundException(resource,id);}private String compact(UUID id){return id.toString().replace("-","").substring(0,20).toUpperCase();}
    private void audit(CurrentUserContext.UserContext user,UUID id,String action){jdbc.update("insert into audit.audit_log(actor_person_id,organization_id,module,entity_type,entity_id,action) values (?,?, 'TELECONSULTATION','VIDEO_SESSION',?,?)",user.personId(),user.organizationId(),id,action);}
    private record Source(UUID patientId,UUID patientPerson,UUID professionalPerson,UUID organizationId,Instant scheduled){}
}
