package org.novasos.healthysv2.laboratory;
import jakarta.persistence.*;import java.time.*;import java.util.*;
@Entity @Table(name="lab_order",schema="laboratory") class LabOrder{
 @Id private UUID id;@Column(name="order_number",nullable=false,unique=true,length=50)private String number;@Column(name="patient_id",nullable=false)private UUID patientId;@Column(name="consultation_id")private UUID consultationId;@Column(name="ordering_professional_id",nullable=false)private UUID orderingProfessionalId;@Column(name="laboratory_organization_id")private UUID laboratoryOrganizationId;@Column(nullable=false,length=30)private String priority;@Column(name="ordered_at",nullable=false)private Instant orderedAt;@Column(nullable=false,length=30)private String status;
 @OneToMany(mappedBy="order",cascade=CascadeType.ALL,orphanRemoval=true)private List<LabOrderItem>items=new ArrayList<>();@OneToMany(mappedBy="order",cascade=CascadeType.ALL,orphanRemoval=true)private List<LabResult>results=new ArrayList<>();
 protected LabOrder(){}static LabOrder create(UUID patient,UUID consultation,UUID professional,UUID organization,String priority){var x=new LabOrder();x.id=UUID.randomUUID();x.number="LAB-"+x.id.toString().replace("-","").substring(0,20).toUpperCase();x.patientId=Objects.requireNonNull(patient);x.consultationId=consultation;x.orderingProfessionalId=Objects.requireNonNull(professional);x.laboratoryOrganizationId=organization;x.priority=required(priority).toUpperCase();x.orderedAt=Instant.now();x.status="ORDERED";return x;}
 LabOrderItem addItem(UUID exam,String instructions){ensureMutable();if(items.stream().anyMatch(i->i.getExamCatalogId().equals(exam)))throw new IllegalArgumentException("Duplicate exam");var item=LabOrderItem.create(this,exam,instructions);items.add(item);return item;}
 Specimen collect(UUID itemId,String number,String type,Instant at,UUID by){ensureMutable();var specimen=item(itemId).collect(number,type,at,by);status="IN_PROGRESS";return specimen;}
 void receive(UUID specimenId){specimen(specimenId).receive();}void reject(UUID specimenId){specimen(specimenId).reject();}
 LabResult createResult(UUID performedBy,Instant performedAt,String notes){ensureMutable();if(items.isEmpty()||items.stream().anyMatch(i->!i.hasUsableSpecimen()))throw new IllegalStateException("Specimens are incomplete");var result=LabResult.create(this,performedBy,performedAt,notes);results.add(result);return result;}
 void validateResult(UUID resultId,UUID validator){var result=result(resultId);result.validate(validator,items);status="COMPLETED";items.forEach(LabOrderItem::complete);}
 void cancel(){if("COMPLETED".equals(status)||"CANCELLED".equals(status))throw new IllegalStateException("Order cannot be cancelled");status="CANCELLED";items.forEach(LabOrderItem::cancel);}
 private void ensureMutable(){if(Set.of("COMPLETED","CANCELLED").contains(status))throw new IllegalStateException("Order is closed");}LabOrderItem item(UUID id){return items.stream().filter(i->i.getId().equals(id)).findFirst().orElseThrow(NoSuchElementException::new);}private Specimen specimen(UUID id){return items.stream().flatMap(i->i.getSpecimens().stream()).filter(s->s.getId().equals(id)).findFirst().orElseThrow(NoSuchElementException::new);}private LabResult result(UUID id){return results.stream().filter(r->r.getId().equals(id)).findFirst().orElseThrow(NoSuchElementException::new);}private static String required(String v){if(v==null||v.isBlank())throw new IllegalArgumentException("Required value");return v.trim();}
 UUID getId(){return id;}String getNumber(){return number;}UUID getPatientId(){return patientId;}UUID getConsultationId(){return consultationId;}UUID getOrderingProfessionalId(){return orderingProfessionalId;}UUID getLaboratoryOrganizationId(){return laboratoryOrganizationId;}String getPriority(){return priority;}Instant getOrderedAt(){return orderedAt;}String getStatus(){return status;}List<LabOrderItem>getItems(){return items;}List<LabResult>getResults(){return results;}
}
