package org.novasos.healthysv2.laboratory;
import static org.novasos.healthysv2.laboratory.api.LaboratoryDtos.*;import java.time.*;import java.util.*;import org.novasos.healthysv2.patient.PatientAccessService;import org.novasos.healthysv2.shared.api.dto.PageResponse;import org.novasos.healthysv2.shared.api.error.*;import org.springframework.data.domain.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @Transactional class LaboratoryService{
 private static final Set<String>PRIORITIES=Set.of("ROUTINE","URGENT","STAT");private final LabOrderRepository repository;private final JdbcTemplate jdbc;private final PatientAccessService access;LaboratoryService(LabOrderRepository repository,JdbcTemplate jdbc,PatientAccessService access){this.repository=repository;this.jdbc=jdbc;this.access=access;}
 LabOrderResponse create(CreateOrderRequest r){access.requireAccess(r.patientId(),"LAB_RESULTS","WRITE");validateOrder(r);var order=LabOrder.create(r.patientId(),r.consultationId(),r.orderingProfessionalId(),r.laboratoryOrganizationId(),r.priority());for(var item:r.items())order.addItem(item.labExamCatalogId(),item.instructions());repository.saveAndFlush(order);audit(order,"CREATE_ORDER");return response(order);}
 LabOrderItemResponse addItem(UUID id,OrderItemRequest r){var order=write(id);requireExam(r.labExamCatalogId());try{var item=order.addItem(r.labExamCatalogId(),r.instructions());repository.flush();audit(order,"ADD_ORDER_ITEM");return item(item);}catch(IllegalArgumentException e){throw new ConflictException("LAB_EXAM_ALREADY_ORDERED","error.laboratory.exam-exists");}}
 @Transactional(readOnly=true)LabOrderResponse find(UUID id){var o=get(id);access.requireAccess(o.getPatientId(),"LAB_RESULTS","READ");return response(o);}
 @Transactional(readOnly=true)PageResponse<OrderSummary>search(UUID patient,UUID organization,String status,Pageable pageable){if(patient!=null)access.requireAccess(patient,"LAB_RESULTS","READ");return PageResponse.from(repository.search(patient,organization,normalize(status),pageable).map(this::summary));}
 SpecimenResponse collect(UUID orderId,UUID itemId,CollectSpecimenRequest r){var order=write(orderId);requireProfessional(r.collectedBy());if(exists("select count(*) from laboratory.specimen where specimen_number=?",r.specimenNumber()))throw new ConflictException("SPECIMEN_NUMBER_EXISTS","error.laboratory.specimen-number");try{var specimen=order.collect(itemId,r.specimenNumber(),r.specimenType(),r.collectedAt(),r.collectedBy());repository.flush();audit(order,"COLLECT_SPECIMEN");return specimen(specimen);}catch(NoSuchElementException e){throw notFound("LabOrderItem",itemId);}catch(IllegalArgumentException e){throw rule("INVALID_SPECIMEN","error.laboratory.specimen");}}
 SpecimenResponse receive(UUID orderId,UUID specimenId){var order=write(orderId);try{order.receive(specimenId);repository.flush();audit(order,"RECEIVE_SPECIMEN");return findSpecimen(order,specimenId);}catch(NoSuchElementException e){throw notFound("Specimen",specimenId);}catch(IllegalStateException e){throw rule("INVALID_SPECIMEN_TRANSITION","error.laboratory.specimen-transition");}}
 SpecimenResponse reject(UUID orderId,UUID specimenId){var order=write(orderId);try{order.reject(specimenId);repository.flush();audit(order,"REJECT_SPECIMEN");return findSpecimen(order,specimenId);}catch(NoSuchElementException e){throw notFound("Specimen",specimenId);}catch(IllegalStateException e){throw rule("INVALID_SPECIMEN_TRANSITION","error.laboratory.specimen-transition");}}
 LabResultResponse createResult(UUID orderId,CreateResultRequest r){var order=write(orderId);requireProfessional(r.performedBy());try{var result=order.createResult(r.performedBy(),r.performedAt(),r.notes());repository.flush();audit(order,"CREATE_RESULT");return result(result);}catch(IllegalStateException e){throw rule("SPECIMENS_INCOMPLETE","error.laboratory.specimens-incomplete");}}
 LabResultItemResponse addResultItem(UUID orderId,UUID resultId,ResultItemRequest r){var order=write(orderId);var orderItem=orderItem(order,r.labOrderItemId());if(r.parameterCatalogId()!=null&&!exists("select count(*) from catalog.laboratory_parameter_catalog where id=? and exam_id=?",r.parameterCatalogId(),orderItem.getExamCatalogId()))throw rule("PARAMETER_EXAM_MISMATCH","error.laboratory.parameter-exam");var result=labResult(order,resultId);try{var item=result.addItem(orderItem,r.parameterCatalogId(),r.parameter(),r.value(),r.unit(),r.referenceMin(),r.referenceMax(),r.interpretation(),r.abnormalFlag());repository.flush();audit(order,"ADD_RESULT_ITEM");return resultItem(item);}catch(IllegalArgumentException|IllegalStateException e){throw rule("INVALID_RESULT_ITEM","error.laboratory.result-item");}}
 LabResultResponse validate(UUID orderId,UUID resultId,ValidateResultRequest r){var order=write(orderId);requireProfessional(r.validatedBy());try{order.validateResult(resultId,r.validatedBy());repository.flush();audit(order,"VALIDATE_RESULT");return result(labResult(order,resultId));}catch(NoSuchElementException e){throw notFound("LabResult",resultId);}catch(IllegalStateException e){throw rule("RESULT_INCOMPLETE_OR_FINAL","error.laboratory.result-incomplete");}}
 LabOrderResponse cancel(UUID id){var order=write(id);try{order.cancel();repository.flush();audit(order,"CANCEL_ORDER");return response(order);}catch(IllegalStateException e){throw rule("LAB_ORDER_CANNOT_CANCEL","error.laboratory.cannot-cancel");}}
 private void validateOrder(CreateOrderRequest r){if(!PRIORITIES.contains(r.priority().toUpperCase()))throw rule("INVALID_LAB_PRIORITY","error.laboratory.priority");require("patient.patient",r.patientId(),"Patient");requireProfessional(r.orderingProfessionalId());if(r.laboratoryOrganizationId()!=null)require("organization.organization",r.laboratoryOrganizationId(),"Organization");if(r.consultationId()!=null&&!exists("select count(*) from consultation.consultation where id=? and patient_id=?",r.consultationId(),r.patientId()))throw rule("CONSULTATION_PATIENT_MISMATCH","error.laboratory.consultation");var unique=new HashSet<UUID>();for(var item:r.items()){requireExam(item.labExamCatalogId());if(!unique.add(item.labExamCatalogId()))throw new ConflictException("LAB_EXAM_ALREADY_ORDERED","error.laboratory.exam-exists");}}
 private LabOrder write(UUID id){var o=get(id);access.requireAccess(o.getPatientId(),"LAB_RESULTS","WRITE");if(Set.of("COMPLETED","CANCELLED").contains(o.getStatus()))throw rule("LAB_ORDER_CLOSED","error.laboratory.closed");return o;}private LabOrder get(UUID id){return repository.findById(id).orElseThrow(()->notFound("LabOrder",id));}private LabOrderItem orderItem(LabOrder o,UUID id){try{return o.item(id);}catch(NoSuchElementException e){throw notFound("LabOrderItem",id);}}private LabResult labResult(LabOrder o,UUID id){return o.getResults().stream().filter(r->r.getId().equals(id)).findFirst().orElseThrow(()->notFound("LabResult",id));}
 private void requireExam(UUID id){if(!exists("select count(*) from catalog.laboratory_exam_catalog where id=? and active=true",id))throw notFound("LaboratoryExamCatalog",id);}private void requireProfessional(UUID id){require("professional.professional",id,"Professional");}private void require(String table,UUID id,String resource){if(!exists("select count(*) from "+table+" where id=?",id))throw notFound(resource,id);}private boolean exists(String sql,Object...args){return Objects.requireNonNull(jdbc.queryForObject(sql,Integer.class,args))>0;}private String normalize(String s){return s==null||s.isBlank()?null:s.trim().toUpperCase();}
 private void audit(LabOrder o,String action){jdbc.update("insert into audit.audit_log(actor_person_id,organization_id,module,entity_type,entity_id,action,new_value) values (?,?,?,?,?,?,?::jsonb)",actor(),o.getLaboratoryOrganizationId(),"LABORATORY","LabOrder",o.getId(),action,"{\"status\":\""+o.getStatus()+"\"}");}private UUID actor(){var a=SecurityContextHolder.getContext().getAuthentication();if(!(a instanceof JwtAuthenticationToken jwt))return null;try{UUID sub=UUID.fromString(jwt.getToken().getSubject());return jdbc.query("select id from identity.person where keycloak_user_id=? or id=? limit 1",rs->rs.next()?(UUID)rs.getObject(1):null,sub,sub);}catch(IllegalArgumentException e){return null;}}
 private OrderSummary summary(LabOrder o){return new OrderSummary(o.getId(),o.getNumber(),o.getPatientId(),o.getLaboratoryOrganizationId(),o.getPriority(),o.getOrderedAt(),o.getStatus());}private LabOrderResponse response(LabOrder o){return new LabOrderResponse(o.getId(),o.getNumber(),o.getPatientId(),o.getConsultationId(),o.getOrderingProfessionalId(),o.getLaboratoryOrganizationId(),o.getPriority(),o.getOrderedAt(),o.getStatus(),o.getItems().stream().map(this::item).toList(),o.getResults().stream().map(this::result).toList());}private LabOrderItemResponse item(LabOrderItem i){String[]exam=jdbc.query("select code,name from catalog.laboratory_exam_catalog where id=?",rs->rs.next()?new String[]{rs.getString(1),rs.getString(2)}:new String[]{null,null},i.getExamCatalogId());return new LabOrderItemResponse(i.getId(),i.getExamCatalogId(),exam[0],exam[1],i.getInstructions(),i.getStatus(),i.getSpecimens().stream().map(this::specimen).toList());}private SpecimenResponse specimen(Specimen s){return new SpecimenResponse(s.getId(),s.getNumber(),s.getType(),s.getCollectedAt(),s.getCollectedBy(),s.getStatus());}private SpecimenResponse findSpecimen(LabOrder o,UUID id){return o.getItems().stream().flatMap(i->i.getSpecimens().stream()).filter(s->s.getId().equals(id)).findFirst().map(this::specimen).orElseThrow(()->notFound("Specimen",id));}private LabResultResponse result(LabResult r){return new LabResultResponse(r.getId(),r.getNumber(),r.getPerformedBy(),r.getValidatedBy(),r.getPerformedAt(),r.getValidatedAt(),r.getStatus(),r.getNotes(),r.getItems().stream().map(this::resultItem).toList());}private LabResultItemResponse resultItem(LabResultItem i){return new LabResultItemResponse(i.getId(),i.getOrderItemId(),i.getParameterCatalogId(),i.getParameter(),i.getValue(),i.getUnit(),i.getReferenceMin(),i.getReferenceMax(),i.getInterpretation(),i.getAbnormalFlag());}
 private ResourceNotFoundException notFound(String r,Object id){return new ResourceNotFoundException(r,id);}private BusinessRuleException rule(String code,String key){return new BusinessRuleException(code,key);}
}
