package org.novasos.healthysv2.document;
import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import java.io.*;import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;import org.novasos.healthysv2.TestcontainersConfiguration;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.*;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.context.annotation.*;import org.springframework.http.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.oauth2.jwt.*;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.MockMvc;import org.springframework.mock.web.MockMultipartFile;import org.springframework.transaction.annotation.Transactional;
@ActiveProfiles("test")@SpringBootTest(properties={"spring.security.oauth2.resourceserver.jwt.issuer-uri=https://keycloak.example/realms/healthys","healthys.security.api-client-id=healthys-backend-apps","healthys.security.cors.allowed-origins=http://localhost:5173"})@AutoConfigureMockMvc@Import({TestcontainersConfiguration.class,DocumentApiIntegrationTests.Fixtures.class})@Transactional class DocumentApiIntegrationTests{
 static final UUID ADMIN=UUID.fromString("70000000-0000-0000-0000-000000000001");@Autowired MockMvc mvc;@Autowired JdbcTemplate jdbc;
 @Test void uploadsListsDownloadsAndArchivesDocument()throws Exception{UUID patient=patient();var file=new MockMultipartFile("file","report.pdf","application/pdf","clinical result".getBytes());String location=mvc.perform(multipart("/api/v1/documents").file(file).param("patientId",patient.toString()).header(HttpHeaders.AUTHORIZATION,"Bearer admin")).andExpect(status().isCreated()).andExpect(jsonPath("$.fileName").value("report.pdf")).andExpect(jsonPath("$.checksum").isNotEmpty()).andReturn().getResponse().getHeader(HttpHeaders.LOCATION);String id=location.substring(location.lastIndexOf('/')+1);mvc.perform(get("/api/v1/documents").param("patientId",patient.toString()).header(HttpHeaders.AUTHORIZATION,"Bearer admin")).andExpect(status().isOk()).andExpect(jsonPath("$.content[0].id").value(id));mvc.perform(get("/api/v1/documents/{id}/content",id).header(HttpHeaders.AUTHORIZATION,"Bearer admin")).andExpect(status().isOk()).andExpect(header().string(HttpHeaders.CONTENT_DISPOSITION,org.hamcrest.Matchers.containsString("report.pdf"))).andExpect(content().bytes("stored".getBytes()));mvc.perform(post("/api/v1/documents/{id}/archive",id).header(HttpHeaders.AUTHORIZATION,"Bearer admin")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("ARCHIVED"));}
 @Test void rejectsUnsupportedFileType()throws Exception{UUID patient=patient();var file=new MockMultipartFile("file","script.exe","application/octet-stream",new byte[]{1});mvc.perform(multipart("/api/v1/documents").file(file).param("patientId",patient.toString()).header(HttpHeaders.AUTHORIZATION,"Bearer admin")).andExpect(status().isUnprocessableContent()).andExpect(jsonPath("$.code").value("DOCUMENT_TYPE_NOT_ALLOWED"));}
 private UUID patient(){UUID person=UUID.randomUUID(),patient=UUID.randomUUID();jdbc.update("insert into identity.person(id,person_number,first_name,last_name,status) values (?,?,?,?,?)",person,"PER-"+person,"API","Patient","ACTIVE");jdbc.update("insert into patient.patient(id,person_id,patient_number) values (?,?,?)",patient,person,"PAT-"+patient);return patient;}
 @TestConfiguration(proxyBeanMethods=false)static class Fixtures{@Bean @Primary DocumentStorage documentStorage(){var storage=mock(DocumentStorage.class);when(storage.get(anyString())).thenReturn(new DocumentStorage.StoredObject(new ByteArrayInputStream("stored".getBytes()),6,"application/pdf"));return storage;}@Bean JwtDecoder jwtDecoder(){return token->{Instant now=Instant.now();return Jwt.withTokenValue(token).header("alg","RS256").subject(ADMIN.toString()).issuer("https://keycloak.example/realms/healthys").issuedAt(now).expiresAt(now.plusSeconds(300)).claim("realm_access",Map.of("roles",List.of("PLATFORM_ADMIN"))).claim("resource_access",Map.of()).build();};}}
}
