package org.novasos.healthysv2.document;
import static org.assertj.core.api.Assertions.*;import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;import org.novasos.healthysv2.TestcontainersConfiguration;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.context.annotation.Import;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.ActiveProfiles;import org.springframework.transaction.annotation.Transactional;
@ActiveProfiles("test")@Import(TestcontainersConfiguration.class)@SpringBootTest@Transactional class DocumentRepositoryIntegrationTests{
 @Autowired JdbcTemplate jdbc;
 @Test void storesDocumentMetadataAndLinksResources(){UUID patient=patient(),document=UUID.randomUUID(),resource=UUID.randomUUID();jdbc.update("insert into document.document(id,document_number,owner_patient_id,file_name,storage_key,storage_provider,mime_type,size_bytes,checksum,status) values (?,?,?,?,?,'MINIO','application/pdf',12,'abc','ACTIVE')",document,"DOC-TEST",patient,"result.pdf","patients/key");jdbc.update("insert into document.document_link(document_id,resource_type,resource_id) values (?,?,?)",document,"CONSULTATION",resource);assertThat(jdbc.queryForObject("select count(*) from document.document_link where document_id=?",Integer.class,document)).isEqualTo(1);}
 @Test void rejectsDuplicateStorageKeys(){UUID patient=patient();insert(patient,UUID.randomUUID(),"DOC-A","same-key","ACTIVE");assertThatThrownBy(()->insert(patient,UUID.randomUUID(),"DOC-B","same-key","ACTIVE")).isInstanceOf(DataIntegrityViolationException.class);}
 @Test void rejectsInvalidStatus(){UUID patient=patient();assertThatThrownBy(()->insert(patient,UUID.randomUUID(),"DOC-C","other-key","DELETED")).isInstanceOf(DataIntegrityViolationException.class);}
 private void insert(UUID patient,UUID id,String number,String key,String status){jdbc.update("insert into document.document(id,document_number,owner_patient_id,file_name,storage_key,storage_provider,status) values (?,?,?,?,?,'MINIO',?)",id,number,patient,"file.pdf",key,status);jdbc.execute("set constraints all immediate");}private UUID patient(){UUID person=UUID.randomUUID(),patient=UUID.randomUUID();jdbc.update("insert into identity.person(id,person_number,first_name,last_name,status) values (?,?,?,?,?)",person,"PER-"+person,"Doc","Patient","ACTIVE");jdbc.update("insert into patient.patient(id,person_id,patient_number) values (?,?,?)",patient,person,"PAT-"+patient);return patient;}
}
