package org.novasos.healthysv2.professional;
import static org.novasos.healthysv2.professional.api.ProfessionalDtos.*;
import java.net.URI; import java.util.*; import jakarta.validation.Valid;
import io.swagger.v3.oas.annotations.*; import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.data.domain.Pageable; import org.springframework.http.ResponseEntity; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*;
import org.novasos.healthysv2.shared.api.ApiPaths; import org.novasos.healthysv2.shared.api.dto.PageResponse;
@RestController @RequestMapping(ApiPaths.V1+"/professionals") @Tag(name="Professionals",description="Professionals, licences, specialities, assignments, schedules and availabilities")
@PreAuthorize("hasAnyRole('PLATFORM_ADMIN','HOSPITAL_ADMIN','HOSPITAL_AGENT','DOCTOR','NURSE','PHARMACIST','LAB_TECHNICIAN')")
class ProfessionalController {
 private static final String WRITE="hasAnyRole('PLATFORM_ADMIN','HOSPITAL_ADMIN')"; private final ProfessionalService service; ProfessionalController(ProfessionalService s){service=s;}
 @GetMapping @Operation(summary="Search professionals") PageResponse<ProfessionalSummary> list(@RequestParam(defaultValue="") String query,Pageable pageable){return service.findAll(query,pageable);}
 @GetMapping("/specialities") @Operation(summary="List speciality catalogue") List<SpecialityCatalogResponse> specialities(){return service.specialityCatalog();}
 @GetMapping("/{id}") @Operation(summary="Get a professional") ProfessionalResponse get(@PathVariable UUID id){return service.find(id);}
 @PostMapping @PreAuthorize(WRITE) @Operation(summary="Create a professional") ResponseEntity<ProfessionalResponse> create(@Valid @RequestBody ProfessionalRequest r){var out=service.create(r);return ResponseEntity.created(URI.create(ApiPaths.V1+"/professionals/"+out.id())).body(out);}
 @PutMapping("/{id}") @PreAuthorize(WRITE) ProfessionalResponse update(@PathVariable UUID id,@Valid @RequestBody ProfessionalUpdateRequest r){return service.update(id,r);} @DeleteMapping("/{id}") @PreAuthorize(WRITE) ResponseEntity<Void> delete(@PathVariable UUID id){service.delete(id);return ResponseEntity.noContent().build();}
 @PostMapping("/{p}/licenses") @PreAuthorize(WRITE) ResponseEntity<LicenseResponse> addLicense(@PathVariable UUID p,@Valid @RequestBody LicenseRequest r){return ResponseEntity.status(201).body(service.addLicense(p,r));}
 @PutMapping("/{p}/licenses/{id}") @PreAuthorize(WRITE) LicenseResponse updateLicense(@PathVariable UUID p,@PathVariable UUID id,@Valid @RequestBody LicenseRequest r){return service.updateLicense(p,id,r);} @DeleteMapping("/{p}/licenses/{id}") @PreAuthorize(WRITE) ResponseEntity<Void> deleteLicense(@PathVariable UUID p,@PathVariable UUID id){service.deleteLicense(p,id);return ResponseEntity.noContent().build();}
 @PostMapping("/{p}/specialities") @PreAuthorize(WRITE) ResponseEntity<SpecialityResponse> addSpeciality(@PathVariable UUID p,@Valid @RequestBody SpecialityRequest r){return ResponseEntity.status(201).body(service.addSpeciality(p,r));} @DeleteMapping("/{p}/specialities/{id}") @PreAuthorize(WRITE) ResponseEntity<Void> deleteSpeciality(@PathVariable UUID p,@PathVariable UUID id){service.deleteSpeciality(p,id);return ResponseEntity.noContent().build();}
 @PostMapping("/{p}/assignments") @PreAuthorize(WRITE) ResponseEntity<AssignmentResponse> addAssignment(@PathVariable UUID p,@Valid @RequestBody AssignmentRequest r){return ResponseEntity.status(201).body(service.addAssignment(p,r));}
 @PutMapping("/{p}/assignments/{id}") @PreAuthorize(WRITE) AssignmentResponse updateAssignment(@PathVariable UUID p,@PathVariable UUID id,@Valid @RequestBody AssignmentRequest r){return service.updateAssignment(p,id,r);} @DeleteMapping("/{p}/assignments/{id}") @PreAuthorize(WRITE) ResponseEntity<Void> deleteAssignment(@PathVariable UUID p,@PathVariable UUID id){service.deleteAssignment(p,id);return ResponseEntity.noContent().build();}
 @PostMapping("/{p}/assignments/{a}/schedules") @PreAuthorize(WRITE) ResponseEntity<ScheduleResponse> addSchedule(@PathVariable UUID p,@PathVariable UUID a,@Valid @RequestBody ScheduleRequest r){return ResponseEntity.status(201).body(service.addSchedule(p,a,r));}
 @PutMapping("/{p}/assignments/{a}/schedules/{id}") @PreAuthorize(WRITE) ScheduleResponse updateSchedule(@PathVariable UUID p,@PathVariable UUID a,@PathVariable UUID id,@Valid @RequestBody ScheduleRequest r){return service.updateSchedule(p,a,id,r);} @DeleteMapping("/{p}/assignments/{a}/schedules/{id}") @PreAuthorize(WRITE) ResponseEntity<Void> deleteSchedule(@PathVariable UUID p,@PathVariable UUID a,@PathVariable UUID id){service.deleteSchedule(p,a,id);return ResponseEntity.noContent().build();}
 @PostMapping("/{p}/assignments/{a}/availabilities") @PreAuthorize(WRITE) ResponseEntity<AvailabilityResponse> addAvailability(@PathVariable UUID p,@PathVariable UUID a,@Valid @RequestBody AvailabilityRequest r){return ResponseEntity.status(201).body(service.addAvailability(p,a,r));}
 @PutMapping("/{p}/assignments/{a}/availabilities/{id}") @PreAuthorize(WRITE) AvailabilityResponse updateAvailability(@PathVariable UUID p,@PathVariable UUID a,@PathVariable UUID id,@Valid @RequestBody AvailabilityRequest r){return service.updateAvailability(p,a,id,r);} @DeleteMapping("/{p}/assignments/{a}/availabilities/{id}") @PreAuthorize(WRITE) ResponseEntity<Void> deleteAvailability(@PathVariable UUID p,@PathVariable UUID a,@PathVariable UUID id){service.deleteAvailability(p,a,id);return ResponseEntity.noContent().build();}
}
