package org.novasos.healthysv2.messaging;
import static org.novasos.healthysv2.messaging.api.MessagingDtos.*;import java.sql.*;import java.time.*;import java.util.*;import org.novasos.healthysv2.patient.*;import org.novasos.healthysv2.shared.api.dto.PageResponse;import org.novasos.healthysv2.shared.api.error.*;import org.springframework.data.domain.*;import org.springframework.jdbc.core.*;import org.springframework.messaging.simp.SimpMessagingTemplate;import org.springframework.security.access.AccessDeniedException;import org.springframework.security.core.Authentication;import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.transaction.support.TransactionSynchronization;import org.springframework.transaction.support.TransactionSynchronizationManager;import org.springframework.security.core.context.SecurityContextHolder;
@Service @Transactional public class ConversationService{
 private static final Set<String>TYPES=Set.of("DIRECT","CARE_TEAM","PATIENT_SUPPORT","GROUP"),MESSAGE_TYPES=Set.of("TEXT","DOCUMENT","SYSTEM");private final JdbcTemplate jdbc;private final CurrentUserContext users;private final PatientAccessService patientAccess;private final SimpMessagingTemplate broker;
 ConversationService(JdbcTemplate jdbc,CurrentUserContext users,PatientAccessService patientAccess,SimpMessagingTemplate broker){this.jdbc=jdbc;this.users=users;this.patientAccess=patientAccess;this.broker=broker;}
 public ConversationResponse create(CreateConversationRequest r){UUID actor=requireCurrentPerson();requirePatientRecipients(actor,r.patientId(),r.participantPersonIds());String type=normalize(r.type());if(!TYPES.contains(type))throw rule("INVALID_CONVERSATION_TYPE","error.messaging.conversation-type");if(r.patientId()!=null)patientAccess.requireAccess(r.patientId(),"COMMUNICATION","READ");Set<UUID>participants=new HashSet<>(r.participantPersonIds());participants.add(actor);participants.forEach(this::requirePerson);UUID id=UUID.randomUUID();jdbc.update("insert into communication.conversation(id,conversation_number,type,subject,patient_id,created_by) values (?,?,?,?,?,?)",id,"CONV-"+UUID.randomUUID().toString().substring(0,12).toUpperCase(),type,blank(r.subject()),r.patientId(),actor);for(UUID person:participants)jdbc.update("insert into communication.conversation_participant(conversation_id,person_id,participant_role) values (?,?,?)",id,person,person.equals(actor)?"CREATOR":"MEMBER");audit(actor,id,"CREATE_CONVERSATION");invalidate(id);return find(id);}
 @Transactional(readOnly=true)public PageResponse<ConversationSummary>list(Pageable pageable){requirePage(pageable);UUID person=requireCurrentPerson();String sql="select c.id,c.conversation_number,c.type,c.subject,c.patient_id,c.created_at,c.status,(select m.content from communication.message m where m.conversation_id=c.id and m.deleted_at is null order by m.sent_at desc,m.id desc limit 1),(select m.sent_at from communication.message m where m.conversation_id=c.id and m.deleted_at is null order by m.sent_at desc,m.id desc limit 1),(select count(*) from communication.message m join communication.message_receipt r on r.message_id=m.id where m.conversation_id=c.id and m.deleted_at is null and r.person_id=? and r.read_at is null) from communication.conversation c join communication.conversation_participant cp on cp.conversation_id=c.id where cp.person_id=? and cp.status='ACTIVE' and cp.left_at is null order by coalesce((select max(m.sent_at) from communication.message m where m.conversation_id=c.id),c.created_at) desc,c.id desc limit ? offset ?";List<ConversationSummary>content=jdbc.query(sql,(rs,n)->summary(rs,person),person,person,pageable.getPageSize(),pageable.getOffset());long total=Objects.requireNonNull(jdbc.queryForObject("select count(*) from communication.conversation_participant where person_id=? and status='ACTIVE' and left_at is null",Long.class,person));return PageResponse.from(new PageImpl<>(content,pageable,total));}
 @Transactional(readOnly=true)public ConversationResponse find(UUID id){UUID person=requireCurrentPerson();requireParticipant(id,person);return conversation(id);}
 @Transactional(readOnly=true)public PageResponse<MessageResponse>messages(UUID conversationId,Pageable pageable){requirePage(pageable);UUID person=requireCurrentPerson();requireParticipant(conversationId,person);String sql="select m.id,m.conversation_id,m.sender_person_id,concat(p.first_name,' ',p.last_name),m.type,m.content,m.reply_to_message_id,m.sent_at,m.edited_at,m.deleted_at,exists(select 1 from communication.message_receipt r where r.message_id=m.id and r.person_id=? and r.read_at is not null) from communication.message m join identity.person p on p.id=m.sender_person_id where m.conversation_id=? order by m.sent_at desc,m.id desc limit ? offset ?";List<MessageResponse>content=jdbc.query(sql,(rs,n)->message(rs,person),person,conversationId,pageable.getPageSize(),pageable.getOffset());long total=Objects.requireNonNull(jdbc.queryForObject("select count(*) from communication.message where conversation_id=?",Long.class,conversationId));return PageResponse.from(new PageImpl<>(content,pageable,total));}
 public MessageResponse send(UUID conversationId,SendMessageRequest request){return send(conversationId,request,requireCurrentPerson());}public MessageResponse send(UUID conversationId,SendMessageRequest request,Authentication authentication){var previous=SecurityContextHolder.getContext();var context=SecurityContextHolder.createEmptyContext();context.setAuthentication(authentication);SecurityContextHolder.setContext(context);try{return send(conversationId,request,personId(authentication));}finally{SecurityContextHolder.setContext(previous);}}
 private MessageResponse send(UUID conversationId,SendMessageRequest r,UUID sender){requireParticipant(conversationId,sender);String type=normalize(r.type());if(!MESSAGE_TYPES.contains(type))throw rule("INVALID_MESSAGE_TYPE","error.messaging.message-type");if(!"DOCUMENT".equals(type)&&(r.content()==null||r.content().isBlank()))throw rule("MESSAGE_CONTENT_REQUIRED","error.messaging.content-required");if(r.replyToMessageId()!=null&&!exists("select count(*) from communication.message where id=? and conversation_id=?",r.replyToMessageId(),conversationId))throw new ResourceNotFoundException("Message",r.replyToMessageId());for(UUID document:r.documentIds())requireSendDocument(conversationId,document,sender);if("DOCUMENT".equals(type)&&r.documentIds().isEmpty())throw rule("MESSAGE_ATTACHMENT_REQUIRED","error.messaging.content-required");UUID id=UUID.randomUUID();jdbc.update("insert into communication.message(id,conversation_id,sender_person_id,type,content,reply_to_message_id) values (?,?,?,?,?,?)",id,conversationId,sender,type,blank(r.content()),r.replyToMessageId());for(UUID document:r.documentIds())jdbc.update("insert into communication.message_attachment(message_id,document_id) values (?,?)",id,document);jdbc.update("insert into communication.message_receipt(message_id,person_id,delivered_at,read_at) select ?,person_id,now(),case when person_id=? then now() else null end from communication.conversation_participant where conversation_id=? and status='ACTIVE' and left_at is null",id,sender,conversationId);MessageResponse out=findMessage(id,sender);audit(sender,conversationId,"SEND_MESSAGE");publish("/topic/conversations/"+conversationId,new MessageResponse(out.id(),out.conversationId(),out.senderPersonId(),out.senderName(),out.type(),out.content(),out.replyToMessageId(),out.sentAt(),out.editedAt(),out.deletedAt(),out.documentIds(),false,out.readByOthersCount()));invalidate(conversationId);return out;}
 public ConversationResponse addParticipant(UUID conversationId,AddParticipantRequest r){UUID actor=requireCurrentPerson();requireParticipant(conversationId,actor);requirePatientRecipients(actor,conversation(conversationId).patientId(),Set.of(r.personId()));requirePerson(r.personId());jdbc.update("insert into communication.conversation_participant(conversation_id,person_id,participant_role) values (?,?,?) on conflict(conversation_id,person_id) do update set status='ACTIVE',left_at=null,participant_role=excluded.participant_role",conversationId,r.personId(),blank(r.role()));audit(actor,conversationId,"ADD_PARTICIPANT");invalidate(conversationId);return conversation(conversationId);}
 public ReadReceiptResponse markRead(UUID messageId){UUID person=requireCurrentPerson();UUID conversation=jdbc.query("select conversation_id from communication.message where id=?",rs->rs.next()?(UUID)rs.getObject(1):null,messageId);if(conversation==null)throw new ResourceNotFoundException("Message",messageId);requireParticipant(conversation,person);jdbc.update("insert into communication.message_receipt(message_id,person_id,delivered_at,read_at) values (?,?,now(),now()) on conflict(message_id,person_id) do update set delivered_at=coalesce(message_receipt.delivered_at,now()),read_at=now()",messageId,person);Timestamp value=jdbc.queryForObject("select read_at from communication.message_receipt where message_id=? and person_id=?",Timestamp.class,messageId,person);var out=new ReadReceiptResponse(messageId,person,value.toInstant());publish("/topic/conversations/"+conversation+"/receipts",out);invalidate(conversation);return out;}
 public boolean maySubscribe(Authentication authentication,UUID conversation){try{return isParticipant(conversation,personId(authentication));}catch(RuntimeException e){return false;}}public UUID personId(Authentication authentication){if(!(authentication instanceof JwtAuthenticationToken jwt))throw new AccessDeniedException("JWT_REQUIRED");if(jwt.getToken().getExpiresAt()==null||!jwt.getToken().getExpiresAt().isAfter(Instant.now()))throw new AccessDeniedException("SESSION_EXPIRED");try{UUID subject=UUID.fromString(jwt.getToken().getSubject());UUID person=jdbc.query("select id from identity.person where keycloak_user_id=? and status='ACTIVE' limit 1",rs->rs.next()?(UUID)rs.getObject(1):null,subject);if(person==null)throw new AccessDeniedException("PERSON_CONTEXT_MISSING");return person;}catch(IllegalArgumentException e){throw new AccessDeniedException("INVALID_SUBJECT");}}
 private UUID requireCurrentPerson(){return personId(SecurityContextHolder.getContext().getAuthentication());}public UUID requireMember(UUID conversation){UUID person=requireCurrentPerson();requireParticipant(conversation,person);return person;}private void requireParticipant(UUID conversation,UUID person){if(!isParticipant(conversation,person))throw new AccessDeniedException("CONVERSATION_ACCESS_DENIED");}private boolean isParticipant(UUID conversation,UUID person){return exists("select count(*) from communication.conversation_participant cp join communication.conversation c on c.id=cp.conversation_id where cp.conversation_id=? and cp.person_id=? and cp.status='ACTIVE' and cp.left_at is null and c.status='ACTIVE'",conversation,person);}private void requirePerson(UUID id){if(!exists("select count(*) from identity.person where id=? and status='ACTIVE'",id))throw new ResourceNotFoundException("Person",id);}private boolean exists(String sql,Object...args){return Objects.requireNonNull(jdbc.queryForObject(sql,Integer.class,args))>0;}
 private ConversationResponse conversation(UUID id){return jdbc.query("select id,conversation_number,type,subject,patient_id,created_by,created_at,status from communication.conversation where id=?",rs->{if(!rs.next())throw new ResourceNotFoundException("Conversation",id);return new ConversationResponse((UUID)rs.getObject(1),rs.getString(2),rs.getString(3),rs.getString(4),(UUID)rs.getObject(5),(UUID)rs.getObject(6),rs.getTimestamp(7).toInstant(),rs.getString(8),participants(id));},id);}private List<ParticipantResponse>participants(UUID id){return jdbc.query("select cp.person_id,concat(p.first_name,' ',p.last_name),cp.participant_role,cp.joined_at,cp.status from communication.conversation_participant cp join identity.person p on p.id=cp.person_id where cp.conversation_id=? order by cp.joined_at",(rs,n)->new ParticipantResponse((UUID)rs.getObject(1),rs.getString(2),rs.getString(3),rs.getTimestamp(4).toInstant(),rs.getString(5)),id);}
 private ConversationSummary summary(ResultSet rs,UUID person)throws SQLException{UUID id=(UUID)rs.getObject(1);Timestamp last=rs.getTimestamp(9);return new ConversationSummary(id,rs.getString(2),rs.getString(3),rs.getString(4),(UUID)rs.getObject(5),rs.getTimestamp(6).toInstant(),rs.getString(7),rs.getString(8),last==null?null:last.toInstant(),rs.getLong(10),participants(id));}private MessageResponse message(ResultSet rs,UUID person)throws SQLException{UUID id=(UUID)rs.getObject(1);return new MessageResponse(id,(UUID)rs.getObject(2),(UUID)rs.getObject(3),rs.getString(4),rs.getString(5),instant(rs,10)==null?rs.getString(6):null,(UUID)rs.getObject(7),rs.getTimestamp(8).toInstant(),instant(rs,9),instant(rs,10),instant(rs,10)==null?documents(id):List.of(),rs.getBoolean(11),Objects.requireNonNull(jdbc.queryForObject("select count(*) from communication.message_receipt where message_id=? and person_id<>? and read_at is not null",Long.class,id,rs.getObject(3,UUID.class))));}private MessageResponse findMessage(UUID id,UUID person){return jdbc.query("select m.id,m.conversation_id,m.sender_person_id,concat(p.first_name,' ',p.last_name),m.type,m.content,m.reply_to_message_id,m.sent_at,m.edited_at,m.deleted_at,exists(select 1 from communication.message_receipt r where r.message_id=m.id and r.person_id=? and r.read_at is not null) from communication.message m join identity.person p on p.id=m.sender_person_id where m.id=?",rs->{if(!rs.next())throw new ResourceNotFoundException("Message",id);return message(rs,person);},person,id);}private List<UUID>documents(UUID message){return jdbc.queryForList("select document_id from communication.message_attachment where message_id=?",UUID.class,message);}private Instant instant(ResultSet rs,int column)throws SQLException{Timestamp value=rs.getTimestamp(column);return value==null?null:value.toInstant();}
 @Transactional(readOnly=true)public List<RecipientResponse> recipients(){
  UUID actor=requireCurrentPerson();
  return jdbc.query("select distinct person.id,concat(person.first_name,' ',person.last_name),professional.id from patient.patient patient join patient.care_relationship relationship on relationship.patient_id=patient.id join professional.professional professional on professional.id=relationship.professional_id join identity.person person on person.id=professional.person_id where patient.person_id=? and relationship.status='ACTIVE' and relationship.start_date<=now() and (relationship.end_date is null or relationship.end_date>now()) and professional.status='ACTIVE' and person.status='ACTIVE' order by 2,1",(rs,n)->new RecipientResponse(rs.getObject(1,UUID.class),rs.getString(2),rs.getObject(3,UUID.class)),actor);
 }
 private void requirePatientRecipients(UUID actor,UUID patient,Set<UUID> recipients){
  var user=users.current();if(!user.has("PATIENT")||user.hasAny("PLATFORM_ADMIN","HOSPITAL_ADMIN","DOCTOR","NURSE"))return;
  UUID self=jdbc.query("select id from patient.patient where person_id=?",rs->rs.next()?rs.getObject(1,UUID.class):null,actor);
  if(self==null||(patient!=null&&!self.equals(patient)))throw new AccessDeniedException("PATIENT_CONVERSATION_ACCESS_DENIED");
  Set<UUID> allowed=new HashSet<>();this.recipients().forEach(r->allowed.add(r.personId()));allowed.add(actor);
  if(!allowed.containsAll(recipients))throw new AccessDeniedException("RECIPIENT_OUTSIDE_CARE_TEAM");
 }
 private void requirePage(Pageable pageable){if(pageable.getPageSize()>100)throw rule("INVALID_PAGE","error.malformed");}
 private void requireSendDocument(UUID conversation,UUID document,UUID sender){
  boolean scoped=exists("select count(*) from document.document d join document.document_link l on l.document_id=d.id where d.id=? and d.status='ACTIVE' and d.uploaded_by=? and l.resource_type='CONVERSATION' and l.resource_id=?",document,sender,conversation);
  boolean ownPublished=exists("select count(*) from document.document d join patient.patient p on p.id=d.owner_patient_id join communication.conversation c on c.id=? where d.id=? and d.status='ACTIVE' and d.patient_visible=true and not exists(select 1 from document.document_link where document_id=d.id and resource_type='CONVERSATION') and p.person_id=? and (c.patient_id is null or c.patient_id=p.id)",conversation,document,sender);
  if(!scoped&&!ownPublished){UUID patient=jdbc.query("select d.owner_patient_id from document.document d join communication.conversation c on c.id=? where d.id=? and d.status='ACTIVE' and (c.patient_id is null or c.patient_id=d.owner_patient_id) and not exists(select 1 from document.document_link where document_id=? and resource_type='CONVERSATION')",rs->rs.next()?rs.getObject(1,UUID.class):null,conversation,document,document);if(patient==null)throw new AccessDeniedException("MESSAGE_DOCUMENT_ACCESS_DENIED");var actor=users.current();if(actor.has("PATIENT")&&!actor.hasAny("PLATFORM_ADMIN","HOSPITAL_ADMIN","DOCTOR","NURSE"))throw new AccessDeniedException("MESSAGE_DOCUMENT_ACCESS_DENIED");patientAccess.requireAccess(patient,"DOCUMENTS","READ");}
 }
 private void invalidate(UUID conversation){jdbc.queryForList("select person_id from communication.conversation_participant where conversation_id=? and status='ACTIVE' and left_at is null",UUID.class,conversation).forEach(person->publish("/topic/messaging/users/"+person,Map.of("conversationId",conversation)));}
 private void publish(String destination,Object payload){
  if(TransactionSynchronizationManager.isSynchronizationActive())TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){@Override public void afterCommit(){broker.convertAndSend(destination,payload);}});
  else broker.convertAndSend(destination,payload);
 }
 private void audit(UUID actor,UUID entity,String action){jdbc.update("insert into audit.audit_log(actor_person_id,module,entity_type,entity_id,action) values (?,'MESSAGING','Conversation',?,?)",actor,entity,action);}private String normalize(String value){return value==null?"":value.trim().toUpperCase();}private String blank(String value){return value==null||value.isBlank()?null:value.trim();}private BusinessRuleException rule(String code,String key){return new BusinessRuleException(code,key);}
}
