package org.novasos.healthysv2.messaging;
import java.util.*;import org.springframework.beans.factory.ObjectProvider;import org.springframework.beans.factory.annotation.Value;import org.springframework.context.annotation.Configuration;import org.springframework.messaging.*;import org.springframework.messaging.simp.config.*;import org.springframework.messaging.simp.stomp.*;import org.springframework.messaging.support.ChannelInterceptor;import org.springframework.security.access.AccessDeniedException;import org.springframework.security.core.Authentication;import org.springframework.security.oauth2.jwt.JwtDecoder;import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationConverter;import org.springframework.web.socket.config.annotation.*;
@Configuration @EnableWebSocketMessageBroker class MessagingWebSocketConfiguration implements WebSocketMessageBrokerConfigurer{
 private final ObjectProvider<JwtDecoder> decoder;private final ObjectProvider<JwtAuthenticationConverter> converter;private final ObjectProvider<ConversationService> conversations;private final String[] origins;
 MessagingWebSocketConfiguration(ObjectProvider<JwtDecoder> decoder,ObjectProvider<JwtAuthenticationConverter> converter,ObjectProvider<ConversationService> conversations,@Value("${healthys.security.cors.allowed-origins:http://localhost:5173}")String origins){this.decoder=decoder;this.converter=converter;this.conversations=conversations;this.origins=Arrays.stream(origins.split(",")).map(String::trim).toArray(String[]::new);}
 @Override public void registerStompEndpoints(StompEndpointRegistry registry){registry.addEndpoint("/ws").setAllowedOrigins(origins);}
 @Override public void configureMessageBroker(MessageBrokerRegistry registry){registry.setApplicationDestinationPrefixes("/app");registry.enableSimpleBroker("/topic");}
 @Override public void configureClientInboundChannel(ChannelRegistration registration){registration.interceptors(new ChannelInterceptor(){@Override public Message<?>preSend(Message<?>message,MessageChannel channel){var accessor=StompHeaderAccessor.wrap(message);if(StompCommand.CONNECT.equals(accessor.getCommand())){String header=accessor.getFirstNativeHeader("Authorization");JwtDecoder jwtDecoder=decoder.getIfAvailable();JwtAuthenticationConverter authenticationConverter=converter.getIfAvailable();if(header==null||!header.startsWith("Bearer ")||jwtDecoder==null||authenticationConverter==null)throw new AccessDeniedException("JWT_REQUIRED");accessor.setUser(authenticationConverter.convert(jwtDecoder.decode(header.substring(7))));}else if(StompCommand.SUBSCRIBE.equals(accessor.getCommand())){String destination=accessor.getDestination();if(destination!=null&&destination.startsWith("/topic/conversations/")){String value=destination.substring("/topic/conversations/".length()).split("/")[0];try{if(!(accessor.getUser() instanceof Authentication authentication)||!conversations.getObject().maySubscribe(authentication,UUID.fromString(value)))throw new AccessDeniedException("CONVERSATION_ACCESS_DENIED");}catch(IllegalArgumentException e){throw new AccessDeniedException("INVALID_CONVERSATION_DESTINATION");}}}return message;}});}
}
